### ISSUE TITLE
EQ Knobs

### ISSUE THREAD

**Issue by sdatkinson** [sdatkinson/NeuralAmpModelerPlugin#1]
Add in a simple treble/mid/bass set of knobs that can be used to EQ the model. Some simple filters that act just ahead of the ML model would be fine as a first step.

**Comment by arsafes** [comment]
I'd actually include a pre-post switch for the EQ, so that it can be used both as a pre-filter and as a more standard post-gainstage eq

**Comment by sdatkinson** [comment]
Right. The first version of this feature will focus on post-EQ; we'll see about a pre/post switch later on.
