### ISSUE TITLE
Volume differences

### ISSUE THREAD

**Issue by jaredbehrens** [sdatkinson/NeuralAmpModelerPlugin#10]
I noticed that the difference in volume between profiles can be quite large, depending on how loud the output.wav is. Perhaps having a guideline that tells users how loud output.wav should be would help make everyone's profiles more uniform.

If you are open to this idea I can do more testing and provide what I think is an optimal range.

**Comment by sdatkinson** [comment]
I can see how this could be useful.  I have to admit that I really like how the models tend to come out exactly like their sources, so this could make it harder to demonstrate that.

On the other hand, I can see how this would be really useful.

But this is a potentially good idea. I'm going to do some research to find out what people tend to prefer and then come back to this.

**Comment by jaredbehrens** [comment]
Instead of changing the code, how about providing people a recommended volume for the output.wav - that way if people follow instruction profiles will stay fairly uniform but nothing changes with the actual product.

**Comment by sdatkinson** [comment]
Seems like people agree with you. I'm going to mark this as invalid and we'll do something about it :)

**Comment by Eraz102** [comment]
Perhaps a volume compensation switch? So people who would like to have the same volume for all their profiles can switch that on. Otherwhise its the volume of the model, and how it was captured?

**Comment by jaredbehrens** [comment]
I like that idea! I do think some documentation with recommended levels
would be helpful to the overall community as well. Thanks for all your
efforts.

**Comment by sdatkinson** [comment]
Resolved by #175
