### ISSUE TITLE
[BUG] Impulse responses seem too loud

### ISSUE THREAD

**Issue by sdatkinson** [sdatkinson/NeuralAmpModelerPlugin#100]
IRs seem,to play 10db+ louder than they do in other IR loaders. Is the math wrong? Compare with some other IR loaders and see what's going on.

**Comment by mikeoliphant** [comment]
From my own IR loading code:

`    float gain = pow(10, -18 * 0.05);  // IRs are usually too loud`

Can't remember the specifics of why I used -18db, though...

**Comment by sdatkinson** [comment]
I'd like to first check that it at least does what I intended, but then yeah probably slapping in a gain adjustment is probably fine.

**Comment by sdatkinson** [comment]
Will track on [NeuralAmpModelerCore](https://github.com/sdatkinson/NeuralAmpModelerCore/issues/7).
