### ISSUE TITLE
[FEATURE] 96kHz support

### ISSUE THREAD

**Issue by James-F2** [sdatkinson/NeuralAmpModelerPlugin#101]
Please include 96kHz support for the VST plugin.
I thought the training process was creating bad captures, turns out my DAW project was set to 96kHz which makes all captures sound broken, but when the DAW is set to 48kHz captures sound correct.

**Comment by sdatkinson** [comment]
Good catch. I'm tracking this with #59, so I'll close this one as a duplicate
