### ISSUE TITLE
Help guys: Windows 11 when I set the Asio drivers in the Preferences and apply ok Neural Amp Modeler in standalone it doesn't start[BUG]

### ISSUE THREAD

**Issue by seve54** [sdatkinson/NeuralAmpModelerPlugin#103]
**Thanks for taking the time to write a bug report!** Use the following prompts to help you describe what's going on.  The more info you provide, the easier it'll be to understand how to fix it for you without having to come back and ask you questions.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS [e.g. Windows 10, macOS 10.15]
 - Plugin version [e.g. 0.6.1]
 - Standalone, VST3, or AU
 - DAW (if applicable)

**Additional context**

**Comment by seve54** [comment]
Help guys: Windows 11 when I set the Asio drivers in the Preferences and apply ok Neural Amp Modeler in standalone it doesn't start

**Comment by sdatkinson** [comment]
Hi!

Would you mind editing the OP to fill out some of the other info?  This might help with figuring out what's going on.

**Comment by sdatkinson** [comment]
Duplicate, will follow this in #106
