### ISSUE TITLE
[BUG] Cubase 10 crash (NAM v. 0.7.0)

### ISSUE THREAD

**Issue by eArt67** [sdatkinson/NeuralAmpModelerPlugin#104]
NAM version 0.7.0
Running one instances seems fairly stable, but adding one or more crashes Cubase most times with no error messages. Using alt key to copy instances in Cubase mixer (from one insert to another) is a guaranteed crash.

Cubase 10
Win 10/64

**Comment by sdatkinson** [comment]
Sorry to hear this--I was really hoping that I found the big root cause with #76 

Can you give me more info about the tracks involved? Is NAM the only plugin on their signal chain?

**Comment by eArt67** [comment]
It does not seem to matter - I have tried to disable all other plugins and it still crashes. 

Let me know if there is anything I can do to help you track down this!

**Comment by eArt67** [comment]
Short update: Since Steinberg is running a sale on Cubase 12 upgrades, I decided it was time. A short test so far proves very promising - I could without a crash copy several new instances and run 8 in parallel. Obviously I have no idea what differs between Cubase 10 and 12 but so far so good...

**Comment by QuickChemist** [comment]
> Short update: Since Steinberg is running a sale on Cubase 12 upgrades, I decided it was time. A short test so far proves very promising - I could without a crash copy several new instances and run 8 in parallel. Obviously I have no idea what differs between Cubase 10 and 12 but so far so good...

Weird, i'm running 12.0.60 and I can only open one instance before crashing my whole daw with a runtime error

**Comment by sdatkinson** [comment]
I believe this was addressed with #298
