### ISSUE TITLE
Extra Slots + Switch to choose between 'Series' or 'Parallel' + Blend knob [FEATURE]

### ISSUE THREAD

**Issue by DomMcsweeney** [sdatkinson/NeuralAmpModelerPlugin#111]
It'd be pretty fantastic to have an extra slot to load up a second model into NAM plugin, with a switch to decide between series or parallel modes, and if in parallel mode - a blend knob to control the balance between two models.
  
example 1 - for an overdrive pedal + amp model to be loaded in one instance of the plugin (series mode)
example 2 - for loading two drive pedals or amp models (parallel mode)  

Quick GUI mockup: 

![image](https://user-images.githubusercontent.com/86134812/224240501-063a5165-f684-4ed1-a8b5-9b9b36adab22.png)

Thanks Steve! 
- Dom

**Comment by sdatkinson** [comment]
Revisiting older Issues to clean up & get closure where possible. I think I'm not going to be pursuing this feature in this repo.
