### ISSUE TITLE
[FEATURE] central zero-maintenance repositiry for models/IRs community implemented in GitHub itself  

### ISSUE THREAD

**Issue by hrstoyanov** [sdatkinson/NeuralAmpModelerPlugin#112]
This is a proposal on how to implement a community database for sharing models/IRs and rate them.

TONEX and other similar tools already have somewhat usable central database that allows the respective community to freely share models, IRs, etc. This is a huge advantage, and NAM should do this too. Unlike TONEX, there is no paid db admin, rented server,  to maintain a highly available, world-wide database, but I think NAM can achieve the same self-hosted, distributed implementation, utilizing GitHub itself, which it already depends on anyway!

Basically, each contributer will be a GitHub user and and will maintain own repo with his/her NAM captured models. The content of the repo will follow some structure that NAM requires and can recognize.
When a contributor wants to share his/her models with the community they should open a issue request with the URL pointing back to their GitHub repo. All registered contributions (repo URLs) would be maintained in a data file in the NAM repo itself.
In other to rate a particular contribution repo, one would just go and give a GitHub star to that repo.
Upon startup, NAM will launch a thread to download the data file (it is just http request to a well-known URL in GitHub) download the file and parse  the contribution URLs inside, also downloading the repo ratings, and store all this in a local database for fast subsequent access/searchability (btw TONEX uses local SQLLite). There should be a button in the UI to refresh this local/embedded database at user's will. Note that downloading the actual model should happen only if required by the user.

The advantage of using GitHub repos over Google docs links is:
- github repos stars for ranking the models
- 0 maintenance cost
- user management is taken care of.
- git allows for versioning and cloning.

The above implementation requires that every NAM contributed must be a registered GitHub user, which I think is not a big deal. Further, there is published GitHub Rest API that can be used, on behalf of the logged in user. This can all be part of NAM UI  itself.

**Comment by James-F2** [comment]
This is a great idea, but I have a few questions.
How would you suggest users will search for specific models, let's say a boosted JCM800 or a IIC+ if the main repository only contains links to other repositories?
What about metadata and info about the model?

PS.
I will NEVER register on facebook, so for me there is currently no centralized place to talk about and ask questions about NAM.
I think https://github.com/sdatkinson/NeuralAmpModelerPlugin/issues/105 is a great idea too.

**Comment by David-Else** [comment]
> I will NEVER register on facebook

+ 1

**Comment by avanzzzi** [comment]
I like the github repository idea but, at the same time, I'm starting a flask project to be some kind of "model center". It have a database to store the models and metadata (outside of the nam files). Will make a simple version first and share here.

**Comment by hrstoyanov** [comment]
@James-F2 
I think the central GitHub repo file is only used to seed/refresh a local Embedded database (like sqllite) which is searchable. 

The major advantages of the GitHub models store are:
- guthub stars are natural voting system for models.
- 0 maintenance/ server expenses.
- security/user management is taken care of
- git branches can also be used, fir models versioning.

**Comment by hrstoyanov** [comment]
@James-F2 
Regarding issue #105 :
GitHub already has "discussions" - the repo admin just needs to enable it. This replaces the need for external forums like discord, and provides a proper place for discussions,  which should not be mixed with GitHub "issues".  Just Google for "GitHub discussions" for documentation on how to enable this feature.

**Comment by sdatkinson** [comment]
Hi!

Strictly speaking, a database is out of scope for this repo, which is focused on the plugin itself.

However, something like some links to other projects (like if someone is building a website) is something that I might be open to including in the README of this repo (Think "projects using NAM"?). Make me a PR of something like that? Then other could PR their projects in as time goes on like @avanzzzi pointed out with the base16 schemes example.

**Comment by pelennor2170** [comment]
Chris, maintainer of the github model repository ( https://github.com/pelennor2170/NAM_models ) here.

So, the other background to this idea is that there are currently 3 different, "competing" NAM tone sharing type websites developed by folks in the NAM community, two operational, and one about to be very soon.

What I'd like to do is develop an integration within the NAM plugin to the github repository mentioned above.  I haven't fleshed out the details yet, but something simple along the lines of a button that pulls any changes (ie new models) from the repository on github to a local checkout, and defaulting the capture file dialog to that folder.  I'd be happy to (with your blessing, Steve) do that and submit a pull request.

The thinking behind this approach is that end users can upload their models to whichever of the tone sharing websites they choose (or more than one), and github can be refreshed with new models from them either manually by me, or via integrations with the websites.  And that way you also don't have to worry about how to handle it if multiple websites want their own integrations within the NAM plugin, or what if any of the websites discontinue etc.  This would be a website agnostic way of integration.

Very interested to hear your thoughts on this, @sdatkinson !

Thank you!

**Comment by pelennor2170** [comment]
> 

I'm not sure if Discord is any better for you, but if so, there's a NAM discord at https://discord.gg/6dbu36kPKH

**Comment by sdatkinson** [comment]
Closing this because [ToneHunt](https://tonehunt.org)  🙂
