### ISSUE TITLE
[BUG] Cakewalk DAW : Nam "gets stuck" when adding-bypassing audio effect in fx chain

### ISSUE THREAD

**Issue by powerslave7** [sdatkinson/NeuralAmpModelerPlugin#119]
Hey , i think i found a bug with the bandlab cakewalk DAW. (windows 10)
I am using nam 0.7 version, and latest cakewalk version. Also uninstalled and reinstalled both just to be sure. 

When you create a fx-chain , when you try to bypass-enable effects after nam modeler , the output meter of the nam plugin gets stuck and you can hear only the dry guitar sound with the effects you have on or off at that time. To get it fixed you need to restart Cakewalk daw.

This is an example. A DI track with a simple fx- chain. Pro Fab (eq) - NAM - Timeless 3 (delay)
![1](https://user-images.githubusercontent.com/127772512/224761339-3d8a86cf-1e36-467f-8a3a-7ab739ee66f5.jpg)

If you switch off- bypass timeless 3, the nam output meter gets stuck , while the di track is still playing. Re-enabling the delay justs adds the effect to the di track. Nam is still stuck and not working.

![3](https://user-images.githubusercontent.com/127772512/224760904-e6cba612-de00-4c0c-8c5f-10ac953dddc0.jpg)
![2](https://user-images.githubusercontent.com/127772512/224760900-65c5fd96-fceb-4449-b2f3-662bb0a5fd66.jpg)

**Comment by sdatkinson** [comment]
Thanks for the report!

Does this require there to be a plugin ahead of NAM?
Does it happen with other plugins than Timeless? Do you notice any patterns wrt mono/stereo ins/outs?

**Comment by powerslave7** [comment]
It happens with plugins that are before nam as well , I checked today this morning to be sure. 
I have tried various plugins from effects to modeling vsts , mono/stereo doesn't matter.

**Comment by James-F2** [comment]
This is exactly the same issue.
https://github.com/sdatkinson/NeuralAmpModelerPlugin/issues/102

**Comment by damiangr** [comment]
This : https://github.com/sdatkinson/NeuralAmpModelerPlugin/issues/102#issuecomment-1459643007  solved it for me in cakewalk

**Comment by sdatkinson** [comment]
Just downloaded Cakewalk to try this out.

I think we're currently fixed; see you in the next release!
