### ISSUE TITLE
Next / Prev Buttons for models and IR files [FEATURE]

### ISSUE THREAD

**Issue by teadrinker** [sdatkinson/NeuralAmpModelerPlugin#121]
Great work on this!
Would be great to have Next / Prev Buttons for models and IR files for faster browsing!

**Comment by kingyubba** [comment]
And / or a drop down that populates available files, similar to NDSP.

**Comment by sdatkinson** [comment]
Closing as duplicate: Model buttons is tracked in #63 and for IRs in #68.

Give ahead and those +1's so I can track the level of interest.

Thanks!
