### ISSUE TITLE
[BUG] Failed to load IR file. Message: Unsupported file format "IEEE float”

### ISSUE THREAD

**Issue by SaturosStudio** [sdatkinson/NeuralAmpModelerPlugin#123]
I make my impulses through a impulse creation program "MatcherCL", and such impulses are not loaded into NAM. All other impulse loading IR programs are working.
NAM: Failed to load IR file. Message: Unsupported file format "IEEE float”

 - Windows 10
 - Plugin version 0.7.0
 - VST3
 - DAW (Reaper)

![2023-03-15 204318](https://user-images.githubusercontent.com/127966900/225348262-78e1128d-44fb-4b01-be53-df0cbeb2d6b5.jpg)
[wav impulse.zip](https://github.com/sdatkinson/NeuralAmpModelerPlugin/files/10981241/wav.impulse.zip)

**Comment by sdatkinson** [comment]
We're tracking this in #84, so I'm going to close this as a duplicate.

My current plan is to have this in the next release :)

**Comment by SaturosStudio** [comment]
> We're tracking this in #84, so I'm going to close this as a duplicate.
> 
> My current plan is to have this in the next release :)

thank you for your work, I will be waiting. I didn't see it right away sorry
