### ISSUE TITLE
Please make "Select model" and "Select IR" text labels clickable, would improve GUI accessibility

### ISSUE THREAD

**Issue by ScottChesworth** [sdatkinson/NeuralAmpModelerPlugin#124]
Hi,

I'm a totally blind guitar player who uses open source screen reader software and DAW parameters to control plug-ins. Just been checking out NAM, and it's good that you've already got all adjustable controls exposed to DAW automation, but at the moment I'm not able to load models or IRs because the iPlug2 GUI isn't natively accessible at all.

Can you make the "Select model" and "Select IR" text labels clickable? Screen reader software can scan The GUI using optical character recognition, so if clicking those lines of text performed the same function as clicking the file icons), it would make it possible for screen reader users like me to get stuff loaded. OCR won't detect the file icons though, so right now there's nothin' doin'.

Thanks in advance for any improvements you can rustle up. Happy to clarify any questions of course.

Cheers,

Scott (London)

**Comment by sdatkinson** [comment]
Hi, Scott!

Great idea--I click the text pretty frequently myself!

Let me see what I can do.

**Comment by olilarkin** [comment]
Hi Scott, Making iPlug2's UI accessible is something we plan to do soon. We do support WebViews, which are potentially as accessible as any webpage and I might have a go at adapting the NAM UI to use a WebView for the whole UI

**Comment by ScottChesworth** [comment]
That's excellent news Oli! Gimme a shout any time you could use some hands-on testing with screen reader software. I'm familiar with all of the widely adopted options on Windows, Mac and iOS here. Have already gotten plenty of feedback actioned around JUCE, and the majority of REAPER accessibility improvements filter through me in one way or another. Just doing a few brags so you know the feedback would be legit. :)

**Comment by ScottChesworth** [comment]
In the meantime, it would be great if you do get a chance to rustle up a WebView UI for NAM. Other screen reader users have been asking me about it on Mastodon and in the REAPER accessibility spaces.

**Comment by olilarkin** [comment]
@mikeoliphant has made a LV2 port, which exposes the path as a LV2 port. Unfortunately, reaper doesn't support that kind of port/parameter, but if it did, I imagine that would be ideal for accessibility

**Comment by mikeoliphant** [comment]
Regarding path parameter support in Reaper, there is a feature request thread open:

https://forum.cockos.com/showthread.php?p=2505988

Feel free to pile on there to let the Reaper devs know that this is a desired feature.

**Comment by ScottChesworth** [comment]
Just bumped the thread. Do you know if there's been any response from Cockos anywhere? I can probably make sure Justin at least sees it if nobody's tried that already.

**Comment by mikeoliphant** [comment]
I haven't seen any response from them. Visibility is pretty hard there - the threads blow by at a pretty fast rate.

**Comment by ScottChesworth** [comment]
Gotcha. Will see if I can give it more of a nudge.

**Comment by sdatkinson** [comment]
Bumping priority because I'd personally love to see the whole fields be clickable & hope this helps the underlying issue.

**Comment by gabrielucido** [comment]
I have no idea of how I going to solve this, but currently working on it...

**Comment by sdatkinson** [comment]
@gabrielucido ah, sorry--this was resolved by #242.

**Comment by gabrielucido** [comment]
No problem, I will try to find another "good first issue" to work on

**Comment by mikeoliphant** [comment]
Yep - it is great that Reaper added LV2 path support. Hopefully it will get included in a release build soon.
