### ISSUE TITLE
Not recognizing VST3 in Reaper Mac IOS 10.13.6

### ISSUE THREAD

**Issue by Beau-Jason** [sdatkinson/NeuralAmpModelerPlugin#126]
Hello,

I am using a late 2011 MacBook Pro with iOS High Sierra 10.13.6. My DAW is REAPER 6.19. I have installed NAM version 0.7.0 (VST3 and AU) under (LIBRARY/AUDIO/PLUG-INS/VST3) as well as (LIBRARY/AUDIO/PLUG-INS/COMPONENTS) and it does not recognize the VST3 at all. However it does recognize the AU but is unable to load it. I have also tried to “Clear cache and scan fall all new plug-ins) in REAPER and still no luck.

[AU reaper message ](https://drive.google.com/file/d/1c1bDr9RubcW4gXOKCeF0cjgolRq32vaY/view?usp=drivesdk)

**Comment by sdatkinson** [comment]
macOS before 10.15 currently isn't supported.  I'll have to stop using some now-standard libraries to get it supported, tracked here: #23 

I do mean to get it fixed eventually since I've heard from a number of folks who would benefit from it.

**Comment by Beau-Jason** [comment]
Steve,

Thank you so much for the quick reply. Keep up the amazing work!

Beau


________________________________

**Comment by EchoReverbFilter** [comment]
> 

same situation , 10.14.  please tell me if it works someday! thanks
