### ISSUE TITLE
[BUG] Not able to extract the files from Installer.EXE

### ISSUE THREAD

**Issue by Yzrsah** [sdatkinson/NeuralAmpModelerPlugin#127]
**Describe the bug**

Hi, I am trying to figure out how to extract the DLL/VST3 from the Installer.exe.
I tried UniExtract and 7-Zip but none of them are able to extract the files from the Installer.exe
Usually these tools can extract the DLLs and other files from an installer but they are failing with the installer you used.
So how to get the DLLs and other files for this project?

I have free plugins from over 400 developers and they've all been extracted and they're all perfectly organized in one folder.

When there is a special case scenario and one of the developers forces me to use an installer it destroys the organization and I have to make a special folder with entries for "! WARNING, THESE ONES NEED INSTALLER.txt"

With over 4000 plugins in my setup, there is only about 10 things in the "! WARNING, THESE ONES NEED INSTALLER.txt" and I'm hoping the Neural Amp Modeler is not another one of those because it ruins the setup.

**Comment by sdatkinson** [comment]
Hmm. I have to admit that's not really a use case I'm keen to prioritize.

Can you workaround by running the installer and collecting the artifacts that were installed to your computer?

Alternatively, you can always build from source.

**Comment by Yzrsah** [comment]
@sdatkinson Yes of course I can do that but it is a total nightmare for a project where we download the installer every month and have to do that over and over. I would rather not use the project than have to deal with the installers. Please do not be one of the few projects that is forcing this on us.

**Comment by Yzrsah** [comment]
@sdatkinson If you are going to force the install on the user, at least use an installer method that can be extracted with 7-Zip by people like me. You're making no compromise of any kind and it's really negative and unfriendly and uncompassionate toward people like me.
