### ISSUE TITLE
[FEATURE] Several ideas that might help.

### ISSUE THREAD

**Issue by metalcabal** [sdatkinson/NeuralAmpModelerPlugin#130]
A few ideas here, so feel free to shoot them down if they aren't necessary or wouldn't be as useful as I initially considered, or if they are just outside of the intent/scope of what this software is intended to be for. 
Make it possible for the path where Amp's an IR's are pulled from to be default location, and when you click the Select button it automatically opens that folder path. 
I think a mute button for the Standalone version would be GREAT! I think it would also be good for the VST if you use it in Gig Performer or something like that also. 
A way to save an amp and IR as a preset and the ability to load a preset. This might be helpful for those who aren't always using it in a DAW. 
Maybe consider adding a broader eq that can be turned on or off - something like 10 bands or so. I think maybe it could be between the EQ dials and the gate and eq buttons that are there now. 
This is a long shot that may be completely out of bounds.....but. I think if this could allow for VST's to be loaded before and after the Amp and also after Cab, that it would pretty much replace 95% of the full guitar suites that are out there - I won't name names lol. 
If it means anything, these are all QoL type ideas that I'd be willing to donate cashola towards seeing come to fruition. 
Please also know that I didn't read all of the Feature requests there are here, so if any are dupes....sorry.

**Comment by Fannon** [comment]
- Regarding the presets idea - I'd like that. Especially if it could be expanded a bit:
- 
- * Allow NAM models to also come with inbuilt presets or make it simple that they can be installed along with them
- * Create some pre-defined tags / taxonomy for presets. Right now it's really hard to understand what you'll get from a NAM model (even things like whether they've been captured with cabinet or not). And if such categories / tags are not pre-defined, everyone will use them differently - making them less useful.

**Comment by metalcabal** [comment]
You explained that better than I would have thought to. I'm down for that idea being added.

**Comment by sdatkinson** [comment]
> * Create some pre-defined tags / taxonomy for presets. Right now it's really hard to understand what you'll get from a NAM model (even things like whether they've been captured with cabinet or not). And if such categories / tags are not pre-defined, everyone will use them differently - making them less useful.

This can be addressed once the model file defines a spot for metadata. This is coming in trainer version 0.5.1 and those models will be supported in plugin version 0.7.1 (I won't have this _functionality_ in 0.7.1--just that there's "space" for it to get built)

**Comment by sdatkinson** [comment]
BTW, it'd really help to have each individual ask in its own Issue instead of clumping things together like this. As is, it's hard to track each piece of this that you're asking for (I may not choose to do all of these, and I definitely won't do them all at the same time.)

**Comment by sdatkinson** [comment]
Coming back to this

> Make it possible for the path where Amp's an IR's are pulled from to be default location, and when you click the Select button it automatically opens that folder path.

I believe we're good on this now.

> I think a mute button for the Standalone version would be GREAT! I think it would also be good for the VST if you use it in Gig Performer or something like that also.

A workaround would be to move the gate up to zero. Not sure you can get anything through at that level :)

> A way to save an amp and IR as a preset and the ability to load a preset. This might be helpful for those who aren't always using it in a DAW.

I believe the first step toward this is being addressed in #326. I'm open to this being developed.

> Maybe consider adding a broader eq that can be turned on or off - something like 10 bands or so. I think maybe it could be between the EQ dials and the gate and eq buttons that are there now.

I don't think I'll be doing this in the context of this repo.

> This is a long shot that may be completely out of bounds.....but. I think if this could allow for VST's to be loaded before and after the Amp and also after Cab

Also probably going to be out of scope for me here I'm afraid.

---

Taking stock of it all, if I can find a preset feature request to attach this to, I think I can close this Issue and we can track that piece of this there...yes, let's say #252.

Ok, so I can close this.
