### ISSUE TITLE
[FEATURE] +/- 0.1 increments for Input/Output knobs please.

### ISSUE THREAD

**Issue by Airtrooper719** [sdatkinson/NeuralAmpModelerPlugin#132]
Can we have the ability to adjust the NAM input and output knobs in increments of +/-0.1? At the moment it jumps in increments of about +/-0.6 and is making it hard to fine tune things. Thanks.

**Comment by sdatkinson** [comment]
This has been fixed with updates to iPlug2 and should be available in v0.7.3
