### ISSUE TITLE
Logos and Skin the plugin with a graphic image [FEATURE]

### ISSUE THREAD

**Issue by petepodge** [sdatkinson/NeuralAmpModelerPlugin#133]
Love the plugin you've created Steve, amazing!

Im content with the current design being simple but if there is the possibility to skin the plugin with a graphic with out too much extra work then id be happy to assist you with some graphic design.

Ive attached an example but i'm happy to make what ever you would like. 
Things i'd need to know would be:
- pixel dimensions for the plugin graphic
- A theme - Ie, guitar amp mixed with neural network/tech look and colours/font style
- Maybe some images you would like to be incorporated. high res photos with royalty free licence

If you want logos designed then let me know:
- Style of font
- colours
- possible design parameters i.e. an image, shape, sub phase etc

If your keen let me know and id be happy to assist with the graphic design.
I'm sure there are others in the community that could collaborate too with graphic design, if you want us to get it up and running we could get a discord channel going. I know there is a crew doing web design already.
<img width="599" alt="NAM Skin" src="https://user-images.githubusercontent.com/128587615/226859161-49c76bd5-7b01-4c4e-9601-079578776a18.png">

**Comment by sdatkinson** [comment]
Thanks for the contribution! I'm moving forward with Evan Heritage's design for the next release but will keep you in mind for the future 🙂
