### ISSUE TITLE
cant find any presets - what is the default location for presets for Windows 64 bit [BUG]

### ISSUE THREAD

**Issue by patautrey** [sdatkinson/NeuralAmpModelerPlugin#136]
**Thanks for taking the time to write a bug report!** Use the following prompts to help you describe what's going on.  The more info you provide, the easier it'll be to understand how to fix it for you without having to come back and ask you questions.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS [e.g. Windows 10, macOS 10.15]
 - Plugin version [e.g. 0.6.1]
 - Standalone, VST3, or AU
 - DAW (if applicable)

**Additional context**

**Comment by sdatkinson** [comment]
The plugin does not come with any models. You have to either make them yourself or get them from someone/somewhere.

The models are files; once you have them saved on your computer, you can select them from the plugin or standalone by clicking the button and navigating to where you saved them.

**Comment by patautrey** [comment]
Is there a manual or instructions on how to make models? What type of
hardware/software is needed to make the model of an amp
