### ISSUE TITLE
[FEATURE] Logo and User Interface for NAM

### ISSUE THREAD

**Issue by flotasser** [sdatkinson/NeuralAmpModelerPlugin#139]
Hey guys, I've been thinking about a logo for NAM. Been posting it to Facebook and people resonated well with it so far, more than I could've hoped for to be honest.

**Logo**
The idea was "sound waves", "data highway" and combined they kinda looked like a tube. Another user also mentioned fingerprint, which I think is even more awesome and a cool coincidence. 

People seem to love the colored logo on the bottom left in this image:
![image](https://user-images.githubusercontent.com/80381745/227564040-5722d6f7-78ae-42cd-9a7d-a6eb53432ecd.png)
(colors are from the group header, just took them for inspiration)

And also I made this one:
![image](https://user-images.githubusercontent.com/80381745/227564585-138ced07-feb2-4095-a286-ada8f11330e2.png)

**User Interface of the Plugin**
Secondly, I can work on a GUI, graphically. I can model and render pretty much anything, just need to know which direction we're headed and more importantly - how I technically have to work, what exactly the deliverables are that I have to create. Is it a flat image in the background and some knobs as png images that are "in front" of the background image?

Also, would it be themed? So we could possibly create multiple UIs that can be easily switched? Everything in the same spot, but different colors, maybe interchangeable knobs, etc?

Cheers!

**Comment by Syberpathetic** [comment]
I like the logo design. It also resembles a tube

**Comment by GeistRodriguez** [comment]
it seems right now the images are within a .rsrc file so you cant really get in there to edit, so I dont know what the plan is to unlock that file and convert to a regular resource folder.  Im sure Steve will review soon, I posted a question about it as a feature request just now

**Comment by flotasser** [comment]
Ok sounds good. I looked through the iPlug2 repo and found that the GUI should be doable with vector and pixel graphics, so I think it all should work out. 
Best for me as a non-coder would be to have fixed sizes or aspect ratios to create the graphics and then deliver them all in SVG (for vectors) and PNG (or what format suits best for pixels) so only the files could be updated until it is all polished and the look is final.

**Comment by Gomez2178** [comment]
Sorry man.. i don't know where i found the 'skin themes' for the NAM .. some one can help me?  thx

**Comment by sdatkinson** [comment]
Thanks for the contribution! I'm moving forward with Evan Heritage's design for the next release but will keep you in mind for the future 🙂

It does also interest me to facilitate making changes to the skin for interested folks, so I'm still open to code changes that step closer to making that more approachable.

**Comment by flotasser** [comment]
Alright. It's a good choice to be honest. So, all good. :) You know how to reach me, I'm always glad to help with anything related to NAM.
