### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by sdatkinson** [sdatkinson/NeuralAmpModelerPlugin#14]
The code style in this repo is currently inconsistent, and it bugs me.

I'm looking for a common C++ code style that can be automatically enforced with a formatter to adopt and make things look a little cleaner. Suggestions welcome! :)

**Comment by masqutti** [comment]
In case you didn't know and I just found out that that using .editorconfig-file on the project folder lets you define code styling without the need for everyone to adjust their editors to match the project style. The file does have a wide support so is a way to go? More on https://editorconfig.org/

**Comment by sdatkinson** [comment]
Thanks for the suggestion. I looked it over, but I think I'm going to go with "`clang-format --style=llvm`" since it seems like one could easily blanket-apply it to the code base before PRing. I've added a [`format.bash`](https://github.com/sdatkinson/NeuralAmpModelerPlugin/blob/main/format.bash) that helps do this with a single command :)
