### ISSUE TITLE
[FEATURE] unlock .rsrc in the resource folder by making the resources available to edit

### ISSUE THREAD

**Issue by GeistRodriguez** [sdatkinson/NeuralAmpModelerPlugin#140]
your resource folder within the plugin contains a .rsrc file for what I assume are images for the plugin UI (on mac, not sure how it is for PC).  Any way to change the .rsrc file to an open resource folder for editing the UI?  Would be cool to be able to drop it into PS and edit the colors, and images.  It would be helpful for graphic designers to help create skins or add logos.

**Comment by sdatkinson** [comment]
Can you be more precise? Ctrl+F for ".rsrc" shows nothing under [NeuralAmpModeler/resources](https://github.com/sdatkinson/NeuralAmpModelerPlugin/tree/main/NeuralAmpModeler/resources).

Images used as resources by the plugin are stored under [NeuralAmpModeler/resources/img](https://github.com/sdatkinson/NeuralAmpModelerPlugin/tree/main/NeuralAmpModeler/resources/img).

**Comment by GeistRodriguez** [comment]
I thought the UI might have been laid out via images inside of the .rsrc

Is there a way to modify colors?

**Comment by olilarkin** [comment]
I think this can be closed. It may be possible to add a user skinnable UI in the future, but this wouldn't be the way to do it
