### ISSUE TITLE
[FEATURE] Stereo operation

### ISSUE THREAD

**Issue by axewav** [sdatkinson/NeuralAmpModelerPlugin#142]
Currently NAM can't be used to process stereo track.s 

Feature request: operate in stereo (dual mono), applying the same capture to both channels.

Optionally, allow separate captures for left and right channels. This would be necessary when a stereo device has been captured, such as "Studer A807 Tape Machine" by Joseph Chan.

**Comment by sdatkinson** [comment]
Dual mono is tracked in #108.

Mind updating this for specifically stereo models? That will require different work.

**Comment by sdatkinson** [comment]
In fact, I'm going to close for now. If you update the Issue as I asked, feel free to remove the duplicate tag and re-open at that point.
