### ISSUE TITLE
[FEATURE] Compilation Guide on Windows/Linux

### ISSUE THREAD

**Issue by dbanshee** [sdatkinson/NeuralAmpModelerPlugin#147]
Hello and thanks for de effort and great work.

A brief guide on how to configure/compile on Windows (and maybe Linux) would be helpful.

I find the project preconfigured for use under Mac (xcodebuild) and it is difficult for me to adapt it. Or maybe my approach is not correct and there is everything necessary in the project, but I am not able to understand it at the moment.

**Comment by dbanshee** [comment]
Thanks for the clarification.

It was my mistake trying to compile from Visual Studio Code. Opening the project from Visual Studio IDE has compiled perfectly.

**Comment by sdatkinson** [comment]
Great! Glad too hear it

**Comment by jahmed9** [comment]
Hi, I am unable to compile it on Windows 10 using Microsoft Visual Studio 2022 using the project file shared in one of the above messages. It fails to open the project file, giving error "The selected file is not a valid solution file"

<img width="237" alt="Image" src="https://github.com/user-attachments/assets/34ae2c1e-f935-4184-878f-4bdec3a7dd6f" />
