### ISSUE TITLE
eigen  cannot be cloned with --recursiv

### ISSUE THREAD

**Issue by damiangr** [sdatkinson/NeuralAmpModelerPlugin#15]
Hi, 
somehow eigen can not be clonned with git clone --recursiv

**Comment by sdatkinson** [comment]
Hi!

I saw the same problem. I know that `Notebook` was causing issues (#19). Since merging #20, it seems like it's working.

Want to give it another try and report back?  If it still doesn't work, would you mind sharing more info--what OS you're using and what version of `git`?

**Comment by sdatkinson** [comment]
Haven't heard back in a while so closing. Feel free to reopen and provide more info if this is still a problem

**Comment by damiangr** [comment]
It's ok now. Thanks!
