### ISSUE TITLE
[FEATURE] auto-level the main output loudness

### ISSUE THREAD

**Issue by ltgoes** [sdatkinson/NeuralAmpModelerPlugin#153]
Hi!

I tried using the standalon application and I am a bit frustrated the same way as when I got one IR pedal (cuvave). The problems on adjusting volumes of different patches.

I believe that in the future we will have AI engines that would adjust that and make possible the use of totally different presets in a smooth change between all of them.

For now, my suggestion would be an "auto level" in the main output of the standalone application, that would boost or decrease the volume to some sort of "ideal output level".

I am aware that this can be quite hard to make, but even if there's some way of avoiding a really loud preset take place when I'm testing all of the amazing ones available here, it would be great.

This is my first ever github interaction and I hope it can be useful. I really liked the project and I believe it will have a huge impact in the amp modeling systems.

**Comment by sdatkinson** [comment]
No, this is great--and something I've been meaning to do! (Could've sworn there was already an Issue, but I just checked and I don't see it?)

Version 0.5.1 of [neural-amp-modeler](https://github.com/sdatkinson/neural-amp-modeler) will define a new "metadata" part of the model file, which will include a "loudness" value. The intent is to use this value in the plugin to scale up or down the model's output and keep things consistent.

**Comment by sdatkinson** [comment]
...and done!

There are a few PRs in [NeuralAmpModelerCore](https://github.com/sdatkinson/NeuralAmpModelerCore) that I'd like to get sorted first as a courtesy to my collaborators, but this should be in the next release! 😄
