### ISSUE TITLE
[BUG]REAPER doesn't recognize the plugin or fails to load AU

### ISSUE THREAD

**Issue by alucast** [sdatkinson/NeuralAmpModelerPlugin#156]
After installing, REAPER doesn't recognize vst3 but does show AU, when trying to open it, it just doesn't load.

Mac Os Mojave 10.14
REAPER 6.78

This issue happened with this other plugin, I made a report and the developer fixed it briefly, I feel it's the same thing maybe with the same fix? Literally acted the same way so I kind of copy pasted the bug here kind of. 

https://github.com/vvvar/PeakEater/issues/73

**Comment by sdatkinson** [comment]
Mojave isn't currently supported--this Issue is being tracked in #23.

Keep an eye on that for when a fix gets in.

**Comment by EchoReverbFilter** [comment]
> 

i got same problem .Cant run NAM on my Mac 10.14,, i really dont wanna update to 10.15 ...cause i really wanna keept my Midas firewire Mixer  work.  If i update to 10.15.  my midas mixer wont recongnized on MAC.... i watch lot of video about  how Good is NAM on guitar, and i really wanna try it  on my  * Mac 10.14.6* can u make it happen? thanks alot
