### ISSUE TITLE
[FEATURE] Support Hardtanh activations in WaveNet models

### ISSUE THREAD

**Issue by sdatkinson** [sdatkinson/NeuralAmpModelerPlugin#158]
Support [Hardtanh](https://github.com/sdatkinson/NeuralAmpModelerCore/blob/2e5e1b2eabd110600af67b3af70ae97ad219812d/dsp/dsp.h#L156). Apparently this is just as accurate but much faster to compute.

Potential big win since the activations appear to be the heaviest part of the WaveNet.

**Comment by mikeoliphant** [comment]
We can probably close this, as it is now supported by the plugin.

Issue for supporting it in training is here: https://github.com/sdatkinson/neural-amp-modeler/issues/197
