### ISSUE TITLE
[FEATURE] Amp/IR/settings presets via shortcut (standalone mode)

### ISSUE THREAD

**Issue by wilsonjeff72** [sdatkinson/NeuralAmpModelerPlugin#169]
The following is regarding the standalone tool but could also be applied in some way to the plugin as well?

It's difficult to remember and recall all the combinations of profile and IR that we like for different purposes.

I imagine a folder with NAM shortcuts, each representing a "preset" launching NAM with preloaded amp, IR, control/dial settings (whatever is provided).  This will allow users a nice way to save "presets" to and more easily pull them up later.  

`nam.exe -amp="C:\NAMFiles\JetCity333.nam" -impulse="C:\Stuff\IRFiles\myimpulse.wav" -input=-2.0 -bass=5.3 -middle=-2.3`

Taking it one step further, there could be a button in the UI that will create such a shortcut for you, first prompting for a location and shortcut name.

You get the idea.  If one of the referenced files (amp or IR) no longer exists it could just leave them empty or pop-up a message.

**Comment by sdatkinson** [comment]
Let's collapse this up into #252 and track there.
