### ISSUE TITLE
[BUG] Mac installer requires Rosetta 2 emulation layer enabled on an Apple Silicon Mac

### ISSUE THREAD

**Issue by Enver-Yilmaz** [sdatkinson/NeuralAmpModelerPlugin#172]
**Describe the bug**
Mac Installer has Rosetta dependency.

**To Reproduce**
1. Start installer on an Apple silicon Mac with Rosetta emulation layer is NOT enabled. 
2. Installation fails with "You need to install Rosetta" dialog.

**Expected behavior**
Installer should work even Rosetta is not enabled on an Apple Silicon Mac

**Screenshots**
<img width="732" alt="Screenshot 2023-04-06 at 09 47 04" src="https://user-images.githubusercontent.com/7890684/230325012-25535008-08f1-47d2-be15-f4f31ea37a94.png">

**Desktop (please complete the following information):**
 - OS [macOS 13.3]
 - Plugin version [0.7.1]
 - Standalone
 - DAW (none)

**Additional context**
I extracted standalone app from the payload, drag it in the applications folder and it worked on my non rosetta MacBook. I guess rosetta dependency should be removed from installer.

**Comment by sdatkinson** [comment]
Sorry, I don't have a Mac with Apple Silicon, so I'm not really able to replicate this bug or understand what needs to be done to fix it. I'll add "Help wanted" in case someone else in the community can help with this before I buy a second Macbook for this project! ;)

For my education, what's so bad about Rosetta? It seems that other M1/M2 users are using NAM, by using it?

**Comment by Enver-Yilmaz** [comment]
There is nothing bad or wrong about rosetta, it is a temporary workaround from apple until everyone moves to the universal binary format. NAM itself is universal binary but the package manifest does not contains this information. This should be easy fix for someone knows where to look. Let me try to find out what is necessary to fix it.
