### ISSUE TITLE
[FEATURE] Add sample rate warning for non 48kHz

### ISSUE THREAD

**Issue by mikeoliphant** [sdatkinson/NeuralAmpModelerPlugin#182]
It might be helpful to have some sort of warning in the plugin UI if the plugin is operating at a sample rate that doesn't match the model. Not sure what, exactly - maybe a small, but highly visible (red?) indicator that shows an explanation popup when clicked?

Even if/when we get resampling implemented in the plugin, it would still probably be useful for the user to know it is happening.

**Comment by sdatkinson** [comment]
Agreed again :) Plan is to get the data sample rate into the model file first so that it's available over here for that reason (but one could safely assume 48k for models before that point since non-48k I _think_ still yells at you if you try!)

**Comment by mikeoliphant** [comment]
Yeah, we're going to have to assume 48k by default for all of the existing models out there anyway.

I think there are probably a bunch of people out there running the plugin at 44.1 and not knowing there is anything wrong. I did that myself initially.

**Comment by jan-kowalski** [comment]
But how will such a warning work when oversampling can be set in Reaper for any plug-in, such as NAM? Then the project in Reaper can have 44.1kHz sampling, but NAM itself will work in oversampling. Will then also such a warning appear?

**Comment by mikeoliphant** [comment]
> But how will such a warning work when oversampling can be set in Reaper for any plug-in,

It does not make sense to use Reaper oversampling with NAM - using a sample rate higher than that used to train the model will make things worse, not better.

In any case, if you *did* turn on oversampling in Reaper, then the plugin would see the oversampled sample rate. So if you were running at 48K, and enabled 2x oversampling, the plugin would see a 96k sample rate - and should complain (unless the model happened to be trained at 96k).

**Comment by sdatkinson** [comment]
Adding this to the checklist for next plugin version, though I'm hoping I can implement #59 instead, which will make this one obsolete 👍🏻
