### ISSUE TITLE
[FEATURE] Disable Normalization toggle when model has no loudness information

### ISSUE THREAD

**Issue by mikeoliphant** [sdatkinson/NeuralAmpModelerPlugin#183]
I think users may be confused that normalization isn't doing anything on models that do not have loudness metadata. Maybe disable the Normalization toggle if the current loaded model has no loudness value?

**Comment by sdatkinson** [comment]
You're absolutely right. In fact, it was so much on my mind to make this issue that when I saw it I thought that I had written it myself!

**Comment by sdatkinson** [comment]
Solved w/ #192
