### ISSUE TITLE
Win 7 x64 support? 

### ISSUE THREAD

**Issue by AndersonAOS** [sdatkinson/NeuralAmpModelerPlugin#184]
I'm not able to use with Windows 7 64bit + Reaper daw.

**Comment by Petervos2018** [comment]
Sorry, but Windows 7 isn't supported. https://github.com/sdatkinson/NeuralAmpModelerPlugin/issues/176#issuecomment-1501044887

**Comment by sdatkinson** [comment]
Currently, I'm not planning to support Windows 7 since iPlug2, the framework that this plugin is built on, doesn't support it.
