### ISSUE TITLE
[FEATURE] Sign and notarise the releases. 

### ISSUE THREAD

**Issue by colin-campbell** [sdatkinson/NeuralAmpModelerPlugin#185]
I would be happy to sponsor a year's Apple developer subscription for the author to sign releases and have Apple Notarise the DMG to lower the barrier for take-up amongst non-technical users on Apple.

**Comment by olilarkin** [comment]
FWIW @sdatkinson I am working on new CI scripts for the iPlug2OOS repo which will do all the signing etc in the cloud

**Comment by colin-campbell** [comment]
Github actions can do it excellently with the existing script, I should think, or alternatively, there is a specific action for it.

**Comment by colin-campbell** [comment]
I understand. If you not are actively working on it, I'm happy also to contribute code there. Or on the port to Cmake that I saw was being worked on, if it is still active.

**Comment by olilarkin** [comment]
oops duplicate -> #365 but this is really important

**Comment by sdatkinson** [comment]
Let's close this and continue w/ #365 to keep things deduped 👍🏻
