### ISSUE TITLE
MacBook Catalina dosdude Ableton live plug in crash

### ISSUE THREAD

**Issue by Charleychocolate** [sdatkinson/NeuralAmpModelerPlugin#186]
![7AF4CC42-7AA0-4057-B03F-A60A16578A68](https://user-images.githubusercontent.com/130464245/231440046-653b7c13-e1c7-4cb3-a3fc-cab6f1613790.jpeg)
![Uploading B2DEE58E-6B8E-494E-B05D-26D6E94ECE6E.jpeg…]()
Having an issue running standalone and vst both crash before opening.Not very good with my computer probably my error

**Comment by sdatkinson** [comment]
Closing because there have been a bunch of bug fixes on these. Re-open w/ more info if it's still a problem.
