### ISSUE TITLE
[FEATURE] Support compressed nam files

### ISSUE THREAD

**Issue by sprack** [sdatkinson/NeuralAmpModelerPlugin#193]
**Is your feature request related to a problem? Please describe.**
Current `nam` file sizes average around 400kb. Higher ESR files are commonly in the +1MB range. While not large it adds up in storage space and costs. For future scaling it would be great to standardize with a compressed format. zstandard compressed files averages 25% the original file size. 

**Describe the solution you'd like**
Support loading a compressed `nam` file using some format like zstd or lz4 using a filename extension of something like `namz`.

**Describe alternatives you've considered**
- binary format for the weights array field
- other compression formats: zip, 7zip, bzip2

**Additional context**
```
-rw-r--r--    1 user  staff     421555 Apr 14 17:25 VS8100 80s Metal.nam

-rw-r--r--    1 user  staff     117268 Apr 14 17:57 VS8100 80s Metal.7z
-rw-r--r--    1 user  staff     111166 Apr 14 17:57 VS8100 80s Metal.nam.bz2
-rw-r--r--    1 user  staff     133691 Apr 14 17:57 VS8100 80s Metal.nam.gz
-rw-r--r--    1 user  staff     170566 Apr 14 17:57 VS8100 80s Metal.nam.lz4
-rw-r--r--    1 user  staff     114492 Apr 14 17:57 VS8100 80s Metal.nam.zst
-rw-r--r--    1 user  staff     133936 Apr 14 17:57 VS8100 80s Metal.zip
```

1.4MB `ESR_0.0151` test file:
```
-rw-r--r--    1 user  staff    1489009 Apr 14 18:02 test.nam

-rw-r--r--    1 user  staff     406755 Apr 14 18:03 test.7z
-rw-r--r--    1 user  staff     391875 Apr 14 18:03 test.nam.bz2
-rw-r--r--    1 user  staff     470245 Apr 14 18:03 test.nam.gz
-rw-r--r--    1 user  staff     596699 Apr 14 18:03 test.nam.lz4
-rw-r--r--    1 user  staff     405608 Apr 14 18:03 test.nam.zst
-rw-r--r--    1 user  staff     470208 Apr 14 18:03 test.zip
```

**Comment by sdatkinson** [comment]
I don't think I'll be pursuing this in this repo. Even with 1000 NAM models, that's still less than half a gigabyte. At that scale, using file compression tools outside of NAM would probably be a reasonable first step.
