### ISSUE TITLE
[BUG]  (Win 10 ) Reaper closure after NAM 0.7.1 vST3 launch 

### ISSUE THREAD

**Issue by Chiudicasse** [sdatkinson/NeuralAmpModelerPlugin#194]
Good evening.
When I try to launch NAM 0.7.1, Reaper closes. 
Reaper Version:6.78 win 64. 
Windows 10 pro version.
Please help me

**Comment by sdatkinson** [comment]
Can you provide a crash log?

I have a fairly similar desktop to yours based on the info you've provided (Win10 pro, OS build 19045.2846; Reaper V6.79, 64-bit; NAM version 0.7.2) and can't replicate.  I need more info to get to the bottom of this.

**Comment by Chiudicasse** [comment]
Thanks for the answer. I solved updating the video card drives
