### ISSUE TITLE
[BUG] DAW crashes on startup with VST3 instance with a model loaded

### ISSUE THREAD

**Issue by sdatkinson** [sdatkinson/NeuralAmpModelerPlugin#199]
**Describe the bug**
Loading a project with an instance of NAM with a laoded model crashes the DAW.

The root cause is that `GetUI()` returns `NULL` because it's not fully instantiated when [the real-time loop tries to use it](https://github.com/sdatkinson/NeuralAmpModelerPlugin/blob/main/NeuralAmpModeler/NeuralAmpModeler.cpp#L649). (Is there a better place for this than the real-time loop? Feels inappropriate...)

Solution is to check that the needed objects are in a valid state and, if not, try again next time around (ouch).

**Comment by pawelKapl** [comment]
@sdatkinson Nice one! Sorry for that bug, but in my DAW (FL Studio), everything was OK, need to install Reaper too :/
