### ISSUE TITLE
[BUG] FL Studio crashes when opening Plugin on effect channel

### ISSUE THREAD

**Issue by Donarrr** [sdatkinson/NeuralAmpModelerPlugin#207]
If I try to open the plugin on an effect channel in FL Studio, the whole DAW crashes.

<img width="1440" alt="Bildschirm­foto 2023-04-18 um 10 51 00" src="https://user-images.githubusercontent.com/131148714/232725422-69c0e489-9500-4245-9f1b-184f3cf89c9e.png">

**Desktop (please complete the following information):**
 - mac OS Ventura 13.0
 - Plugin version 0.7.1
 - VST3
 - FL Studio

I normally installed the plugin with the provided .pkg file. As a stand-alone Plugin, it works.
It would be really nice if you guys could fix the bug, so that I can use that Plugin :)

**Comment by Presicion** [comment]
happens on windows too but whever i turn the plugin off or on after it loaded

**Comment by marcus-universe** [comment]
I had this crash also after having two of them in the effects chain where one is off and one is on. It also crashes when enabling it on and off. I used the version 0.7.2

**Comment by svioletg** [comment]
I wasn't having any issues before, but this has started happening to me on any project that had NAM loaded in it. Error doesn't occur until trying to click on it in the effects rack.

**Comment by sdatkinson** [comment]
Anyone want to chime in whether this still happens w/ 0.7.3?

@Nakedverse 

>  It loads fine and after 10-15 mins it Freezes Fl Studio 21.

may be due to #233, which was resolved and shipped in v0.7.3.

**Comment by sdatkinson** [comment]
Going to close then.

Feel free to open up if it's still a problem.
