### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Steveb1983** [sdatkinson/NeuralAmpModelerPlugin#208]
**Thanks for taking the time to write a bug report!** Use the following prompts to help you describe what's going on.  The more info you provide, the easier it'll be to understand how to fix it for you without having to come back and ask you questions.

**Describe the bug**
When using Nam in Calkwalk the amp becomes a clean tone when any plugins are added to the chain.

**To Reproduce**
1. Go to 'FX...'
2. Click on '.Nam..'
3. Scroll down to 'Your Amp and chosen Ir....'
4. Add another plugin into the signal chain.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS [e.g. Windows 10, macOS 10.15]
 - Plugin version [e.g. 0.6.1]
 - Standalone, VST3, or AU
 - DAW (if applicable)
Windows 10, Calkwalk

**Additional context**

**Comment by sdatkinson** [comment]
?

**Comment by Steveb1983** [comment]
Hi Steven :-)Did you receive my bug report about calkwalk?I've seen there's a new update which might hopefully solve the issue :-)Cheers SteveOn 19 Apr 2023 1:49 am, Steven Atkinson ***@***.***> wrote:
Closed #208 as completed.
