### ISSUE TITLE
[FEATURE] Library system

### ISSUE THREAD

**Issue by mertyyyy** [sdatkinson/NeuralAmpModelerPlugin#213]
It would be beneficial to implement a library system as soon as possible. As more people will contribute, it will become more problematic to implement "keywords" for a library system later on.

Captures can have "tags" (like; amp brand/model, drive character, lead/rhythm/clean...) for easy search. These tag.s can be implemented by the person who sampled the sound before release.

**Comment by sdatkinson** [comment]
This is somewhat solved by the inclusion of metadata into the training process.

However, setting up a "library" (you mean a website?) is out of scope and I'm not planning to take that on any time soon.
