### ISSUE TITLE
[BUG] Cubase 10 crash and standalone doesn’t work

### ISSUE THREAD

**Issue by DeLee79** [sdatkinson/NeuralAmpModelerPlugin#217]
Hi everybody, I installed NAM , the standalone version doesn’t run at all , (I click on the .exe file and nothing happens) and the vst version, on Cubase 10, appears in the vst list but when I click on it , cubase crashes. 🙁
Any ideas ? 
Windows 10 , interface SSL2+, Ryzen 7, 32 gb ram, ssd m.2 hd.
Thank you for your time !

**Comment by sdatkinson** [comment]
Is this still an issue with [the latest version](https://github.com/sdatkinson/NeuralAmpModelerPlugin/releases/tag/v0.7.3)?

I just grabbed a trial version of Cubase 12 Elements (alas, my Cubase Elements 7 copy seems too far out of date for me to get running stably on either my Mac or Windows machine) and wired it up on my Macbook.  Seems to be running fine.

Will check on Windows (assuming the trial lets me check both computers).

**Comment by DaniloMoran** [comment]
Yeah, still crashing in Version 0.7.3, but if i save my presets-bypassed- NAM doesn't crash

**Comment by sdatkinson** [comment]
Decent chance this will be fixed in 0.7.4 thanks to #298

**Comment by DaniloMoran** [comment]
Hey, I'm Testing the 0.7.4 and finnaly is Fixed, Thank you so much man!!!
