### ISSUE TITLE
[FEATURE] Nightly build or pre release testing channel

### ISSUE THREAD

**Issue by galczo5** [sdatkinson/NeuralAmpModelerPlugin#237]
Hi, is there any reason why there's no nightly build or even CI? 
I think that it would be great to have it for testing purposes. More people (mostly non-programming guitarists) would have a chance to contribute by testing pre-release versions and report critical bugs earlier. 

If you want I can try to figure it out and configure what's necessary.

**Comment by mikeoliphant** [comment]
This would be effectively solved by PR https://github.com/sdatkinson/NeuralAmpModelerPlugin/pull/238

**Comment by galczo5** [comment]
Nice! Thx

**Comment by galczo5** [comment]
I've just checked the results of your PR. It works.
I'm closing my issue
