### ISSUE TITLE
[BUG] Build macOS Failed

### ISSUE THREAD

**Issue by sdatkinson** [sdatkinson/NeuralAmpModelerPlugin#245]
https://github.com/sdatkinson/NeuralAmpModelerPlugin/actions/runs/4910825859/jobs/8768337306

<img width="1156" alt="image" src="https://user-images.githubusercontent.com/12240186/236725163-7d9270e3-7346-442e-a822-04eed6993a9e.png">

**Comment by mikeoliphant** [comment]
This looks like the culprit:

![nambuild](https://user-images.githubusercontent.com/6710799/236878395-33e862c1-3cdc-4275-bb03-91a785484429.png)

**Comment by sdatkinson** [comment]
D'oh!  Good catch @mikeoliphant 

Welp, that was a fun little puzzle to ponder over and a good opportunity to learn a little more about what I'm using...but glad for #248 😅
