### ISSUE TITLE
[FEATURE] Knob value entry

### ISSUE THREAD

**Issue by d-Vincent-b** [sdatkinson/NeuralAmpModelerPlugin#246]
It has been asked before, in someone's list of suggestions. This has been closed without too much explanation.

_-Clicking the values under the knobs lets us input values with the keyboard_
<s>_-Holding shift (or another modifier) lets us have finer control when using the mouse to turn knobs_</s> -> now working

**Steve's answer:** _I can check whether the iPlug2 framework supports these, but if not, then it's not something I'd be developing under this repo._

Is manual value entry possible in the iPlug2 framework, if so: can we have this in NAM?
If not i'll be in the iPlug repo bothering Oli :)

**Comment by olilarkin** [comment]
it's easy to enable manual entry, I made a PR #247

**Comment by sdatkinson** [comment]
> it's easy to enable manual entry, I made a PR #247

🙌🏻
