### ISSUE TITLE
[BUG] Output in 0.7.3 is MUCH hotter than in 0.7.2 (especially in Right Channel)

### ISSUE THREAD

**Issue by vvasilikos** [sdatkinson/NeuralAmpModelerPlugin#251]
The output level in 0.7.3 is MUCH hotter than in 0.7.2 especially on the right channel.

(In my situation, have not tried changing things around yet). Details on my particular setup at the end of this write-up.

**To Reproduce**
Simply load a previous project that was using 0.7.2 after upgrading to 0.7.3, the difference in levels should be noticeable immediately. See also screenshot below.

**Expected behavior**
I was expecting the output level to not be affected, I guess :) Even though the entire signal chain is actually mono, the right channel seems MUCH more affected than the left. See also screenshot.

**Screenshots**
![image](https://github.com/sdatkinson/NeuralAmpModelerPlugin/assets/133423485/236b5241-228a-4620-92f5-7e0eaacf5cdd)

**Desktop (please complete the following information):**
 - OS Windows 10 x86_64
 - Plugin version: 0.7.3
 - VST3
 - DAW: Reaper 6.79

**Additional context**
The FX Chain I was using:
- DI Track of guitar 48kHz 16bit wav recording
- ReaTune (as a tuner, does no processing, just used as a visual aid for tuning the guitar)
- **NAM Instance 1** (using the Xotic EP Booster profile named "GP EP Booster 100 Vintage.nam". Settings: Input 0.0 / Gate ON @ -80db, EQ ON with B/M/T  @ 5 (noon), Output 0.0, Normalize OFF, IR Loader OFF
- **NAM Instance 2** (using the JCM800 Zakk Wylde profile named "MARSHALL JCM800 ZW - HIGH SENSITIVITY - G3". Settings: Input 0.0, Gate OFF, EQ OFF, Output 3.8, Normalize OFF, IR Loader OFF
- Ignite NadIR
- ReEQ

Signal is already way too hot before NadIR and ReEQ.

**Initial attempts at isolating the issue**
- Even only 1 instance (not 2 chained as in the original setup) is still hotter in 0.7.3
- The output level setting is not the culprit, even if left at 0.0 the newer version is still a lot hotter.
- Removing the ReaTune, NadIR and ReEQ have no effect, they don't seem to influence the problem at all.

**Comment by vvasilikos** [comment]
Perhaps there is a channel division missing here:

https://github.com/sdatkinson/NeuralAmpModelerPlugin/blob/56a3a3228432cb9668af677c2bbc8f153ef0c7a1/NeuralAmpModeler/NeuralAmpModeler.cpp#L925

```c++
const double gain = pow(10.0, GetParam(kOutputLevel)->Value() / 20.0);
```

Should (maybe?) be:

```c++
#ifdef APP_API
  const double gain = pow(10.0, GetParam(kOutputLevel)->Value() / 20.0);
#else
  const double gain = pow(10.0, GetParam(kOutputLevel)->Value() / 20.0) / (float)nChansIn;
#endif
```

**Comment by sdatkinson** [comment]
I'll look into this.

@vvasilikos it shouldn't be in the output. The previous behavior was to apply the gain then copy to all of the connected output channels; this release doesn't change that.

**Comment by sdatkinson** [comment]
First test: an instance of the plugin with no models correctly outputs the same as its input.

Bypassed:

<img width="708" alt="image" src="https://github.com/sdatkinson/NeuralAmpModelerPlugin/assets/12240186/082c2abb-0211-4562-9df9-40c11188662c">

Active but no model loaded, no IR loaded, noise gate, EQ, and normalize disabled, input/output at 0:

<img width="706" alt="image" src="https://github.com/sdatkinson/NeuralAmpModelerPlugin/assets/12240186/c66f972e-6f11-40dd-bd0c-76939864629a">

Only plugin on the signal chain, input track is mono (first few seconds of [v1_1_1.wav](https://drive.google.com/file/d/1v2xFXeQ9W2Ks05XrqsMCs2viQcKPAwBk/view)).

**Comment by sdatkinson** [comment]
Test 2: Using [DR Pedal Platform]().

Installed v0.7.2 VST3 and rendered:
<img width="704" alt="image" src="https://github.com/sdatkinson/NeuralAmpModelerPlugin/assets/12240186/d05647d5-07d4-4ce3-8e0c-0250f79f1c12">

Installed v0.7.3 and:
<img width="704" alt="image" src="https://github.com/sdatkinson/NeuralAmpModelerPlugin/assets/12240186/3d12af08-4298-4104-8a11-0947295b3df4">

So, it's replicated.

Lemme pop these into Python and have a closer look

**Comment by sdatkinson** [comment]
Left channel appears to match
<img width="618" alt="image" src="https://github.com/sdatkinson/NeuralAmpModelerPlugin/assets/12240186/24475dcb-1d36-4e16-9963-cd65b3937af2">

But this is different from what you're seeing--visually, it looks like the left channel is different (not only where there's clipping).

**Comment by sdatkinson** [comment]
Inspecting with the debugger while playing the standalone, things seem correct: output is the same for both channels.

(Still running the DR pedal platform model)

<img width="867" alt="image" src="https://github.com/sdatkinson/NeuralAmpModelerPlugin/assets/12240186/6fefc495-5fdb-4110-968d-b856d5f78a0d">

Gotta say this is odd--I could've sworn I've spent a fair amount of time playing the plugin in a state that should have been functionally equivalent to what I'm looking at right now and never noticed this.

Unfortunately, I'm currently away from home until Sunday and don't have an interface nor even a pair of headphones, so I'm limited in what I can do. I'm going to put up a "help wanted" on this Issue and see if I can't get a hand from the community. 0.7.3 is a really exciting release and I'd love for folks to not have to downgrade in the meantime 💔

**Comment by sdatkinson** [comment]
Right channel, v0.7.3 seems exactly twice as loud (unless it clips obv)

Plotting around the first spike in v1_1_1.wav

<img width="591" alt="image" src="https://github.com/sdatkinson/NeuralAmpModelerPlugin/assets/12240186/60437799-97f2-4823-afba-b873573db1e3">

**Comment by sdatkinson** [comment]
Think I figured it out:

Can you check out the Plug-in pin connector?

I opened it up and found an extra conenctions from Output 1 to L:

<img width="233" alt="image" src="https://github.com/sdatkinson/NeuralAmpModelerPlugin/assets/12240186/bc41cab6-a685-4acc-be5a-71f3980a02ed">

Unchecking it like so...

<img width="236" alt="image" src="https://github.com/sdatkinson/NeuralAmpModelerPlugin/assets/12240186/679a9bb6-86af-4d80-b670-9361543b946f">

...results in something that nulls out perfectly as expected:

<img width="621" alt="image" src="https://github.com/sdatkinson/NeuralAmpModelerPlugin/assets/12240186/d50e2d55-a9ec-4a45-a98d-28e27ef63e29">

<img width="582" alt="image" src="https://github.com/sdatkinson/NeuralAmpModelerPlugin/assets/12240186/19b9a336-4d80-4931-80af-bb949cc14842">


Let me know if that's what happened for you too

**Comment by vvasilikos** [comment]
That seems to be it indeed!

That is so weird, I never messed with that configuration. Here's what it looks like if I have 0.7.2 loaded:

![image](https://github.com/sdatkinson/NeuralAmpModelerPlugin/assets/133423485/19ea46f6-af1f-40ce-903b-ad3d13282059)

It's already different than what I would expect to be the default and Reaper will put it back to normal if you hit Reset there. I wonder how this setting got this configuration...

This is what it looks like after upgrading to 0.7.3:

![image](https://github.com/sdatkinson/NeuralAmpModelerPlugin/assets/133423485/2510cce9-9675-4ea4-89f2-fc9560a0d051)

The problem I assume was because Reaper somehow tried to "upgrade" the previous config to Stereo, and this resulted in this clipping or something?

Anyway, I think it's fixed now, I just have to go back to the normal full mix projects and reset the Plugin Connector...
