### ISSUE TITLE
[FEATURE] Left And Right Navigation Arrows For Loading Files

### ISSUE THREAD

**Issue by ivanivkovic** [sdatkinson/NeuralAmpModelerPlugin#253]
**Is your feature request related to a problem? Please describe.**
Having to try and locate .nam and .wav files each time you need to change your sound is tedious. 

**Describe the solution you'd like**
Before an actual preset management system is created, it's enough to add "left" and "right" navigation buttons so the next file in the same (or next or previous) directory is loaded.

The left button is at the left of the file name. When the left button is pressed, the previous file in the directory is loaded.
The right button is at the right of the file name. When the right button is pressed, the next file in the directory is loaded.

Another possible solution is to enable drag and drop a file into the plugin.

**Describe alternatives you've considered**
There's no alternative solutions.

**Comment by Petervos2018** [comment]
I think they are working on it, see here : 

https://github.com/sdatkinson/NeuralAmpModelerPlugin/pull/242#issue-1698810970

**Comment by ivanivkovic** [comment]
> I think they are working on it, see here :
> 
> [#242 (comment)](https://github.com/sdatkinson/NeuralAmpModelerPlugin/pull/242#issue-1698810970)

Oh great, yes. I just saw the new version is released and didn't have that.
