### ISSUE TITLE
[BUG] NAM 0.7.3 is randomly crashing Logic Pro X when changing or saving new presets! 

### ISSUE THREAD

**Issue by jacobtryde** [sdatkinson/NeuralAmpModelerPlugin#259]
**Thanks for taking the time to write a bug report!** Use the following prompts to help you describe what's going on.  The more info you provide, the easier it'll be to understand how to fix it for you without having to come back and ask you questions.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS [e.g. Windows 10, macOS 10.15]
 - Plugin version [e.g. 0.6.1]
 - Standalone, VST3, or AU
 - DAW (if applicable)

**Additional context**

**Comment by jacobtryde** [comment]
Desktop (please complete the following information):

OS 12.6.1
Plugin version 0.7.3 AU
DAW LPX 10.7.7

LPX crashes randomly when saving to plugin preset folder or changing preset via left/right arrow in plugin og via library.

**Comment by sdatkinson** [comment]
> changing preset via left/right arrow in plugin

Can you show me what this means?

**Comment by sdatkinson** [comment]
If you could fill out the template and provide as much information as possible (+screenshots are really helpful), I'd love to get this in a state where someone who's got LPX (I don't have a copy) could replicate and then tackle the underlying issue.

**Comment by jacobtryde** [comment]
Hi Steven,

First of all, thank you for you fantastic work!!
And sorry for the slow response - It's quite busy here at the moment :-)

To Reproduce
Go to: The little orange "I" button under the channel fader in LPX to activate "input monitoring"
Click on: In the NAM plugin window, click left or right arrow to select LPX user preset - Logic crashes! (it seems to be OK with input monitoring off)

It's been happening when saving a user preset as well, but more randomly.

I've attache a little video clip and the auto generated crash report from OSX.

Hope this helps and let me know if you need me to test again.

All the best
Jacob :-)

[NAM Crash in LPX_1.pdf](https://github.com/sdatkinson/NeuralAmpModelerPlugin/files/11592898/NAM.Crash.in.LPX_1.pdf)

https://github.com/sdatkinson/NeuralAmpModelerPlugin/assets/133791710/f58b83b5-fe67-4b9d-b828-4f70363846d7

**Comment by sdatkinson** [comment]
I suspect this is resolved thanks to #298
