### ISSUE TITLE
Provide a DLL insted of a EXE installer [FEATURE]

### ISSUE THREAD

**Issue by michelvramos** [sdatkinson/NeuralAmpModelerPlugin#260]
Can you provide a DLL instead of a EXE installer? 

The thing is people are used to work  with VST plugins in a DLL format. However, when the plugin is a EXE installer people gets afraid of virus or unwanted changes in its OS environment.

Thanks!

**Comment by sdatkinson** [comment]
I'm sorry: no. An .exe installer is the way I'm choosing to provide the plugin.

If you'd like a .dll, you're welcome to build it from source.
