### ISSUE TITLE
[BUG] Problem opening Nam Standalone or in Reaper

### ISSUE THREAD

**Issue by andrealucard** [sdatkinson/NeuralAmpModelerPlugin#263]
I'm Brazilian, I'm sorry for the Portuguese from Google translate

When opening version 0.73 in Windows 11 pro - 10.0.22621 - the program in Standalone opens in a white window and closes automatically. When trying to open it in Reaper, a white window opens and even closes Reaper. I tried with versions 0.70, 0.71, 0.72, updated Windows, Visual C++, video drivers, I have a Fast Track Pro - Maudio, My Computer is a Phenom X6, 8gb of Ram, SSD. Motherboard Asus M4n68t-m-le. I'm an advanced Windows user, I've tried everything but the program won't open. I tried on the W10 that I have on another HD, and the error is exactly the same, it opens with a white screen for about 15 seconds and closes by itself. Thanks

Tried to open in compatibility mode W7, W8, run as administrator. unsuccessfully

**Comment by andrealucard** [comment]
Tried to open in compatibility mode W7, W8, run as administrator. Unsuccessfully

**Comment by segazh** [comment]
+1

**Comment by AlBj4Nam** [comment]
+1   I experience the same on win 10

**Comment by AlBj4Nam** [comment]
No luck in running NAM 0.74 vst3 or standalone in my win 10 install.

I've loaded NAM in latest Carla x64 vst host but when I've tried to open NAM GUI, Carla crashed.

I've tried to load NAM in VstHost 1.57 x64 and loading the .vst3 folder structure, does nothing.
But digging in the .vst3 folders and opening the .vst3 file inside with VstHost I've finally obtained an error dump that I carefully copy in next comment, for clarity

**Comment by AlBj4Nam** [comment]
Unhandled exception 0xC0000005 at 0000000000000000 writing to 0000000000000000

CS:RIP=33:0000000000000000 SS:RSP=2B:000000000014F1F8 RBP=0000000000000000
Flags=0000000000010246 MXCSR=0000000000001FA0
DS =000000000000002B ES =000000000000002B FS =0000000000000053 GS =000000000000002B
RAX=0000000000000000 RBX=00000000095583D0 RCX=00000000095583D0 RDX=0000000000000014
RSI=00000000095583D0 RDI=000000000AFBD8A0
R8 =00000000000000F8 R9 =00000000F95E8B78 R10=00000000F94C0000 R11=00000000F9590227
R12=0000000000000000 R13=0000000000000001 R14=0000000000000000 R15=0000000000000000
Stack Trace:
00007FFFF94FBACD (NeuralAmpModeler): ExitDll + 0x3356d
00007FFFF94FBCD7 (NeuralAmpModeler): ExitDll + 0x33777
00007FFFF9513A80 (NeuralAmpModeler): ExitDll + 0x4b520
00007FFFF94F88D3 (NeuralAmpModeler): ExitDll + 0x30373
00007FFFF9524BB2 (NeuralAmpModeler): ExitDll + 0x5c652
0000000140158C26 (vsthost): CVST3PlugIn::EditOpen + 0x76
000000014011B6D0 (vsthost): CSpecPlugIF::EditOpen + 0x20
00000001400E3EA4 (vsthost): CPluginFrame::OnEffEdit + 0x164
00000001401CCD40 (vsthost): _AfxDispatchCmdMsg + 0xc4
00000001401CCF80 (vsthost): CCmdTarget::OnCmdMsg + 0x180
00000001401EC651 (vsthost): CFrameWnd::OnCmdMsg + 0xd9
00000001400A50BC (vsthost): CMiniFrame::OnCmdMsg + 0x5c
00000001401C9D3C (vsthost): CWnd::OnCommand + 0xcc
00000001401EBFB9 (vsthost): CFrameWnd::OnCommand + 0xa1
00000001401CAF5F (vsthost): CWnd::OnWndMsg + 0x5f
00000001401C4724 (vsthost): CWnd::WindowProc + 0x38
00000001401C88D2 (vsthost): AfxCallWndProc + 0xfe
00000001401C898D (vsthost): AfxWndProc + 0x59
00007FF8233DE858 (USER32): CallWindowProcW + 0x3f8
00007FF8233DE299 (USER32): DispatchMessageW + 0x259
00000001401DBDEE (vsthost): AfxInternalPumpMessage + 0x52
00000001401DB8AB (vsthost): CWinThread::Run + 0x6f
000000014026F087 (vsthost): AfxWinMain + 0xab
000000014023B411 (vsthost): set_abort_behavior + 0x21d
00007FF822EB7034 (KERNEL32): BaseThreadInitThunk + 0x14
00007FF823EFCEC1 (ntdll): RtlUserThreadStart + 0x21

**Comment by AlBj4Nam** [comment]
Problem Solved! I suspected the error I was experiencing had something to do with the ui part of NAM. Installing the video drivers for the gpu solved the crashes; video drivers shipped with win 10 was the cause of crashes, NAM ui needed hardware accelerated graphics, in my case.

**Comment by sdatkinson** [comment]
Good to know. Thanks for checking back!
