### ISSUE TITLE
[FEATURE] Code cleanup.

### ISSUE THREAD

**Issue by olilarkin** [sdatkinson/NeuralAmpModelerPlugin#267]
I would like it if we could significantly clean up the plug-in code after #242 is merged.

Please can we

1. do something about the extremely badly named methods _GetNAM() and _GetIR() which actually "Stage" the new model/ir. It is very confusing to see methods named using the word Get, typically used for const Getter methods that do all sorts of sets!
2. rename "NAM" in variable names to "Model"
3. remove the use of this-> everywhere
4. remove the underscore prefix from private methods
5. use curly brackets for if/for loops even one-liners

**Comment by olilarkin** [comment]
After this is done it will be easier to think about removing unnecessary buffering and adding oversampling

**Comment by sdatkinson** [comment]
No preference here; happy to take a PR on it 🙂 (I'm aware of https://github.com/sdatkinson/NeuralAmpModelerPlugin/pull/268, but just working back through Issues now so noting for myself)

**Comment by olilarkin** [comment]
all apart from 4 are done i think, so closing!
