### ISSUE TITLE
Change colour of backlight for the dials based on the value

### ISSUE THREAD

**Issue by RustoMCSpit** [sdatkinson/NeuralAmpModelerPlugin#272]
Have it so the blue changes to a dark blue / purple at lower values but bright blue at higher values for each dial. This is solely a cosmetic request and isn't very important. Better yet, custom colours where people can pick which hex values they want.

**Comment by sdatkinson** [comment]
I'm aware of some forks of this repo that add such a control.

Personally, I'm not really keen to add it to the UI because it feels cluttered.

If you'd like to change the colors, you can find them in [Colors.h](https://github.com/sdatkinson/NeuralAmpModelerPlugin/blob/main/NeuralAmpModeler/Colors.h). Specifically, [Line 72](https://github.com/sdatkinson/NeuralAmpModelerPlugin/blob/e099f5d920ba60bb6110bf2199bfd1ac5e6fd926/NeuralAmpModeler/Colors.h#L72) defines the Azure color that NAM currently sports :)

**Comment by RustoMCSpit** [comment]
> Personally, I'm not really keen to add it to the UI because it feels cluttered.


if i made a pull request to show you what i mean would you consider it?

**Comment by sdatkinson** [comment]
Want to start with a mockup or a screencap or something?

One way I might like this is if we got a little "gear" icon where some of this deep settings stuff people want can be revealed...

**Comment by RustoMCSpit** [comment]
> One way I might like this is if we got a little "gear" icon where some of this deep settings stuff people want can be revealed...

That's what I was thinking, will look into it when I have the time. There is a formatting guide for the code right?

**Comment by olilarkin** [comment]
I have implemented the ability to change the highlight colour on #270

**Comment by MirrorProfiles** [comment]
I think it would be great if the colours were tied to the metadata - for instance, pedals get one colour, direct amps get another, full rigs get another etc. I think this can provide quick visual clues to what we are working with.

**Comment by olilarkin** [comment]
> I think it would be great if the colours were tied to the metadata - for instance, pedals get one colour, direct amps get another, full rigs get another etc. I think this can provide quick visual clues to what we are working with.

That might be something that individual users can set manually, but it wouldn't make sense to make that the default since people wouldn't remember what colour was what

**Comment by RustoMCSpit** [comment]
> I have implemented the ability to change the highlight colour on #270

Does this allow it to be changed based off the value?

**Comment by olilarkin** [comment]
No sorry, ignore that

**Comment by RustoMCSpit** [comment]
> No sorry, ignore that
 
If you're up for feature creep we can close this issue and you can take it on?

**Comment by olilarkin** [comment]
Someone else can make a PR for that if they want, but I don't think it's particularly important, and I prefer single colour anyway.

**Comment by sdatkinson** [comment]
Reading this again, I get that you're asking for it to react to the parameter _value_.

Sounds cool, but unfortunately "below the line" of what I'm personally keen to allocate bandwidth to working on.

**Comment by RustoMCSpit** [comment]
> Reading this again, I get that you're asking for it to react to the parameter _value_.
> 
> Sounds cool, but unfortunately "below the line" of what I'm personally keen to allocate bandwidth to working on.

bandwidth? would it slow NAMp down or do you mean youre too busy, I can look into working this in when im free
