### ISSUE TITLE
Guitar De-noise feature

### ISSUE THREAD

**Issue by RustoMCSpit** [sdatkinson/NeuralAmpModelerPlugin#274]
Use AI to achieve something like this: https://www.youtube.com/watch?v=ol0gJLdrIyM

**Comment by RustoMCSpit** [comment]
> (In the meantime) I recommend you try Bertom Audio's Denoiser - it's fantastic and does just as good a job if not better and it's free or pay what you want. https://bertomaudio.com/denoiser-classic.html

isnt this an equaliser type thing that applies noise gates to different bands? in the mean time sure, that could be cool but it's nothing compared to what i linked in the youtube video

**Comment by sdatkinson** [comment]
The scope of this repo is a plugin tha plays NAM models.

This sounds like a different technology from what NAM does?
