### ISSUE TITLE
Strat to Tele to Gibson, etc.. AI converter

### ISSUE THREAD

**Issue by RustoMCSpit** [sdatkinson/NeuralAmpModelerPlugin#275]
Not sure if this is feasible but a setting in which you can convert the sound of your strat for example to the sound of a tele using AI

**Comment by sdatkinson** [comment]
Not really in scope for this plugin repo 😅

**Comment by RustoMCSpit** [comment]
> Not really in scope for this plugin repo sweat_smile

Honestly fair, still cool idea
