### ISSUE TITLE
Ability to run two or more NAM models simutaneously to tonestack, also panning them would be cool

### ISSUE THREAD

**Issue by RustoMCSpit** [sdatkinson/NeuralAmpModelerPlugin#276]

**Comment by sdatkinson** [comment]
I'm going to be closing this because it's outside the scope of what this current repo is aiming to accomplish.

If you'd like to do this, I'd recommend using a host application to organize multiple plugins (e.g. multiple instances of NAM) as you'd like.

**Comment by RustoMCSpit** [comment]
> I'm going to be closing this because it's outside the scope of what this current repo is aiming to accomplish.
Hey Scott, while some of my other issues I get were unrealistic this one seems simple enough? Just add extra NAM and IR inputs? Is there something I'm missing cause this seems like a very natural feature?

**Comment by RustoMCSpit** [comment]
> I'm going to be closing this because it's outside the scope of what this current repo is aiming to accomplish.

Hey Scott, while some of my other issues I get were unrealistic this one seems simple enough? Just add extra NAM and IR inputs? Is there something I'm missing cause this seems like a very natural feature?
