### ISSUE TITLE
Ability to "chain" models

### ISSUE THREAD

**Issue by RustoMCSpit** [sdatkinson/NeuralAmpModelerPlugin#277]
Like how Amplitube 5 let's you make chains in the bottom of the photo: https://bedroomproducersblog.com/2020/10/29/amplitube-5-custom-shop/

**Comment by sdatkinson** [comment]
Closing this as out of scope similarly to https://github.com/sdatkinson/NeuralAmpModelerPlugin/issues/276

**Comment by RustoMCSpit** [comment]
> Closing this as out of scope similarly to #276

If the project got bigger (as in funding, time, etc.) would this be a natural progression of NAM or is this simply something you don't want NAM to be. I feel like this is the main thing holding NAM back. I have all Summer ahead of me and know Python, if you want I can try work with you to implement a built in signal chain to replicate Amplitube 5 (which was why having icons / art was so important beyond looking cool)
