### ISSUE TITLE
Allow for photos of the Amp type to be attached to the NAM file

### ISSUE THREAD

**Issue by RustoMCSpit** [sdatkinson/NeuralAmpModelerPlugin#278]
Or add a stylish cartoon drawing of the common type of Amps and display it on the app

**Comment by sdatkinson** [comment]
Changing the format of the .nam files falls under the scope of https://github.com/sdatkinson/neural-amp-modeler. I can see how it might be something nice to have in general (not just for the plugin).

As far as the plugin side of it, currently, I'm not really looking to do more work on the appearance of the plugin.

**Comment by RustoMCSpit** [comment]
Can I add this to the other repo then?
