### ISSUE TITLE
[BUG] 0.7.4 RC - "Last Directory" not working

### ISSUE THREAD

**Issue by James-F2** [sdatkinson/NeuralAmpModelerPlugin#290]
Testing the latest Artifact ([here](https://github.com/sdatkinson/NeuralAmpModelerPlugin/actions/runs/5238108041)) Windows 10, Cakewalk DAW.
Every time I click the folder button it opens the root (Desktop) destination, it doesn't remember the last opened folder destination.

PS.
I'm not sure how to properly report pre-release bugs.

**Comment by sdatkinson** [comment]
> I'm not sure how to properly report pre-release bugs.

If you let me know what commit you built from, that's perfect 🙂

So in this case I presume it'd be 3979a85?

**Comment by James-F2** [comment]
I did, it's linked after 'Artifact'.

**Comment by sdatkinson** [comment]
Behavior should be reverted to picking files with https://github.com/sdatkinson/NeuralAmpModelerPlugin/pull/297 and it seems to fix the Issue here.
