### ISSUE TITLE
[BUG] Nonexistent .nam file.

### ISSUE THREAD

**Issue by DocShadrach** [sdatkinson/NeuralAmpModelerPlugin#293]
I moved the folder that contained a .nam file that I have on a bass track and if I open NAM it still appears as if it has the profile loaded, but it obviously doesn't, because it's in another folder and it does not sound with the profile. Perhaps NAM should advise that that profile no longer exists in that location.

I'm using Reaper in Windows 7.

**Comment by sdatkinson** [comment]
> and if I open NAM it still appears

What do you mean by "open NAM"? Start the DAW and open a project with NAM instances, re-open the GUI after closing it, starting a new instance of NAM (which shouldn't have _any_ models or IRs loaded...?)

I need more details to understand.

**Comment by DocShadrach** [comment]
I mean start the DAW and open a project with NAM instance, and a (now) nonexistent file is still in the plugin without any notice that the file no longer exists in that location.
