### ISSUE TITLE
[FEATURE] Support for automatically adjusting input level control to an internal reference level metadata value

### ISSUE THREAD

**Issue by MirrorProfiles** [sdatkinson/NeuralAmpModelerPlugin#294]
**Is your feature request related to a problem? Please describe.**
Currently users are creating models with totally different converters and reamp boxes, as well as different input chains. All can provide a wide variety of input and output levels - some people record DI's hotter and reamp quieter, some record DI's with more headroom and have a louder reamp signal. In all cases, the levels are accurately matched to the real amp BUT ONLY for their own specific rig. When someone else uses the model, its likely their input signal will be different and they need to adjust to compensate. This usually involves guessing unless the creator has specified the analog level of their reamp chain (usually in the file name or ToneHunt description. The user then has to calculate the difference between their input headroom and the one the model was created for, and adjust the input level accordingly. 

**Describe the solution you'd like**
It would be great to have a preferences page, where the user can set a value of their maximum input level (i.e. headroom they are recording with). This typically varies between -3dBu and 19dBu, with most instrument inputs using around 12-14dBu. If a user has selected their own input headroom, and the .nam model has metadata with the headroom the model was created for, the plugin could automatically adjust the input dial, so 0 becomes the intended gain level, and the user can adjust to taste from there (with the ability to return to the starting point, as captured).

**Describe alternatives you've considered**
Described above - currently involves asking the creator and hoping they are able to determine the correct level, and then adjusting manually for each model (if using models created by different people then it means an adjustment is needed every time (if accuracy is desired).

**Additional context**

**Comment by dglava** [comment]
This would be huge. I don't think any other amp sim offers something like this. Some don't even publish their exact, optimal input levels. I hope this gets implemented in the plug-in and that providing such a value becomes mandatory for new captures.

**Comment by sdatkinson** [comment]
This will be coming soon (probably in the next version).

I've merged in the needed code on the trainer side: https://github.com/sdatkinson/neural-amp-modeler/pull/477

**Comment by sdatkinson** [comment]
Note to self: make it a text box instead of a knob.
