### ISSUE TITLE
[FEATURE] Package the plugin without the installer (Windows)

### ISSUE THREAD

**Issue by reaper-sid** [sdatkinson/NeuralAmpModelerPlugin#302]
On Windows, the installer complains that the app is unknown and potentially dangerous.

Why not package a version that is just a ZIP file with a VST inside without the installer. Many bigger companies offer that option,
And it could not be harder than packaging up an installer. It is 2023 we know what to do with a VST file. We don't need the handholding of an installer.

**Comment by AlBj4Nam** [comment]
+1 for .zip file

**Comment by sdatkinson** [comment]
As I said in #127, I'm not planning on doing this.

If you need any of the individual artifacts, you're welcome to build from source.

**Comment by sdatkinson** [comment]
To solve the issue of Windows complaining, the plan is to sign the releases; see #185.
