### ISSUE TITLE
[FEATURE] More dynamic range

### ISSUE THREAD

**Issue by hubertoWeb** [sdatkinson/NeuralAmpModelerPlugin#304]
**Thanks for taking the time to write a feature request!**

Hi, 
first: thanks for your great NAM, its sounds very nice!!! And this with a smaller team and money like the big players!!! :)

**Is your feature request related to a problem? Please describe.**
What is missing at the moment is the dynamic in playing, it feels like there are 5 possible dynamic ranges, it feels very compressed. on high gain metal riffs no problem, but in the blusey area I miss it

But with this feature, I don't have the feeling that I need something else in my DAW or Mac

**Describe the solution you'd like**
more dynamic feeling

**Describe alternatives you've considered**
Tonex
Amplitube 5
Line6 Pod go

the all have more dynamic ranges

**Additional context**

**Comment by hubertoWeb** [comment]
Is it maybe possible to train the neural engine with more dynamic files?

**Comment by sdatkinson** [comment]
> Is it maybe possible to train the neural engine with more dynamic files?

Yep! Go ahead and insert examples of whatever you think it's not getting right. Just make sure it's not anywhere where there are special pieces to the training file (at the beginning/end). If you insert it at the 1-minute mark, you'll be fine :)

That said, I'm surprised you find TONEX more dynamic. [My test](https://youtu.be/nBS2JlCypQ8) found NAM was more true to the dynamics in an _extremely_-dynamic model (Deluxe Reverb on 10)--and it makes sense that it would--TONEX doesn't provide any low-volume examples to learn the behavior of the amp when reacting to playing with the volume rolled back/picking lightly, and it shows--the TONEX model was louder and more distorted at low volumes, and quieter/cleaner at high volumes, than the real thing.

If you could provide an example where there's a systematic difference between the amp and its NAM model, that'd help try to troubleshoot. But from what I've seen myself, the more likely explanation is that it's the amp it's modeling that isn't very dynamic. 

The best way to do this would be by providing the following 4 files:
* The reamp of of v2_0_0.wav of the amp being modeled
* (Optional) the model you trained from it. (I can always run the trainer on output file myself, but it might help to get the exact model you got).
* An example input DI that demonstrates NAM not behaving dynamically as expected.
* The output of the amp to that DI to demonstrate how it _should_ react instead.

Feel free to re-open this issue if you can provide those for me and we can dig in from there.
