### ISSUE TITLE
[BUG] Touch screen does not work on 0.7.4

### ISSUE THREAD

**Issue by golentones** [sdatkinson/NeuralAmpModelerPlugin#308]
Nothing responds to touch on touchscreen laptop.  Using Windows 10.  True for both standalone and VST3.

**Comment by sdatkinson** [comment]
Can you give me some concrete examples of things that aren't working? "Nothing" leaves too much for me to guess.

e.g.:
* Do the knobs work?
* Do the "open file" icons open the file browser? Does the text populate after picking one
* etc.

A step-by step demo of what's going on would be really helpful.

**Comment by golentones** [comment]
I would be more specific, but I literally mean nothing.  Not the knobs, not the open file or open IR buttons, none of the switches for gate or EQ.... nothing responds to touch.  I'm not sure what I can say for step by step demo.  I simply open either the VST3 plugin or the standalone on my touchscreen and nothing responds to the touch.

**Comment by sdatkinson** [comment]
Hmm. Just realized I've got a Windows laptop with a touchscreen kicking around that I might be able to try and replicate this with.

Going to add it to the short list and see what I can do.

Just to confirm, it used to work on 0.7.3? If so, that helps me narrow down what might have happened.

**Comment by sdatkinson** [comment]
@olilarkin that appears to be it!

Will PR this in presently 😄
