### ISSUE TITLE
Version v0.7.4 does not recognize Ableton Live 11.3.2

### ISSUE THREAD

**Issue by sloopy2nd** [sdatkinson/NeuralAmpModelerPlugin#324]
After installing version v0.7.4 ableton does not recognize the vst ....the path created is C:\Program Files\Common Files\VST3\NeuralAmpModeler.vst3\Contents\x86_64-win , I tried to copy the file "NeuralAmpModeler. vst3" to the path "C:\Program Files\Common Files\VST3\NeuralAmpModeler.vst3" and still not recognized by Ableton Live 11.3.2

DAW Ableton Live 11.3.2
Operating System Windows 11 22H2 Build 22621.1848

**Comment by fab672000** [comment]
Confirming latest version works fine with 0.7.4, you may have to rescan plugins in the preferences/Plug-Ins tab in Live.
Suggesting to close that bug.

**Comment by sdatkinson** [comment]
Sounds good. OP feel free to re-open with more info if you're not set
