### ISSUE TITLE
Improve get_dsp method

### ISSUE THREAD

**Issue by masqutti** [sdatkinson/NeuralAmpModelerPlugin#33]
#32 As it's a crucial method for interfacing this repo with other projects, I'd like to suggest modifications for get_dsp method. On the pull request there's a vague idea of what I'm after.

It might be a good idea to make the get_dsp-method's steps usable independently, at minimum allowing the loading of a dsp from a JSON-file (from a disk) and also allowing the loading of a dsp from memory. This would also require returning such data structure upon loading that can be saved and maybe even manipulated and to be loaded again with the get_dsp-method making the whole plugin repo more versatile.

To reduce amount of double-coding anything, if it's possible to split the get_dsp into sub-methods that also work independently but might use each other, it'd be efficient.

This pull request is a one way to achieve the result. Others ways could include not mixing up returning the data during the loading as a reference, but do a separate getter method for the dsp data and/or maybe include other small helper functions as well instead of defining a data struct but just returning the data with getters..

**Comment by masqutti** [comment]
#32 The mentioned issues are fixed on the PR

**Comment by masqutti** [comment]
Now that I look a bit more I think it is probably unnecessary to split the architecture, version and config info separately from the JSON and instead the struct could include just the json and parameters vector? I think I just made that split based on intuition of what is happening inside the get_dsp, and ALSO because I haven't worked much with JSON's so my stand point is iffy!

**Comment by sdatkinson** [comment]
Thanks for explaining the rationale a little more.  Having read through it, I think that I'm personally not too opinionated on this point, but happy to oblige.

> it is probably unnecessary to split the architecture, version and config info separately from the JSON and instead the struct could include just the json and parameters vector

Actually, I do appreciate the explicit listing of those attributes. Not really a huge issue for this repo since it's tiny, but typically I try to avoid relying too much on data structures that can hold who-knows-what inside--gets confusing after a while! :)

Resolved by #32 ; thanks!

**Comment by sdatkinson** [comment]
Causes #40
