### ISSUE TITLE
[BUG] Wrong messsage tag appears used for IR file browser control

### ISSUE THREAD

**Issue by sdatkinson** [sdatkinson/NeuralAmpModelerPlugin#330]
The IR file browser control is instantiated with `kMsgTagClearModel` as its `mClearMsgTag`:
https://github.com/sdatkinson/NeuralAmpModelerPlugin/blob/cb0132011598d5597fc56fd7218795bfc725bbc9/NeuralAmpModeler/NeuralAmpModeler.cpp#L204C26-L204C26

Instead, it should be `kMsgTagClearIR`:
https://github.com/sdatkinson/NeuralAmpModelerPlugin/blob/cb0132011598d5597fc56fd7218795bfc725bbc9/NeuralAmpModeler/NeuralAmpModeler.cpp#L431C10-L431C24

**Comment by olilarkin** [comment]
yep, well spotted!
