### ISSUE TITLE
anti aliasing

### ISSUE THREAD

**Issue by Percepton** [sdatkinson/NeuralAmpModelerPlugin#332]
Add oversampling to reduce aliasing or train a specific model to produce pure aliasing noise from orginal model and run in real time as a noise canceling destructive model to remove aliasing artefacts

**Comment by RustoMCSpit** [comment]
very descriptive title

**Comment by sdatkinson** [comment]
The models that NAM runs aren't made in a way that allows you to oversample them in the same way you can a normal gray-box simulation model.

The other part I'm not sure what to do with concretely, so I'm going to close this.
