### ISSUE TITLE
Reopening: cakewalk still crashes when loading NAM into Fx [BUG]

### ISSUE THREAD

**Issue by sjm2021** [sdatkinson/NeuralAmpModelerPlugin#334]
Still having issues with Cakewalk crashing when trying to load NAM 0.7.4  Tried rebuilding PC, tried contacting Bandlab, they will not be releasing any updates as they will release the pay for Cakewalk Sonar. Any ideas or suggestions would be appreciated. Thanks in advance

**Comment by sjm2021** [comment]
The first zip file contains the stand alone dmp file. The second zip file contains the dmp from Cakewalk while loading NAM into Fx
Thanks for any help.

Zip file 1: [NeuralAmpModeler_x64.exe.5080.zip](https://github.com/sdatkinson/NeuralAmpModelerPlugin/files/12045805/NeuralAmpModeler_x64.exe.5080.zip)


Zip file 2: [Cakewalk.exe.8752.zip](https://github.com/sdatkinson/NeuralAmpModelerPlugin/files/12045852/Cakewalk.exe.8752.zip)

**Comment by sdatkinson** [comment]
Let's continue this on #269
