### ISSUE TITLE
Forced Sample Rate [BUG]

### ISSUE THREAD

**Issue by Zappafile** [sdatkinson/NeuralAmpModelerPlugin#344]
**Thanks for taking the time to write a bug report!** Use the following prompts to help you describe what's going on.  The more info you provide, the easier it'll be to understand how to fix it for you without having to come back and ask you questions.

**Describe the bug**
I am running Win 11 and an Audient iD44 mki. When I open NAM it forces my ID44 to run at 96khz. If I open preferences in NAM and set back to 48khz NAM freezes and is unuseable. I can quit NAM and set the iD to 48k and run NAM once more but it again will force back to 96khz starting the cycle once more.

**To Reproduce**
1: Run NAM
2: warning on NAM appears "NAM is meant to be run at 48khz"
3: open Settings and set NAM to 48khz and as soon as i hit apply the program freezes.
4: rinse and repeat

**Desktop (please complete the following information):**
 - OS [e.g. Windows 11
 - Plugin version [e.g. 0.7.5]
 - Standalone

**Comment by sdatkinson** [comment]
Is this the standalone?

Is your interface's sample rate set to 48k before opening the app?

I would also assume that you need to open a model before step 2 to get the warning to appear? It shouldn't display any warnings about sample rate if there is no model loaded up.

**Comment by Zappafile** [comment]
This is in standalone. I have my interface set to 48k as standard but as soon as I load a model it gives the warning. However, the app is opening in 96 and forcing my interface to change accordingly. I can’t change the interface or the app without it freezing. Hope that helps. TimSent from my iPhoneOn 19/07/2023, at 02:26, Steven Atkinson ***@***.***> wrote:﻿
Is this the standalone?
Is your interface's sample rate set to 48k before opening the app?
I would also assume that you need to open a model before step 2 to get the warning to appear? It shouldn't display any warnings about sample rate if there is no model loaded up.

**Comment by sdatkinson** [comment]
One other quick question: I see you're using the release candidate for 0.7.5? Is this specific to this version, or does the same issue happen with version 0.7.4?

**Comment by Zappafile** [comment]
No this is new behaviour. Unique to 0.7.5 TimSent from my iPhoneOn 21/07/2023, at 05:50, Steven Atkinson ***@***.***> wrote:﻿
One other quick question: I see you're using the release candidate for 0.7.5? Is this specific to this version, or does the same issue happen with version 0.7.4?

**Comment by Zappafile** [comment]
Hi Steve, Not sure what to tell you but I opened it today to try and replicate the issue and get a crash report etc and it is now working fine. Honestly, I tried everything the first time around and absolutely nothing worked yet today it is up and running first try. It still defaults to 96k but I switched via the control panel in Nam and it worked fine. I will monitor this for the next little while and see if it comes back but for now it is not an issue.  For reference the interface is an Audient id44mki Thanks for following up again Steve. Fingers crossed it was just a glitch in the matrix Tim Sent from Mail for Windows From: Steven AtkinsonSent: Wednesday, 26 July 2023 3:31 AMTo: sdatkinson/NeuralAmpModelerPluginCc: Zappafile; AuthorSubject: Re: [sdatkinson/NeuralAmpModelerPlugin] Forced Sample Rate [BUG] (Issue #344) Sorry, just catching up with this. A few questions I need the answers to in order to understand what's going on.Is there a crash report that you can share? A straight copy-paste of everything you get would be great, or if you could attach it as a text file.[Less important but would still be helpful] Does this happen in the non-standalone versions (VST3, AU)?[Also not sure it's important but] what interface are you using?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by sdatkinson** [comment]
Thanks for following up. I'm going to close this for now; feel free to come back and re-open if it happens again and you're able to get more info 🙂
