### ISSUE TITLE
[BUG]Problem in Logic pro x on ventura 13.0.1

### ISSUE THREAD

**Issue by dhokray** [sdatkinson/NeuralAmpModelerPlugin#348]
I installed the latest version of the plugin 0.7.4 correctly
My OS is Ventura 13.0.1
Logic pro version 10.7.5
I loaded the plugin and clicked on "select model" and selected a model i downloaded from tonehunt.org but nothing loaded
I loaded the plugin and clicked on "select ir" and selected a ir from a folder but nothing loaded
the plugin still says "select model" and select ir" I mean nothing is loaded there still
i tried the standalone mode it worked there but not in plugin
please kindly help
thank you

**Comment by sdatkinson** [comment]
What is the full file path to the model/IR on your computer that you tried to use?

**Comment by dhokray** [comment]
it is in my downloads folder on my mac
so it might be like this :
Downloads->1 NAM Profiles->5152 Clean ish.nam

actually i tried many others as well. the above one is just one example of
what i tried loading.
i tried loading lots and lots of models and IRs also from different
locations and also some very very old IRs that i had from many years old.
but basically none of the models or IRs is loading in that plugin in logic
pro. but the same ones load in standalone mode.

**Comment by olilarkin** [comment]
This is likely to be a sandboxing issue. Try putting your models somewhere in ~/Music/ and see if you can access them via the plug-in UI there.

**Comment by dhokray** [comment]
i will try and get to asap
thanks for your kind reply
i am a small producer from Nepal eagerly & enthusiastically trying your
amazing plugin
cheers

**Comment by sdatkinson** [comment]
@dhokray

> Downloads->1 NAM Profiles->5152 Clean ish.nam

Can you give the _exact_, _full_ path? It matters here. I believe you may be seeing #306.

If that's the case, this would be solved by updating to the latest version, released yesterday.

**Comment by dhokray** [comment]
It worked!! I put the IRs and profiles in music folder. Trying to open from the download folder still didn't work with the new updated 0.7.5. But that's ok since it is working from music folder now.
Thanks. Much appreciated. Best wishes for more and more success of this company/ plugin.
Namaste from Nepal. 🇳🇵

**Comment by sdatkinson** [comment]
> thanks! so this is kind of a duplicate of #254

Hard to tell, but perhaps. Going to close this since the Issue here is resolved, though it bothers me to not be sure (and it's not clear to me why it was a problem here and _not_ for most other folks).

**Comment by dhokray** [comment]
Don't know what happened in my system. I haven't tried from other locations
to open the profiles or IRs. I tried with download folder which didn't work
and later tried with music folder which worked. But the good news is it is
working.
Thanks.
