### ISSUE TITLE
NAM makes Reaper crash when trying to open Fx for a guitar.[BUG]

### ISSUE THREAD

**Issue by Khan0888** [sdatkinson/NeuralAmpModelerPlugin#350]
**Thanks for taking the time to write a bug report!** Use the following prompts to help you describe what's going on.  The more info you provide, the easier it'll be to understand how to fix it for you without having to come back and ask you questions.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS [e.g. Windows 10, macOS 10.15]
 - Plugin version [e.g. 0.6.1]
 - Standalone, VST3, or AU
 - DAW (if applicable)

**Additional context**

**Comment by Khan0888** [comment]
Hi All, I am just a musician and I can no longer use Nam on my new laptop.
 NAM makes Reaper crash when trying to open Fx for a guitar.
Other plugins work fine  except for 1
If anyone can help thanks a lot and remenber I am no developper.
Thanks

**Comment by sdatkinson** [comment]
Can you please post the crash log and try to answer the rest of the questions?

**Comment by Khan0888** [comment]
Hi Steven,

I attach a screenshot of the Event log: Error
[Screenshot Event viewer.pdf](https://github.com/sdatkinson/NeuralAmpModelerPlugin/files/12197592/Screenshot.Event.viewer.pdf)
OS: Windows 10 Pro
Plugin version v0.7.5win
VST3

When I open Reaper 
Go to a project
Add Fx to guitar track
Click Nam then after a few seconds Reaper shut down

Hope this is enough for you to understand. My old laptop, Nam is working perfectly with Windows 10

Thanks a lot Steven for your great job

Regards,
Khaïr

**Comment by Khan0888** [comment]
Problem solved 
GPU updated

**Comment by Khan0888** [comment]
Thanks
