### ISSUE TITLE
[BUG] IR sample rate incorrect 

### ISSUE THREAD

**Issue by Rcabbott408** [sdatkinson/NeuralAmpModelerPlugin#351]
**To Reproduce**
1. Open NAM
2. Load an IR (no model)
3. Listen, and then change project sample rate
4. The sound of the IR will change.

**Expected behavior**
If you playback a track with an IR in NAM and no model, and then compare it to another IR loader with the same IR, it will sound different. If you change the project sample rate, the IR inside NAM will have a tonal shift.

 -  macOS 11.6.8
 - Plugin version [0.7.4]
 - VST3,
 - Reaper

**Comment by Rcabbott408** [comment]
Here is a link to the IR used : (https://drive.google.com/open?id=1XttXjJQwrkJk0xQCg-CwH5JPjcFr-EOr&usp=drive_fs)

**Comment by sdatkinson** [comment]
Thanks for the bug report, and thanks for the steps to reproduce. I bet I know exactly what the problem is--when teh sample rate is changed, I need to tell the IR loader to resample the IR in the new sample rate.

Having a look

**Comment by Rcabbott408** [comment]
Thank you I appreciate it. NAM is amazing!
