### ISSUE TITLE
Windows 7_ I7 cpu_ 32 gig ram, NAM knobs freezing upon launch but able to load profiles[BUG]

### ISSUE THREAD

**Issue by refreshener** [sdatkinson/NeuralAmpModelerPlugin#356]
**Thanks for taking the time to write a bug report!** Use the following prompts to help you describe what's going on.  The more info you provide, the easier it'll be to understand how to fix it for you without having to come back and ask you questions.

**Describe the bug**

**To Reproduce**
1. Go to launch NAM from task bar
2. Click on Icon
3. Scroll down to knobs intermintent problem they freeze and dont turn
4. no error msg

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 Windows 7 I7 CPU 32 gig ram
plugin version latest built June 19 2023
 - Standalone and VST3,
 - DAW Studio one

**Additional context**
tried other ASIO drivers and non asio drivers still have the problem.

**Comment by sdatkinson** [comment]
I wonder if this may be related to Windows 7. This repo uses the iPlug2 framework, which [supports](https://iplug2.github.io/) Windows 8 and later.

So, if you're able to reproduce the issue on a more up-to-date OS, I might be able to help. But if not and without any other context, I'm afraid this is out of scope.

**Comment by refreshener** [comment]
Hi nice to hear directly back from you Mr Atkinson. I do not have a windows 8 system with the Iplug2 framework at this time. Sorry to hear there are no other options. Additional update info that should interest you is even though all the knobs and switches visually freeze on NAM, there desired function is working, but blindly have to rely on my ears when adjusting them to accomplish my desired setting. If there is anything further I can do to help this issue for futureWIN7 users with this same problem. I come in the spirit of co-operation as I have IT tech support experience and want to help. Best regards, Joe
