### ISSUE TITLE
UI not responding [BUG]

### ISSUE THREAD

**Issue by Misskanao** [sdatkinson/NeuralAmpModelerPlugin#366]
Im using windows 7 i just want to try these application. It works just fine. The ui is not responding but I can change the parameters (like input value,gate, eq) its just that the knobs are not displaying it. If I click to change the .nam file , it displays the correct value. Im not technically inclined with these things. This app is amazing btw. Thanks in advance

**Comment by sdatkinson** [comment]
> Im using windows 7

This is probably the issue, I'm afraid--[iPlug2 only supports Windows 8 and up.](https://iplug2.github.io/) 

So, I'm going to close this; if you're able to upgrade to a supported system and the issue still happens, feel free to open a new issue and I'll be happy to see if I can help 🙂
