### ISSUE TITLE
Setero bug studio one 6.2[BUG]

### ISSUE THREAD

**Issue by Zeus2000es** [sdatkinson/NeuralAmpModelerPlugin#369]
Latest version of nam
Studio one pro 6.2

When usine nam on a stereo track, the plugin sum the two channel (L-R) to à mono signal.

Help with that, have plenty of profils i cant use

**Comment by sdatkinson** [comment]
This is the current intended functionality: [stereo input is summed to mono (#166)](https://github.com/sdatkinson/NeuralAmpModelerPlugin/pull/166).

Processing two mono signals that are hard-panned L/R on a stereo track (dual mono) is tracked here: #108
