### ISSUE TITLE
[BUG] Build is broken

### ISSUE THREAD

**Issue by sdatkinson** [sdatkinson/NeuralAmpModelerPlugin#371]
[Ope!](https://github.com/sdatkinson/NeuralAmpModelerPlugin/actions/runs/6309924195)

Possibly related to [iPlug2](https://github.com/sdatkinson/NeuralAmpModelerPlugin/actions/runs/6309924195/job/17130829835#step:2:494).

Updating the submodule as in #341 and #370 may do it?

**Comment by olilarkin** [comment]
Just looks like a random CI failure to me

**Comment by sdatkinson** [comment]
Agreed. [Re-run worked](https://github.com/sdatkinson/NeuralAmpModelerPlugin/actions/runs/6335751599)

Whew.
