### ISSUE TITLE
[FEATURE] UI Improvement Idea

### ISSUE THREAD

**Issue by HuoDx** [sdatkinson/NeuralAmpModelerPlugin#385]
Hello! Thanks for starting and contributing to such an amazing project! 

As a new user, I have an slight improvement idea on the UI design: 

- add text "Noise Gate" for the switch at the bottom, so that all switches uniformly have text labels.
- replace text for the knob from "Gate" to "Threshold", so it indicates what the knob does (though the unit makes it pretty simple to infer)

The logic behind this change is to have better unity and clarity for the UI: 

- all switches now have labels (unity); and the function of the knob is more clear
- relationship between texts above and below the separator line is more uniform: "Bass", "Middle", and "Treble" are parameters of "EQ", and now "Threshold" is a parameter for "Noise Gate".

Because the modification is so slight, I have updated it and it looks like this:

![modified version](https://github.com/sdatkinson/NeuralAmpModelerPlugin/assets/58379153/c27e3463-daa2-4f10-b7da-7b9ad4b33965)

Also, I totally get why there's no text for the switch: the warning message! So, I've got another change: to move the warning message to the bottom near the model area and move the IR area a bit lower to leave space. 

This actually makes the error message closer to where the error comes from, also making the hint slightly more intuitive; like this:

![123371699150762_ pic](https://github.com/sdatkinson/NeuralAmpModelerPlugin/assets/58379153/d2157270-900e-45b0-a76e-25acb8aa9e53)

Since the modification is so little, I have already implemented all these changes on my local branch, so if this idea gets approved, I can push my branch and setup PR right away. 

Thanks for your time and consideration!

**Comment by sdatkinson** [comment]
Thanks for the suggestions.

The warning looks a bit squished down there. How about putting it up top below the "NEURAL AMP MODELER"?

If that looks good (I appreciate the demo pictures!) then yes, a PR would probably go quickly 👍🏻

**Comment by HuoDx** [comment]
Great suggestion!
How about this:

<img width="640" alt="Screenshot 2023-11-05 at 12 06 46 PM" src="https://github.com/sdatkinson/NeuralAmpModelerPlugin/assets/58379153/942646c4-8b54-44f0-a236-8d28f091309d">

**Comment by sdatkinson** [comment]
Works for me!

**Comment by HuoDx** [comment]
@sdatkinson  I've posted the PR #387; Thanks!

**Comment by olilarkin** [comment]
I think that the "Thesh"/Gate label change is good! but what about a small red "i" in a circle in the bottom right hand corner? This could also be a button that gives you a little popup with info about the .nam file (.e.g training sample rate etc, model type) - could be white when there is no samplerate mismatch

**Comment by sdatkinson** [comment]
I'm resolving this since the PR is merged.

As far as sample rate etc, I'm thinking to put this all under some "advanced" page with a gear, an ellipsis, or some other icon in the corner. (#460).
