### ISSUE TITLE
[BUG] LSTM models not working in recent builds

### ISSUE THREAD

**Issue by mikeoliphant** [sdatkinson/NeuralAmpModelerPlugin#388]
LSTM models are not working properly in recent builds. On my machine I get silent output.

The last working build seems to be this one:

https://github.com/sdatkinson/NeuralAmpModelerPlugin/actions/runs/6466554198

Which would indicate that this PR broke things:

https://github.com/sdatkinson/NeuralAmpModelerPlugin/pull/377

**Comment by sdatkinson** [comment]
Thanks for flagging this and for providing really helpful details.  Let me have a look at what changed...

**Comment by sdatkinson** [comment]
Ok, I've reproduced it over here with the VST3 in Reaper.

**Comment by sdatkinson** [comment]
Aha..._That'll_ do it! 😂 
<img width="1272" alt="image" src="https://github.com/sdatkinson/NeuralAmpModelerPlugin/assets/12240186/42195760-4113-4c7b-bd42-620007e695d5">

Checking the fix

**Comment by sdatkinson** [comment]
Yep; that'll do it--all better!
<img width="591" alt="image" src="https://github.com/sdatkinson/NeuralAmpModelerPlugin/assets/12240186/6a65d09d-c218-4003-a231-19a5a64bd0e0">

Will PR the fix into the core then here presently

**Comment by mikeoliphant** [comment]
Thanks, Steve!

Looks like I actually introduced the problem when I did the process() overhaul. Super weird that it didn't show up as an issue with the LV2 plugin - the code is clearly wrong, but I'm sure I tested LSTM...

**Comment by mikeoliphant** [comment]
Ahh - turns out that I process the audio buffer in place (input == output) in the LV2 plugin, so the reversal didn't matter... :stuck_out_tongue:
