### ISSUE TITLE
Problem loading IR

### ISSUE THREAD

**Issue by sdatkinson** [sdatkinson/NeuralAmpModelerPlugin#39]
A user reports trouble loading their IR. The plugin shows the failure message. An IR that I provided works for them (and me).

**Comment by sdatkinson** [comment]
The problem is that the IR is stereo. NAM requires mono at the moment.

**Comment by ericsharma** [comment]
@sdatkinson Just wondering if there was any plans to support stereo IRs and if you had any resources for finding good mono IRs
