### ISSUE TITLE
[BUG] Cannot open .nam files in AU plugin

### ISSUE THREAD

**Issue by FlevansGH** [sdatkinson/NeuralAmpModelerPlugin#391]
Hi

Just discovered NAM.  I'm running a new Mac Studio M2 Max, latest OS.

Having downloaded several .nam files (predominantly from ToneHunt), none of them will load in the AU plugin.  After opening up the page to load file, it just returns to the plugin which has nothing loaded.

Any ideas?  Thanks!

**Comment by DivannKokos** [comment]
how old are .nam files? i mean date when they have been uploaded.
i have this kind of problem with several .nam files, that are kinda older, but newer ones loading fine.

**Comment by sdatkinson** [comment]
@FlevansGH Can you share an example of a .nam that does this?

@DivannKokos optional, can you share a pair--one that does, and one that doesn't?

**Comment by sdatkinson** [comment]
Also @FlevansGH , please provide info about the DAW you're using the AU plugin in. Does the same issue happen with the VST3 plugin?

**Comment by sdatkinson** [comment]
Closing this since I haven't heard back from OP in a bit. To re-open, I'd like more info to be able to replicate--give me a model and tell me that DAW's being used, at minimum.
