### ISSUE TITLE
Audio settings not letting me choose which input I want on my audio interface.

### ISSUE THREAD

**Issue by HarriGuitar** [sdatkinson/NeuralAmpModelerPlugin#392]
**Bug**
I have a Focusrite Scarlett Solo Audio Interface.
On the Audio Device Settings in preferences, the inputs and outputs don't show my desired input/output. This happens on DirectSound and ASIO. And both of the Left inputs and outputs it only gives me the option of 1, which is where my mic is inputed but I obviously want my guitar which is in input two. and on both of the Right ones It gives me the option of 1 and two but it's buggy (it sometimes doesn't want to change and sometimes it just goes blank).

I am on Windows 11 and am using the standalone v0.7.5
I also use FL Studio which it will hopefully work with but I would rather use the standalone when I don't want to sort it out every time I want to use it

Screenshots below - 
![NAM issue 1](https://github.com/sdatkinson/NeuralAmpModelerPlugin/assets/106551904/9d3fe5b4-a7bd-4a03-affc-75b8de275449)
![NAM issue 2](https://github.com/sdatkinson/NeuralAmpModelerPlugin/assets/106551904/41a083ff-99ed-4b9c-acef-ce8eda0258d0)
*Output 1 has the same selection on the drop menu as Input 1. Ditto for Output 2.*

**Comment by DivannKokos** [comment]
duplicate #157

**Comment by sdatkinson** [comment]
Closing as duplicate--this is a known issue with the Standalone, unfortunately.
