### ISSUE TITLE
standalone Unable to select the correct input，no sound

### ISSUE THREAD

**Issue by yuanbi1202** [sdatkinson/NeuralAmpModelerPlugin#405]
In the product, the inputs must be left and right channel, but in practice, I only have one guitar input signal from such as input 2 because input 1 is not my guitar,  and I can't select the mono input method, which results in my software not recognizing my input signal, so there is no sound within the software. But when I select the audio device as iMac, he has only one input and the software is able to make sound at this time, I can hear the sound from my microphone in my Mac.

Is it possible for the inputs to be able to change to mono inputs or stereo, it shouldn't be mandatory to choose different input ports for both left and right.

**Comment by yuanbi1202** [comment]
![WechatIMG718](https://github.com/sdatkinson/NeuralAmpModelerPlugin/assets/153414052/b7bc04b7-9f0f-4b57-9500-df0a38667999)
![WechatIMG719](https://github.com/sdatkinson/NeuralAmpModelerPlugin/assets/153414052/29973c0d-0601-4ef2-9db2-1b2b2bdd4f5c)

**Comment by DivannKokos** [comment]
as far as i understand this is known issue 
#386

**Comment by sdatkinson** [comment]
Correct; closing this as a duplicate
