### ISSUE TITLE
VST3 Crash in 0.7.6 (spotted with cubase)

### ISSUE THREAD

**Issue by olilarkin** [sdatkinson/NeuralAmpModelerPlugin#407]
It seems that Cubase crashes when you load a model in 0.7.6.

With your patched version of iPlug2 I think it doesn't crash predictably each time but with the iPlug2/master where I have done further work on the RealtimeResampler [FKA NonIntegerResampler] class it crashes predictably each time (at least on my mac). 

I believe I have tracked it down to a bug with where GetBlockSize() initially returns zero for VST3 in iPlug2. I've fixed that [here](https://github.com/iPlug2/iPlug2/commit/dbca7cfbee0e916d3debadddaa82206557ac7fc6). Since I wasn't able to reliably reproduce the crash with your branch, this is still a theory, but you could try cherry picking that commit to your iPlug2 fork (if you are not yet comfortable to merge #406) and see if it helps the users who are seeing crashes.

hope that helps!

**Comment by sdatkinson** [comment]
Thanks for this! I'm working to see if I can replicate the issue on my side and catch what you described above happening.

**Comment by sdatkinson** [comment]
Well, the bad news is that I can't get 0.7.6 to crash on Cubase.

I've implemented the change you recommended (as well as the correct zeroing of the input buffer array in the Lanczos sampler).

I'm going to have a look through the crash logs I've gotten just to see if there are any other hints there before sharing the new build.
