### ISSUE TITLE
[BUG]still cannot use standalone app, cannot select input 2 ONLY

### ISSUE THREAD

**Issue by 1BrentEdward** [sdatkinson/NeuralAmpModelerPlugin#410]
on many interfaces, you have to select input 2 as the sole input..

the standalone version of this app is unusable because it forces input 1 and 2 as a stereo configuration.  

In other software, say Amplitube, I select input 2 for BOTH left and right inputs.

In your current setup, I cannot make a selection for the Left input, it defaults to 1.  And because of this, it doesn't work, at all.

This should be the highest priority than any other feature requests to just get the basic functionality working.

**Comment by 1BrentEdward** [comment]
duplicate of #386

**Comment by sdatkinson** [comment]
Please +1 #386. Closing this duplicate so that I have one place to focus.
