### ISSUE TITLE
[FEATURE] Proposal to rethink the UX

### ISSUE THREAD

**Issue by dbmann1** [sdatkinson/NeuralAmpModelerPlugin#417]
Thank you very much for your work and have a good New Year!

**Is your feature request related to a problem? Please describe.**
Even though NAM reproduces the high-quality sounds of existing amplifiers, it is first and foremost a piece of software. It would be nice if this could be reflected more in the look and feel in the future.
In view of the fact that NAM creates and plays back snapshots of existing sounds, the storage and selection of these profiles should be made more user-friendly.

**Describe the solution you'd like**
I would like to see an interface that visually organizes similar sounding profiles and IRs in a cloud map.
Inspired by drum sample plugins such as "XO" or "Atlas", similar-sounding amps and IRs could be visually linked and selectable in a map.
Filtering by sound characteristics such as "british", "american", "fenderish" or "high-gainish" could give the user an indication of what sound to expect.
 I have created a first very rough wireframe with Balsamiq:

![New Wireframe 1 (1)](https://github.com/sdatkinson/NeuralAmpModelerPlugin/assets/155324508/ab478625-84ab-4c1b-9eef-99255fef4939)

**Describe alternatives you've considered**
none yet. But I think it would be cool if we continued to think about it together.

**Additional context**
https://www.xlnaudio.com/products/xo
https://algonaut.audio/

**Comment by sdatkinson** [comment]
This is a cool idea and very much the sort of thing I expect could be built on top of the NAM.

Unfortunately, I'm afraid it's out of scope for this repository--I'd like to keep this repo focused as much as possible on playing NAM snapshot models, with a sort of minimal feature set. I could imagine something like what you've described being a completely separate thing--all you need are the models (also something that's not in scope for this repo).

I hope this helps explain, and if you're interested in pursuing this yourself I think you should! 🙂

**Comment by dbmann1** [comment]
That is a pity. Unfortunately, I don't have the developer skills to build something like this myself and my UX skills would also need the support of a team. Do you have any idea who I could approach with this idea? As a user, I would like to see something like this realized.

**Comment by sdatkinson** [comment]
I don't necessarily know of anyone who's looking for a product to develop, but I'd imagine that if they thought it made sense, one of the plugin companies in the industry may take it up. In fact, since you linked those examples from XLN and Algonaut, I suppose you might try asking them? :)

(Or if anyone out there is watching this thread, 👋🏻 😉)

But feel free to shop it around.
