### ISSUE TITLE
Where are the models/IRs?

### ISSUE THREAD

**Issue by alejandroiglesias** [sdatkinson/NeuralAmpModelerPlugin#438]
After installing and opening the app, it seems I should select the models/IRs directories, but I cannot seem to find where those are located. At this point it's not clear if I should look at some directory in my system, if I should download those separately from this repo, or if you don't provide those, in which case it seems I wouldn't be able to use the app at least at this stage in which I don't know where to get models/IRs from. I looked in the manual (it's empty) and did a search on this repo, but couldn't find it. Can you please point me in the direction? Thanks

**Comment by Petervos2018** [comment]
look here : 

https://github.com/pelennor2170/NAM_models

**Comment by alejandroiglesias** [comment]
Thank you @Petervos2018. It may be worthwhile adding that link with instructions on the readme since otherwise, if you're unfamiliar with the project, it's very difficult to figure out what to do after installing NAM.

**Comment by 2-dor** [comment]
> Thank you @Petervos2018. It may be worthwhile adding that link with instructions on the readme since otherwise, if you're unfamiliar with the project, it's very difficult to figure out what to do after installing NAM.

That's a very old repository. 
Look here instead: https://tonehunt.org/all

**Comment by sdatkinson** [comment]
I don't provide them.

You can make models of your own gear using https://github.com/sdatkinson/neural-amp-modeler (or have a look at neuralampmodeler.com/users for a really gentle intro to it).

ToneHunt also works if you want to use other people's models, but I'm not involved in it.
