### ISSUE TITLE
[FEATURE] Mozilla Public License

### ISSUE THREAD

**Issue by RustoMCSpit** [sdatkinson/NeuralAmpModelerPlugin#440]
**Describe the solution you'd like**
Hey Scott, was just wondering if you considered swapping to the MPL instead of MIT? It's like a middle-ground between MIT and GPL in which it can be included in proprietary projects as long as it is kept in a separate file where any changes to that file, any ONLY that file, must be published (oversimplification but it's the best of both worlds).

**Additional context**
[Explainer](https://www.tldrlegal.com/license/mozilla-public-license-2-0-mpl-2)

**Comment by RustoMCSpit** [comment]
If not, why so out of curiousity?

**Comment by sdatkinson** [comment]
In short, it doesn't seem necessary to me. MIT is more permissive.
