### ISSUE TITLE
 [BUG] Random Cubase CRASHES (high priority...)

### ISSUE THREAD

**Issue by boboscorey** [sdatkinson/NeuralAmpModelerPlugin#452]
**Thanks for taking the time to write a bug report!** Use the following prompts to help you describe what's going on.  The more info you provide, the easier it'll be to understand how to fix it for you without having to come back and ask you questions.

**Describe the bug**
Cubase 12, crashes at random times.

**To Reproduce**
Even when the channels using the plugin are "frozen", Cubase can shut down randomly so there's no certain course to recreate the bug

**Screenshots**
When I get to reopen Cubase I get an error tab with some available options, I am going to have to screenshot that and post below.

**Desktop (please complete the following information):**
 - OS [macOS 11.7.9]
 - Plugin version [v0.7.8]
 - VST3
 - DAW [Cubase 12 (original)]
 - Audio interface [MOTU Ultralite MK3]
 - Sample rate [e.g. 44.1 kHz]
 - Buffer size [buffer size won't matter]

**Additional context**
Is there like a proper version of NAM for my macOS?

**Comment by sdatkinson** [comment]
Gonna roll this into #447 (probably the root cause).

**Comment by boboscorey** [comment]
It is not quite the same, since I just get Cubase crashed, no warnings or signs like this, I get my error tab when I reopen Cubase. Also it doesn't have to be one hour, it can crash in let's say 5 minutes...
