### ISSUE TITLE
[FEATURE] is ParametricOD foss?

### ISSUE THREAD

**Issue by RustoMCSpit** [sdatkinson/NeuralAmpModelerPlugin#454]
wheres the source code? i cant find it. if not, why make it free but not open source. amyways thanks for everything you do

**Comment by sdatkinson** [comment]
It's not. A few reasons:

* It wouldn't make sense to release it in isolation; there's a bunch of work outside of the plugin that you'd need as well.
* Open source repos make work for me--especially given how popular this project is. Keeping it closed helps me manage how much time NAM takes from my life.
* As a matter of norms, the expectation should not be that everything associated with NAM is either free or open-source--my stuff included 🙂 

> amyways thanks for everything you do

Thank you! Means a lot to me 🙂

**Comment by RustoMCSpit** [comment]
> As a matter of norms, the expectation should not be that everything associated with NAM is either free or open-source--my stuff included 

oh i kmow that, it's just that i was confused why it was free but not open source. like if it was paid i get that but why make it free lol.

> It wouldn't make sense to release it in isolation; there's a bunch of work outside of the plugin that you'd need as well.

what do you mean
