### ISSUE TITLE
[FEATURE] Skip samples/ms to avoid latency in models with delay

### ISSUE THREAD

**Issue by henrikvilhelmberglund** [sdatkinson/NeuralAmpModelerPlugin#455]
**Thanks for taking the time to write a feature request!** Use the following prompts to help you describe what you're looking for.  The more info you provide, the easier it'll be for me to understand what I can do to make it happen for you without having to come back and ask you questions.

**Is your feature request related to a problem? Please describe.**
Some models have delays for some reason. As in, if I compare the NAM output vs the input signal there's silence at the start of the NAM output.

This is probably due to the training process but can result in models that sound good when reamped but feel bad when tracking/playing.

**Describe the solution you'd like**
I would like a feature where you can skip samples or milliseconds in a model that has obvious (or non obvious) latency to make it respond faster. Maybe something like a delay knob in an IR loader that is used to align different IRs.

No idea if this is even possible but the biggest problem I have with NAM is when using models that sound good but have a delay that makes them feel bad when playing so it would be great if this issue could be solved. Either by a feature like this if possible or if not something in the training process itself.

**Describe alternatives you've considered**
The best alternative is to just switch to another model which seems like a waste.

**Additional context**
N/A

**Comment by sdatkinson** [comment]
It's highly nontrivial to "fix" a model like you're describing. As I'm typing it, it sounds almost silly to say, but that silence is what the model predicts the gear does--so removing that would be "asking the model to predict the future"!

Unfortunately, the direction in which it's easy to modify the latency is in the direction of _increasing_ it 😉 

The best way to keep this from happening is to (A) look closely at the plot when the latency is determined at the start of training with the simplified trainers. If it looks wrong, then (B) set it manually.

---

I've been looking at a few things around this--tweaking the latency calculation algorithm's parameters, and making it easier to set in the Colab trainer (I accidentally made it kind of hidden when I cleaned up the form UI...oops! 😅 )
