### ISSUE TITLE
[BUG] Some profiles won't load up in NAM.

### ISSUE THREAD

**Issue by Yossi530** [sdatkinson/NeuralAmpModelerPlugin#464]
**Describe the bug**
Some models won't load up.
I go to the folder and click on them.
Sometimes they will load up.
Sometimes not.

**To Reproduce**
1. I try to see if its folder problem.
for example if i load up a boost pedal capture and it has 3 modes of boosts.
whenever its in seperated boost mode folders it doesnt work.
whenever its on its own without any folder usage it works.

**Expected behavior**
Would expect it to load up just like any other model profile that loads up normally.

**Screenshots**
![NAMMODEL](https://github.com/sdatkinson/NeuralAmpModelerPlugin/assets/167459355/71d0b6b2-0dc8-4a74-95c8-ef68ee25aee2)

**Desktop (please complete the following information):**
 - OS: Windows 10 64bit
 - Plugin version: 0.7.9
 - Standalone, VST3, or AU : Both Standalone and VST3 wont load the model.
 - DAW (if applicable) Ableton Live 12 Suite
 - Audio interface: Focusrite Scarlett 2i2 2nd Gen
 - Sample rate: 44.1khz
 - Buffer size 256 samples

**Comment by Yossi530** [comment]
yea they load up normally when its on nam main folder.
Neural Amp Modeler/Neural Amp Modeler Profiles
I put them there              ^
Anything else i can do while keeping the folders organized?

**Comment by Yossi530** [comment]
Is it ok to rename nam models? won't it change the capture? and is it ok from the person who did that capture?

**Comment by sdatkinson** [comment]
@Yossi530 can you confirm that saving them in a place with a shorter file path is a workaround?

**Comment by Yossi530** [comment]
Yea, it works.

בתאריך יום ג׳, 7 במאי 2024, 08:35, מאת Dom Mcsweeney ‏<
***@***.***>:
