### ISSUE TITLE
Embedding Nam File

### ISSUE THREAD

**Issue by ValeGen** [sdatkinson/NeuralAmpModelerPlugin#467]
Hi, I'm trying to embed the nam file inside the plugin itself, currently using this code:

`WDL_String path;
        LocateResource("myamp.nam", "nam", path, GetBundleID(), nullptr, nullptr);
        std::unique_ptr<nam::DSP> mymodel = nam::get_dsp(path.Get());
        mModel = std::make_unique<ResamplingNAM>(std::move(mymodel), GetSampleRate());
        mModel->Reset(GetSampleRate(), GetBlockSize());
        mStagedModel = std::move(mModel);`

Works on Mac, but when using windows it just looks for the file outside of the .exe. I included the nam file in the main.rc but still no luck.

**Comment by sdatkinson** [comment]
This seems like a question for [iPlug2](https://github.com/iPlug2/iPlug2)--specifically `LocateResource()`. This functionality isn't part of this repo.  Perhaps you can find more info there.
