### ISSUE TITLE
Problem of latency using NeuralAmpmodeler

### ISSUE THREAD

**Issue by roland6939** [sdatkinson/NeuralAmpModelerPlugin#469]
**Thanks for taking the time to write a bug report!** Use the following prompts to help you describe what's going on.  The more info you provide, the easier it'll be to understand how to fix it for you without having to come back and ask you questions.

**Describe the bug**
Hi,
I am currently using Neural Amp Modeler and i have a Univerasl Audio Volt 276. I have a guitar conected to the Volt 276.
I have a latency time of 2s between the strum of the strings and the sound in the speakers or in the headphones
Tha,nk you for your help and support
Roland

**To Reproduce**

**Expected behavior**

**Screenshots**
See attached file
![Capture d’écran 2024-05-11 160913](https://github.com/sdatkinson/NeuralAmpModelerPlugin/assets/169539754/80bbb9fb-174a-4ca6-9d1b-5eabb8f210f0)

**Desktop (please complete the following information):**
 - OS [e.g. Windows 10, 
 - Plugin version 04/04/2024 - v0.7.9
 - Standalone, VST3, or AU
 - DAW (if applicable)
 - Audio interface: Volt 276
 - Sample rate 44.1 kHz
 - Buffer size 4096

**Additional context**

**Comment by sdatkinson** [comment]
Closing since I assume this was fixed w the above advice.

**Comment by roland6939** [comment]
Dear Steven,Yes it is closed Thank you for your help and support Kind regards RolandEnvoyé depuis l'application Mail Orange----------------De: "Steven Atkinson" ***@***.***>Envoyé: lundi, 27 mai 2024, 1:23À: "sdatkinson/NeuralAmpModelerPlugin" ***@***.***>Cc: "roland6939" ***@***.***>;"Author" ***@***.***>Objet: Re: [sdatkinson/NeuralAmpModelerPlugin] Problem of latency using NeuralAmpmodeler (Issue #469)   
Closing since I assume this was fixed w the above advice.

**Comment by roland6939** [comment]
Dear DomThank you for  your reply I do apologize for my late  answerKind regardsRoland Envoyé depuis mon appareil Galaxy
-------- Message d'origine --------De : Dom Mcsweeney ***@***.***> Date : 13/05/2024  00:36  (GMT+01:00) À : sdatkinson/NeuralAmpModelerPlugin ***@***.***> Cc : roland6939 ***@***.***>, Author ***@***.***> Objet : Re: [sdatkinson/NeuralAmpModelerPlugin] Problem of latency using NeuralAmpmodeler (Issue #469) 
To lower your latency, choose a lower buffer. 8192 is too long. Try something like 64 or 128 @ 48khz, and change 'driver type' from Direct Sound to ASIO.
