### ISSUE TITLE
Works as standalone but crashes as plugin on Ableton [BUG]

### ISSUE THREAD

**Issue by AlexBrutelle** [sdatkinson/NeuralAmpModelerPlugin#472]
**Serious error occured**
I run the installer to have the full install (vst3 + standalone). The standalone runs just fine, but once I open the VST3 on Ableton 11 Lite, Ableton crashes with "serious error occured". 

Any way around that ?

**Comment by sdatkinson** [comment]
Can you fill out the rest of the info requested in a [Bug Report](https://github.com/sdatkinson/NeuralAmpModelerPlugin/issues/new?assignees=&labels=bug%2C+unread%2C+priority%3Alow&projects=&template=bug_report.md&title=%5BBUG%5D)? Thanks!

**Comment by sdatkinson** [comment]
Continuing in #473
