### ISSUE TITLE
NAM as standalone and as plugin crashes after selecting *.nam file

### ISSUE THREAD

**Issue by Hshanoo** [sdatkinson/NeuralAmpModelerPlugin#477]
I use Windows 10 Home with all current updates. The audio interface is Native Instruments Komplete Audio 1.
Standalone application starts and does not work. This means that I can't get the input to be active with any setting - Input power bar is on 0 level and I simply can't hear anything. As for other functionalities of the application, the operation is also not correct. I don't know why, but the first amplifier model I chose after installation was "Helga B 5150 BlockLetter - Boosted" and this model loads correctly (just loads but not working). IR replies can be selected and all the ones I have will load too. The problem occurs when I want to select a different amplifier model. I downloaded all models from GitHub. After loading a different amplifier model, the application crashes.
The situation is similar with the plug-in. I use Cakewalk by Bandlab. The situation is better here, because the plug-in transfers the sound from the guitar. All amplifier parameter settings work correctly. Similarly to the standalone version, the "Helga B 5150 BlockLetter - Boosted" model works, all IR responses work, but as soon as I select a different amplifier model, the plug-in causes Cakewalk to crash - the application immediately turns off.

**Desktop (please complete the following information):**
 - OS: Windows 10 Home with all current updates
 - Plugin version: 0.7.9
 - Standalone, VST3: both
 - DAW: Cakewalk with all current updates
 - Audio interface: Native Instruments Komplete Audio 1
 - Sample rate: e.g. 44.1 kHz
 - Buffer size: Tried with128, 256, 512

**Comment by Hshanoo** [comment]
I just tested this one a moment ago.
[Helga B 6505+ Red Ch - NoBoost rock.zip](https://github.com/sdatkinson/NeuralAmpModelerPlugin/files/15473077/Helga.B.6505%2B.Red.Ch.-.NoBoost.rock.zip)

**Comment by sdatkinson** [comment]
> I just tested this one a moment ago. [Helga B 6505+ Red Ch - NoBoost rock.zip](https://github.com/sdatkinson/NeuralAmpModelerPlugin/files/15473077/Helga.B.6505%2B.Red.Ch.-.NoBoost.rock.zip)

Thanks for sharing that.

The `.nam`file contained in that zip doesn't look like a real model file. Can you open the file with a text editor and confirm that the first few lines look like this?
```






<!DOCTYPE html>
<html
  lang="en"
  
  data-color-mode="auto" data-light-theme="light" data-dark-theme="dark"
  data-a11y-animated-images="system" data-a11y-link-underlines="true"
  >



```

If so, I think there's just a mistake either with how you downloaded the file or how the uploader shared it.

**Comment by sdatkinson** [comment]
It _does_ look like there's a "real" NAM hidden amongst the text of line 1494 of that file 😉

**Comment by sdatkinson** [comment]
Closing this since I haven't back; perhaps that did the trick!
