### ISSUE TITLE
[BUG]Reaper can't find the plugin

### ISSUE THREAD

**Issue by RechiRek** [sdatkinson/NeuralAmpModelerPlugin#484]
**Thanks for taking the time to write a bug report!** Use the following prompts to help you describe what's going on.  The more info you provide, the easier it'll be to understand how to fix it for you without having to come back and ask you questions.

**Describe the bug**
The plug in doesn't show up when I search for it in Reaper, I also downloaded NeuralAmpModeler into the VST Plugin Folder
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 10
 - Latest Plugin Version
 - Both standalone and VST
 - Reaper
 - Focusrite Scarlett Solo 3rd Gen
 - 44.1 kHz
 - 256 samples

**Additional context**

**Comment by sdatkinson** [comment]
>I also downloaded NeuralAmpModeler into the VST Plugin Folder

The download, [NeuralAmpModeler-v0.7.9-win.zip](https://github.com/sdatkinson/NeuralAmpModelerPlugin/releases/download/v0.7.9/NeuralAmpModeler-v0.7.9-win.zip) is an installer. You should be downloading it to wherever, then running the installer, which should install the plug-in to the correct location.

Does that solve the problem?

>Latest Plugin Version

Which version is that?

**Comment by sdatkinson** [comment]
Closing since I haven't heard back in a while; assuming it's fixed.
