### ISSUE TITLE
NAM Crashes Cubase 10 Artist ALL The Time

### ISSUE THREAD

**Issue by vucinawolfman** [sdatkinson/NeuralAmpModelerPlugin#485]
**Thanks for taking the time to write a bug report!** Use the following prompts to help you describe what's going on.  The more info you provide, the easier it'll be to understand how to fix it for you without having to come back and ask you questions.

**Describe the bug**
Sometimes it crashes when I load up the project in Cubase. Most often when the project is open it just crashes randomly after a period. Also sometimes when I render the audio and export. When I load up 2 instances of NAM it is even worse.

**To Reproduce**
Nothing special it happens all by itself.

**Expected behavior**
CRASH

**Desktop (please complete the following information):**
 - Windows 10 x64
 - Version 0.7.7
 - Cubase 10 Artist
 - IK MUltimedia AXe IO SOlo
 - 44.1 kHz
 - Buffer 128

**Comment by sdatkinson** [comment]
Thanks for the info. This is very helpful.

The root problem is probably that you're using version 0.7.7 with a sample rate of 44.1 kHz. There was a slight problem with the resampler that calculation that caused it to drift over time.

There's a fix in NAM version 0.7.9. So go ahead & upgrade and you should be set!

**Comment by sdatkinson** [comment]
Closing this since I haven't heard back / hoping that was it
