### ISSUE TITLE
[BUG] NAM auto crashes in standalone or VST, in multiple DAWs

### ISSUE THREAD

**Issue by baudrillardwasright** [sdatkinson/NeuralAmpModelerPlugin#490]
**Describe the bug**
When I start the standalone, nothing happens - if I'm looking at task manager I can see a process flicker into existence for a second and then disappear without anything showing up on screen. 

If I open the plugin in any DAW (have tried Ableton Live 12 and the most current version of Reaper), it automatically closes the DAW. Reaper gives me no error, Live says "A serious program error has occurred" and closes the program when I click OK on the error. 

**To Reproduce**
Open NAM standalone, or open NAM as VST in any DAW. 

**Expected behavior**
I expect the VST or standalone to open.

**Screenshots**

**Desktop (please complete the following information):**
 - OS Windows 10 Home
 - Plugin version [e.g. 0.7.9]
 - Standalone and VST3
 - DAW - Reaper and Ableton Live 12 
 - Audio interface - Steinberg UR816C
 - Sample rate 44.1 kHz
 - Buffer size 256 samples

processor/graphics - AMD Ryzen 3 3200G with Radeon Vega Graphics (integrated)

**Additional context**

**Comment by olilarkin** [comment]
try updating your graphics drivers

**Comment by sdatkinson** [comment]
@olilarkin, if it's a graphics driver issue, is it possible to catch exceptions like it and alert the user?  The bug reports like this make me feel uncomfortable with the guesswork needed.These types of Issues are tricky to me and it feels like it may be possible to make it more clear what's going wrong?

Alternatively, is there something about the computer that I can ask for in the bug report template that would help pinpoint this as the issue? (E.g. "What graphics drivers do you have installed?" or something like that?)

**Comment by olilarkin** [comment]
It might be possible. I'm just guessing here that if the GUI is not opening in any format, then it's quite possible that there is a problem with the OpenGL driver for the graphics card. The fact that the OP mentioned that they have onboard graphics Also makes me suspicious about this. 

I hope to soon be able to show you how you can switch the graphics backend to skia which doesn't need to use the gpu, and therefore should improve compatibility.

If it is the open GL drivers , This is not an issue unique to iPlug2 or nanovg ... I've heard so many times about flaky OpenGL drivers on windows

**Comment by baudrillardwasright** [comment]
> It might be possible. I'm just guessing here that if the GUI is not opening in any format, then it's quite possible that there is a problem with the OpenGL driver for the graphics card. The fact that the OP mentioned that they have onboard graphics Also makes me suspicious about this.
> 
> I hope to soon be able to show you how you can switch the graphics backend to skia which doesn't need to use the gpu, and therefore should improve compatibility.
> 
> If it is the open GL drivers , This is not an issue unique to iPlug2 or nanovg ... I've heard so many times about flaky OpenGL drivers on windows

Thanks for the response. 

Unfortunately, the computer already has the latest graphics drivers installed. I had seen other bugs with the GPU mentioned which is why I mentioned the onboard graphics.

**Comment by olilarkin** [comment]
Would you be be able to try a few test plug-ins for me? These are recent VST3 CI builds of the iPlug2 example plug-ins. If they fail in the same way on your machine, then I might have something to go on.

I've used different examples so it's easy for you to say which ones work and which ones dont:

[WIN_VST3_IPlugInstrument_SKIA.zip](https://github.com/user-attachments/files/16646548/WIN_VST3_IPlugInstrument_SKIA.zip)
[WIN_VST3_IPlugEffect_NANOVG.zip](https://github.com/user-attachments/files/16646549/WIN_VST3_IPlugEffect_NANOVG.zip)
[WIN_VST3_IPlugControls_SKIA_CPU.zip](https://github.com/user-attachments/files/16646573/WIN_VST3_IPlugControls_SKIA_CPU.zip)

Thanks!

**Comment by olilarkin** [comment]
FYI: working on handling OpenGL problems more gracefully here: https://github.com/iPlug2/iPlug2/pull/1131

**Comment by baudrillardwasright** [comment]
Hey, sorry for the delay. 

Unfortunately for you, and fortunately for me, I don't have any new info for you - all three of the ones you posted worked, so I tried NAM again and it works. I'm not sure what's different... possible I updated my graphics drivers and forgot to restart... 

anyway, thanks!
