### ISSUE TITLE
[FEATURE] Linux version

### ISSUE THREAD

**Issue by kwalker99** [sdatkinson/NeuralAmpModelerPlugin#496]
**Describe the solution you'd like**
a Linux version

**Comment by Petervos2018** [comment]
That could take a while :

https://github.com/sdatkinson/NeuralAmpModelerPlugin/issues/483#issuecomment-2354112813

**Comment by kwalker99** [comment]
aha you are using iplug.. ok np

**Comment by sdatkinson** [comment]
Linux support isn't something I'm really looking to do with this particular plug-in.

However, there are other plug-ins that play NAMs and support Linux e.g. https://github.com/mikeoliphant/neural-amp-modeler-lv2?tab=readme-ov-file which also has links to a few other projects. Hopefully there's something there that will work for you?

**Comment by RustoMCSpit** [comment]
also if this becomes a thing youll have a linux version technically https://github.com/Chowdhury-DSP/BYOD/issues/363

**Comment by RustoMCSpit** [comment]
is this an objection to linux or closing until iplug2 supports it?
