### ISSUE TITLE
[FEATURE] Currently, the UI has the NAM Loader, and Wav loader stretched across the entire UI. If adding both another Nam loader, and Wav loader to the plugin is being planned, you could just minimize the empty space by shifting both current icons to the left, cut the long rectangular space for the loader in half, and add the other two loaders to the right, with their own respective icons.  The reason for another wav loader would be longer IR's such as reverbs.  The reason for the additional Nam loader would be a Boost/OD/Fuzz and so on.  So basically the chain would be this:  Top left=Boost, Top right=NAM, bottom left=Impulse Response, bottom right=Wav loader for Reverb IR's.  I think creating two more icons would be appropriate.  

### ISSUE THREAD

**Issue by GeistRodriguez** [sdatkinson/NeuralAmpModelerPlugin#504]
**Thanks for taking the time to write a feature request!** Use the following prompts to help you describe what you're looking for.  The more info you provide, the easier it'll be for me to understand what I can do to make it happen for you without having to come back and ask you questions.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sdatkinson** [comment]
Thanks for the suggestion, but I believe that [NAM Universal](https://wavemind.net/software) already does what you're looking for :)
