### ISSUE TITLE
[BUG] Standalone won't open; Plugin crashes DAWs

### ISSUE THREAD

**Issue by ITimmyI** [sdatkinson/NeuralAmpModelerPlugin#508]
**Describe the bug**
The standalone application won't open, even when trying to "open as admin". The Plugin will crash the DAW when trying to open NAM

**To Reproduce**
I am not sure how to reproduce the behavior, as I don't do much, other than trying to open the standalone or the plugin.

**Expected behavior**
NAM is expected to start, and the UI to open.

**Screenshots**
I'm not sure if screenshots would be of help, since no specific error code is shown. However, i could make a screen recording if that would help.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Plugin version: v.0.7.10
 - Standalone and VST3
 - DAWs: Ableton, Waveform
 - Audio interface: behringer UMC204HD
 - Sample rate [e.g. 48 kHz]
 - Buffer size [e.g. 512 samples]

**Additional context**
![windows safety popup](https://github.com/user-attachments/assets/d300f058-3896-40e8-8ee1-20b0b25bcf5c)
before installing, windows defender gives me a popup that NAM is a potential threat to the computer. I then click "Run nevertheless" to continue installing.

**Comment by ITimmyI** [comment]
Uploading pluginCrashesWaveformDAW.mp4…

Uploading standaloneWontStart.mp4…

**Comment by ITimmyI** [comment]
Uploading pluginCrashesWaveformDAW.mp4…

**Comment by ITimmyI** [comment]
https://github.com/user-attachments/assets/95887767-ad92-4fb8-a946-359b6a880ef4

**Comment by ITimmyI** [comment]
https://github.com/user-attachments/assets/f3e4d807-b22b-4132-826f-c986c7a12ed3

Thank you for the notice! It should work now.

**Comment by ITimmyI** [comment]
I found the problem. I'm using a Laptop with a dedicated GPU (Nvidia Geforce RTX 3060 Laptop). The onboard Graphics from my CPU (AMD Ryzen 7 5800H with Radeon Graphics) were disabled in the video cards section of my windows device manager. I now activated the onboard graphics in addition to the dedicated GPU and installed the latest driver for them as well. Now NAM works totally fine. However this still keeps this bug alive, I believe. There seems to be a problem with systems that have multiple video cards.

**Comment by sdatkinson** [comment]
Good to know.

I'm not interested in focusing my effort in this repo right now on perfect graphics support, so if you've got a workaround then I'll close this. Thanks for sharing the info; this may help if/when others have a similar issue.
