### ISSUE TITLE
Failed to load IR

### ISSUE THREAD

**Issue by leomoraesguitar** [sdatkinson/NeuralAmpModelerPlugin#51]
It is giving error when adding IR

**Comment by sdatkinson** [comment]
Hi!

Are you on version 0.6.1? If not, I recommend upgrading--it'll h give a little more information about what's going wrong. The most likely possibility is that the wav file that you're using is in a format that the IR loader doesn't support quite yet. I'll be writing to support more kinds of files, but this should help you meet halfway for the moment.

Out of curiosity, what's the IR you're using, or where did it come from? This'll help me figure out what to prioritize supporting.

**Comment by Ni6htWalker** [comment]
same problem here im using IRs from  facebook NAM user group Sebastian Krajewski but IRs from York Audio are loading fine

**Comment by sdatkinson** [comment]
@Ni6htWalker thanks for the report. I can grab one if those and see what's going on. It's probably a new (to NAM) format I just have to get supported, but good to see which formats are out there getting used most often.

**Comment by sdatkinson** [comment]
Closing this since there's been a lot of work on this. If you've got one that doesn't work, open a new Issue and give me an example so I can tackle it.

Thanks!
