### ISSUE TITLE
[FEATURE] Support "gated" models

### ISSUE THREAD

**Issue by 2-dor** [sdatkinson/NeuralAmpModelerPlugin#510]
Hey Steve, folks,

I've been experimenting a bit with some different takes on architectures & setting the "gated" flag to "True" in either one (or both of the layers) of the architecture, seems to help with profile accuracy for when there's a necessity to chase this.

However, when I tried playing back one of these models in the NAM plugin (within Reaper), there is no sound. 

I know it's not priority & most folks are happy with things as they are but just thought I'd ask - maybe this could be added in when time allows for it.

Many thanks!

**Comment by sdatkinson** [comment]
We're good here thanks to #515
