### ISSUE TITLE
[BUG] NAM DON'T WORK ON FL STUDIO

### ISSUE THREAD

**Issue by randy-mm** [sdatkinson/NeuralAmpModelerPlugin#511]
It's my fist time using NAM and this happened : 
![Capture d’écran 2024-10-05 à 17 13 19](https://github.com/user-attachments/assets/707ef68f-a2ff-49b2-978a-d7c275df2f02)

 - macOS High Sierra 10.13.6
 - v0.7.10
 - AU
 - FL Studio
 - UA Volt 76
 - 44,1 Hz
 - 128 samples

**Comment by sdatkinson** [comment]
Correct^, [this plug-in only supports macOS 10.15 and up](https://github.com/sdatkinson/NeuralAmpModelerPlugin?tab=readme-ov-file#supported-platforms).
