### ISSUE TITLE
[BUG] NAM kills ASIO drivers when Initializing or Swapping Models

### ISSUE THREAD

**Issue by StevenLeonCooper** [sdatkinson/NeuralAmpModelerPlugin#518]
## Description
NAM works okay if I load up a project that already has an instance on a track. If I try to move it, add a new one or pick a new model, the ASIO driver just completely freaks out and the entire DAW becomes laggy and won't play back. I have to switch ASIO drivers or restart the app to get anything working again. It specifically happens on a system where I don't have a USB Audio Interface so I'm using ASIO4ALL and also sometimes the Built-in Steinberg ASIO driver (They both work though each has quirks). 

## To reproduce
1. Just add NAM to a track or move it from one track to another. 
2. The ASIO driver goes berserk, the DAW becomes laggy and playback is impossible
3. Restart the DAW or switch ASIO drivers to get things working again
	- Kind of, it's still incredibly buggy and playback clips and stutters randomly. 

## Expected behavior
The app doesn't stall, playback works, doesn't look like you're playing a video game at 3 FPS. 

## Computer & other info
**(please provide the following information):**
 - Windows 10
 - nVidia RTX 3050m
 - NAM 0.7.10
 - VST3
 - Cubase 13 (October '23 Build)
 - No USB Interface (Using ASIO4ALL 15 and Steinberg Generic ASIO, happens with either)
 - 44.1 kHz Sample Rate
 - Buffer size: 512 samples
 - Happens with **1 Plexi 67 Low G8 - Emil Rohbe.nam** (But also even if no model is selected)
 - Happens with **Emil Rohbe YouTube IR.wav** (But also with no IR loaded at all)

## Additional context
The  takeaway here is that NAM does function if you save a project with NAM inserts already on tracks and load it up. **The acts of adding a fresh plugin or moving the plugin from one track to another or selecting a new model** causes the ASIO driver to just utterly break down. I can't tell if it's a memory leak or what (RAM usage does spike) but the entire DAW becomes unusable until the ASIO driver is restarted or the whole DAW is restarted.

**Comment by StevenLeonCooper** [comment]
> Can you try the latest version just released today? Version 0.7.11 should fix this.

I just tried 0.7.11 and I do believe it fixes this specific issue of the ASIO driver crashing when trying to initialize or swap the VST. That said, I'm still getting really choppy playback and glitches even with a 512 sample buffer so NAM isn't really usable for me as a VST insert. 

It's hard to say if this is still a bug or if NAM is just really CPU/RAM intensive. I'm only rocking a Ryzen 5H and 16 GB of RAM on this laptop so maybe a better system could handle it.

**Comment by sdatkinson** [comment]
@StevenLeonCooper 

> It's hard to say if this is still a bug or if NAM is just really CPU/RAM intensive. 

Does the problem happen if you use one of the models [here](https://drive.google.com/drive/folders/15rKS8GDCO451dEd6hAPkeoICRvTZJVxl?usp=drive_link)?

**Comment by sdatkinson** [comment]
Closing bc inactivity; assuming the models linked above work, it's probably that the user is using models that are too big for their CPU.
