### ISSUE TITLE
[BUG] Model info doesn't show when re-opening the UI

### ISSUE THREAD

**Issue by sdatkinson** [sdatkinson/NeuralAmpModelerPlugin#524]
## To reproduce
1. Load model
2. Settings page [pic 1]
3. Close UI
4. Open UI
5. Settings page [pic 2]

## Screenshots
Pic 1:
<img width="593" alt="image" src="https://github.com/user-attachments/assets/c6930724-42a4-4690-9774-5d075893d272">

Pic 2:
<img width="594" alt="image" src="https://github.com/user-attachments/assets/10a22c37-d701-4b1b-b5e1-87858407b5c9">

Seems like the controls are destructed when the UI is closed.

So a solution is to add a way to listen to have the model info control _pull_ from the model info instead of having it _push_ on model staging changes.

**Comment by sdatkinson** [comment]
Note to self: `OnUIOpen()`, `SendControlMsgFromDelegate`, `OnMsgFromDelegate`

**Comment by marmal95** [comment]
A very simple fix would be to just call _NAMSettingsPageControl::SetModelInfo_ inside _NeuralAmpModeler::OnUIOpen_.
As controls are destructed but model seem to stay loaded and in current version _SetModelInfo_ is only called after new model is loaded.
