### ISSUE TITLE
can't change any settings after changing sample rate

### ISSUE THREAD

**Issue by realburger67** [sdatkinson/NeuralAmpModelerPlugin#528]
i'm not very competent in the field. I was messing around with the sample rate as there was a delay between when i played a note on the guitar and when i heard the output. The default sample rate was set to 44100, so i changed it to 4000 to try and see if it worked. It didn't, and now i can't change any settings at all without it crashing. I've already tried uninstalling and reinstalling it. As i already said, i'm not very competent in the field, so i won't be able to give much further information or try to figure out how to solve it myself, and i'm not sure this is the right place to seek help either, but i hope to find a solution to this problem

**Comment by Petervos2018** [comment]
@realburger67 

Maybe remove the settings.ini file from

C:\Users\YOU\AppData\Local\NeuralAmpModeler

and try to start again ?
(just trying to help)

**Comment by realburger67** [comment]
@Petervos2018 

thank you so much, it worked. Again, sorry for my lack of knowledge on the topic
