### ISSUE TITLE
Logic doesn't verify plugin

### ISSUE THREAD

**Issue by ServusJon** [sdatkinson/NeuralAmpModelerPlugin#53]
This is the error when trying to activate the plugin: 

validating Audio Unit NeuralAmpModeler by Steven Atkinson:

    AU Validation Tool
    Version: 1.10.0 
    Copyright 2003-2019, Apple Inc. All Rights Reserved.
    Specify -h (-help) for command options

--------------------------------------------------
VALIDATING AUDIO UNIT: 'aufx' - '1YEo' - 'SDAa'
--------------------------------------------------
Manufacturer String: Steven Atkinson
AudioUnit Name: NeuralAmpModeler
Component Version: 0.6.1 (0x601)

* * PASS
--------------------------------------------------
TESTING OPEN TIMES:
COLD:
Time to open AudioUnit:         6.651 ms
WARM:
Time to open AudioUnit:         0.045  ms
This AudioUnit is a version 2 implementation.
FIRST TIME:
Time for initialization:        0.007 ms

* * PASS
--------------------------------------------------
VERIFYING DEFAULT SCOPE FORMATS:
Input Scope Bus Configuration:
 Default Bus Count:1
    Bus Name: Input
    Default Format: AudioStreamBasicDescription:  2 ch,  48000 Hz, Float32, deinterleaved
    Has Channel Layouts: 0x650002 

Output Scope Bus Configuration:
 Default Bus Count:1
    Bus Name: Output
    Default Format: AudioStreamBasicDescription:  2 ch,  48000 Hz, Float32, deinterleaved
    Has Channel Layouts: 0x650002 

* * PASS
--------------------------------------------------
VERIFYING REQUIRED PROPERTIES:

* * PASS
--------------------------------------------------
VERIFYING RECOMMENDED PROPERTIES:
  VERIFYING PROPERTY: Latency
    PASS
  VERIFYING PROPERTY: Tail Time
    PASS
  VERIFYING PROPERTY: Bypass Effect
    PASS

* * PASS
--------------------------------------------------
VERIFYING OPTIONAL PROPERTIES:

* * PASS
--------------------------------------------------
VERIFYING SPECIAL PROPERTIES:

VERIFYING CUSTOM UI
Cocoa Views Available: 1
  NeuralAmpModeler_View
    PASS

DEFAULT PRESET: 0, Name: 

HAS FACTORY PRESETS

VERIFYING CLASS INFO
WARNING: Preset name is not retained in retrieved class data
    PASS

TESTING HOST CALLBACKS
    PASS

* * PASS
--------------------------------------------------
PUBLISHED PARAMETER INFO:

# # # 6 Global Scope Parameters:

* * PASS
--------------------------------------------------
FORMAT TESTS:

Reported Channel Capabilities (explicit):
      [2, 2]  

Input/Output Channel Handling:
1-1   1-2   1-4   1-5   1-6   1-7   1-8   2-2   2-4   2-5   2-6   2-7   2-8   4-4   4-5   5-5   6-6   7-7   8-8
                                          X                                                                       

# # AudioChannelLayouts (1), Input Scope:
ChannelLayout is Writable: F
The Unit publishes the following Channel Layouts:
  0x650002, 

Is Audio Channel Layout Available:
Mono    Stereo  Binau.  AU_4    Ambi.   AU_5    AU_5_0  AU_6    AU_6_0  AU_7_0  AU_7_0F AU_8    AU_5_1  AU_6_1  AU_7_1  AU_7_1F 
        X                                                                                                                       

# # AudioChannelLayouts (1), Output Scope:
ChannelLayout is Writable: F
The Unit publishes the following Channel Layouts:
  0x650002, 

Is Audio Channel Layout Available:
Mono    Stereo  Binau.  AU_4    Ambi.   AU_5    AU_5_0  AU_6    AU_6_0  AU_7_0  AU_7_0F AU_8    AU_5_1  AU_6_1  AU_7_1  AU_7_1F 
        X                                                                                                                       

* * PASS
--------------------------------------------------
RENDER TESTS:

Input Format: AudioStreamBasicDescription:  2 ch,  48000 Hz, Float32, deinterleaved
Output Format: AudioStreamBasicDescription:  2 ch,  48000 Hz, Float32, deinterleaved
Render Test at 512 frames
Slicing Render Test at 64 frames
  PASS

Render Test at 64 frames, sample rate: 22050 Hz
Render Test at 137 frames, sample rate: 96000 Hz
Render Test at 4096 frames, sample rate: 48000 Hz
Render Test at 4096 frames, sample rate: 192000 Hz
Render Test at 4096 frames, sample rate: 11025 Hz
Render Test at 512 frames, sample rate: 44100 Hz

validation result: Validierung fehlgeschlagen

**Comment by sdatkinson** [comment]
Thanks for the report, and thanks for the logs. (BTW if you enclose the text in a pair of triple backticks, it'll display a little more sanely).

Do you know if earlier versions verify correctly? It'd be helpful if we could pinpoint what version introduced the issue.

**Comment by ServusJon** [comment]
Tested with:
[Version 0.5.6](https://github.com/sdatkinson/NeuralAmpModelerPlugin/releases/tag/v0.5.6)
[Version 0.5.8](https://github.com/sdatkinson/NeuralAmpModelerPlugin/releases/tag/v0.5.8)

same results :(

**Comment by sdatkinson** [comment]
Well, that's unfortunate. It's tough at the moment for me to figure out what's going wrong because the VST3TestPluginHost doesn't seem to show the corresponding failures in what seem to be the most similar unit tests that it runs with the (VST3) plugin.

I'm also had a little bit of a loss to figure out how to get more information about on this myself since I don't own Logic. Is there any way that you can get a more detailed output about what specifically is going wrong? I know that I've seen more complete-looking core dumps when even the release plug-in segfaulted on me in the past...

One other question: do you know whether the plug-in is being tested in the state it initializes into, or do you have the chance to eg pick a model before the validation that's failing gets run? I'm assuming no but just checking in case... Anything to try and figure out where to narrow my focus.

**Comment by ServusJon** [comment]
With the other versions I only tested the standalone versions. They had some really loud buzzing almost like a synth (saw) when playing. I selected different profiles...

**Comment by ServusJon** [comment]
also it crashed a few times as well

**Comment by ServusJon** [comment]
somehow its working now

**Comment by sdatkinson** [comment]
...huh! Mysterious...guess I'll keep my ears open if anyone else reports anything similar.
