### ISSUE TITLE
[BUG] 0.7.12 crashes Gig Perfomer 4

### ISSUE THREAD

**Issue by CarlGalilee** [sdatkinson/NeuralAmpModelerPlugin#539]
## Description
v0.7.12 crashes Gig Performer 4 (windows 10)

## To reproduce
1. Open Gig Performer 4
2. Either add an instance of NAM to a new/existing rackspace or load an existing rackspace with NAM already present 
3. Double click on the NAM plugin instance to open NAM's GUI
4. Gig Performer shuts down before the GUI opens and launches the 'Gig Performer Has Stopped Working' window

## Expected behavior
v0.7.12 works fine within Reaper. 
Rolling back to v0.7.11 works as expected in Gig Performer 4

## Computer & other info
**(please provide the following information):**
 - OS: Windows 10
 - GPU RTX2070
 - Plugin version: 0.7.12
 - VST3
 - DAW: Gig Performer 4
 - Audio interface: Axe I/O
 - Sample rate: 48Khz
 - Buffer size: 64 samples
 - Provide a model that the bug happens with: None loaded
 - Provide an IR that the bug happens with: None Loaded
 - **Does the bug _not_ happen under some other conditions?**: Rolling back to v0.7.11 resolves the issue

**Comment by sdatkinson** [comment]
Probably similar root cause to #541. Fix was shipped in #543. If you can build the latest commit, then give it a test and lmk if it works.
