### ISSUE TITLE
Neural amp modeler fails to show window and crashes Mixcraft 10.5

### ISSUE THREAD

**Issue by GuitArcadeLNX** [sdatkinson/NeuralAmpModelerPlugin#540]
Hey, The new update crashes Mixcraft 9 & 10.5 as well as Jam origin's Midi Guitar 2, If the plugin is already on an existing project, the plugin itself works without having the plugin window open, If I were to open the plugin window, or load a new instance of NAM (window will open automatically) mixcraft crashes and closes immediately.

I can open up mixcraft
Make new project
Load NAM vst
Crashes without fail

Works fine on Ableton live 11 lite & Reaper so I know it's just the programs listed that it won't work on.

Attached is a log file, I tested a plugin that works and nam to see if that helps pinpoint where the crash happens on the log.
[Mixcraft10-Log.txt](https://github.com/user-attachments/files/18051095/Mixcraft10-Log.txt)

Here's the log in text as well of the previous plugin & nam.

02:08:12 [921 mils] : Loading effect NAM Universal (VST3)
02:08:12 [921 mils] : VSTInventory - found GUID, isInstrument = 0, DLL is C:\Program Files\Common Files\VST3\NAM Universal.vst3, bits is 64
02:08:12 [928 mils] : Effect UUID: -2031095517
02:08:12 [928 mils] : Effect Num Inputs: 1
02:08:12 [928 mils] : Effect Num Outputs: 2
02:08:12 [928 mils] : Effect Main Bus Num Inputs: 1
02:08:12 [928 mils] : Effect Main Bus Num Outputs: 2
02:08:12 [928 mils] : Effect Num Input Buses: 1
02:08:12 [928 mils] : Effect Num Output Buses: 1
02:08:12 [928 mils] : Input Bus: 0 Name: Input # of channels: 1
02:08:12 [928 mils] : Output Bus: 0 Name: Output # of channels: 2
02:08:12 [929 mils] : VSTHostWrapper3::Reset(clearbuffers=0) mHasProcessedAudio=0 - Resetting VST3 NAM Universal to sample rate: 44100 and sampleSize:256
02:08:12 [934 mils] : Successfully loaded effect NAM Universal,VST/VST3 reported version 1.0.1, file version 1.0.1.0, file mod time 2024-09-02T13:05:20.000-04:00
02:08:12 [934 mils] : Mem in use percentage = 37 %
02:08:12 [934 mils] : Free physical : 20948.60 MB, Total physical : 33404.38 MB
02:08:12 [934 mils] : Free paging file : 17091.15 MB, Total paging file : 38385.12 MB
02:08:12 [934 mils] : Free virtual : 137433743.96 MB, Total virtual : 137438953.34 MB
02:08:12 [934 mils] : Cur Process -> Working Set Size : 531.48 MB
02:08:12 [934 mils] : Cur Process -> GDI Objects In Use: 239
02:08:12 [934 mils] : Power: AC (plugged in) = 1
02:08:12 [934 mils] : SetFileActivity: FALSE  Current activityCount=1
02:08:12 [934 mils] : Processing FILEACTIVITY
02:08:12 [934 mils] : SetFileActivity exiting.
02:08:12 [936 mils] : ACGuiWindow::ACGuiWindow(Effect Dialog)
02:08:12 [936 mils] : ACGuiWindow::ACGuiWindow() - exit constructor for Effect Dialog
02:08:12 [936 mils] : EffectDialog ctor this 2be8af50 observerCast 2be8b2f0
02:08:12 [936 mils] : Creating Effect Dialog for effect NAM Universal  ID:67, dlgPtr 2be8af50
02:08:12 [954 mils] : Dialog 'VST Dialog' Resize: 300, 180
02:08:12 [955 mils] : ACGuiDialog::Go -> Showing Dialog 'VST Dialog'
02:08:12 [981 mils] : VST3HostWrapper::GetPresetList: num programs 0
02:08:12 [999 mils] : VST3HostWrapper::GetPresetList: num programs 0
02:08:13 [  7 mils] : Dialog 'Track 2 (Audio Track): NAM Universal (VST3) (64-Bit)' Resize: 945, 983
02:08:13 [  7 mils] : VST3ViewCapabilities for NAM Universal: isScalable 1 isResizable 1 minWidth 469 minHeight 457
02:08:13 [ 30 mils] : EffectDialog::Move to 488, 32
02:08:13 [ 31 mils] : EffectDialog exit::Move to 488, 32; mX 488, mY 32, getX 488, getY 9
02:08:13 [ 31 mils] : Exiting EffectDlg.OnInit for NAM Universal
02:08:13 [ 31 mils] : VST3HostWrapper::GetPresetList: num programs 0
02:08:13 [493 mils] : Dialog Shown: virtual x,y 488,29 w,h 945,983; abs x,y 488,29  w,h 945,983
02:08:13 [493 mils] : ACGuiDialog::Go -> Exiting Showing Dialog 'VST Dialog'
02:08:13 [493 mils] : CProject::OpenEffectDialog() added effect dialog:000000002be8af50 effect 000000002d953a70 -> Result: 1
02:08:16 [654 mils] : CProject::DeleteEffectDialog, effectID 67 doAsync 1 bForce 0
02:08:16 [654 mils] : EffectDialog::OnPreDeleteEffectDialog() for effect 2d953a70 (NAM Universal), this 2be8af50 Observer cast 2be8b2f0
02:08:16 [654 mils] : EffectDialog::OnPreDeleteEffectDialog w 937 h 914
02:08:16 [668 mils] : EffectDialog::OnClose() FOR 2be8af50
02:08:16 [668 mils] : CProject::DeleteEffectDialog, effectID 67 doAsync 0 bForce 0
02:08:16 [668 mils] : CProject::DeleteEffectDialog() about to delete effect dialog:2be8af50 effect ID: 67
02:08:16 [668 mils] : EffectDialog::OnPreDeleteEffectDialog() for effect 0 (NULL), this 2be8af50 Observer cast 2be8b2f0
02:08:16 [668 mils] : EffectDialog::CloseAndDeleteWindow() for 2be8af50
02:08:16 [668 mils] : ~EffectDialog 2be8af50
02:08:16 [668 mils] : EffectDialog::OnDestroyZeWindow() for 2be8af50
02:08:16 [668 mils] : OnDestroyZeWindow() Effect NAM Universal closing effect dialog.
02:08:16 [668 mils] : OnDestroyZeWindow() Effect NAM Universal sending preset change notification.
02:08:16 [668 mils] : OnDestroyZeWindow() Done sending preset change notification.
02:08:16 [669 mils] : EffectDialog::OnDestroyZeWindow() EXIT for 2be8af50
02:08:16 [673 mils] : ~EffectDialog 2be8af50 EXIT
02:08:16 [673 mils] : ACGuiWindow::~ACGuiWindow - 2be8af50
02:08:16 [673 mils] : Before cleaning garbage.
02:08:16 [673 mils] : After cleaning garbage.
02:08:18 [276 mils] : ShowDropdown: colW 350 w 352 container: l 348, t 305, w 352, h 717
02:08:25 [883 mils] : SetFileActivity: TRUE  Current activityCount=0
02:08:25 [883 mils] : Processing FILEACTIVITY
02:08:25 [883 mils] : SetFileActivity exiting.
02:08:25 [883 mils] : Loading Effect GUID {A32F8504-0000-0000-0000-000000000000}, isInstrument = 0

02:08:25 [883 mils] : Loading effect NeuralAmpModeler (VST3)
02:08:25 [883 mils] : VSTInventory - found GUID, isInstrument = 0, DLL is C:\Program Files\Common Files\VST3\NeuralAmpModeler.vst3\Contents\x86_64-win\NeuralAmpModeler.vst3, bits is 64
02:08:25 [885 mils] : Effect UUID: -1557166844
02:08:25 [885 mils] : Effect Num Inputs: 2
02:08:25 [885 mils] : Effect Num Outputs: 2
02:08:25 [885 mils] : Effect Main Bus Num Inputs: 2
02:08:25 [885 mils] : Effect Main Bus Num Outputs: 2
02:08:25 [885 mils] : Effect Num Input Buses: 1
02:08:25 [885 mils] : Effect Num Output Buses: 1
02:08:25 [885 mils] : Input Bus: 0 Name: Input # of channels: 2
02:08:25 [885 mils] : Output Bus: 0 Name: Output # of channels: 2
02:08:25 [885 mils] : VSTHostWrapper3::Reset(clearbuffers=0) mHasProcessedAudio=0 - Resetting VST3 NeuralAmpModeler to sample rate: 44100 and sampleSize:256
02:08:25 [885 mils] : Successfully loaded effect NeuralAmpModeler,VST/VST3 reported version 0.7.12, file version 0.0.1.0, file mod time 2024-11-30T18:23:04.000-05:00
02:08:25 [885 mils] : Mem in use percentage = 37 %
02:08:25 [885 mils] : Free physical : 20853.97 MB, Total physical : 33404.38 MB
02:08:25 [885 mils] : Free paging file : 16992.98 MB, Total paging file : 38385.12 MB
02:08:25 [885 mils] : Free virtual : 137433664.98 MB, Total virtual : 137438953.34 MB
02:08:25 [885 mils] : Cur Process -> Working Set Size : 627.43 MB
02:08:25 [885 mils] : Cur Process -> GDI Objects In Use: 250
02:08:25 [885 mils] : Power: AC (plugged in) = 1
02:08:25 [885 mils] : SetFileActivity: FALSE  Current activityCount=1
02:08:25 [885 mils] : Processing FILEACTIVITY
02:08:25 [885 mils] : SetFileActivity exiting.
02:08:25 [885 mils] : ACGuiWindow::ACGuiWindow(Effect Dialog)
02:08:25 [885 mils] : ACGuiWindow::ACGuiWindow() - exit constructor for Effect Dialog
02:08:25 [885 mils] : EffectDialog ctor this 2be8a040 observerCast 2be8a3e0
02:08:25 [885 mils] : Creating Effect Dialog for effect NeuralAmpModeler  ID:68, dlgPtr 2be8a040
02:08:25 [901 mils] : Dialog 'VST Dialog' Resize: 300, 180
02:08:25 [901 mils] : ACGuiDialog::Go -> Showing Dialog 'VST Dialog'
02:08:25 [923 mils] : VST3HostWrapper::GetPresetList: num programs 0
02:08:25 [940 mils] : VST3HostWrapper::GetPresetList: num programs 0
02:08:25 [940 mils] : Dialog 'Track 2 (Audio Track): NeuralAmpModeler (VST3) (64-Bit)' Resize: 608, 469
02:08:25 [941 mils] : VST3ViewCapabilities for NeuralAmpModeler: isScalable 1 isResizable 0 minWidth 0 minHeight 0
02:08:25 [951 mils] : EffectDialog::Move to 656, 289
02:08:25 [951 mils] : EffectDialog exit::Move to 656, 289; mX 656, mY 289, getX 656, getY 266
02:08:25 [952 mils] : Exiting EffectDlg.OnInit for NeuralAmpModeler
02:08:25 [952 mils] : VST3HostWrapper::GetPresetList: num programs 0

**Comment by sdatkinson** [comment]
Assuming this is the same issue as #541. If v0.7.11 works, then I think so.

Just shipped a fix in #543, so I'm going to close this. Feel free to build the latest commit & confirm if you're able.
