### ISSUE TITLE
Plugin version 0.7.12 causes Nembrini Nexus host to crash (exit unexpectedly). And proposed solution inside. 

### ISSUE THREAD

**Issue by synchu** [sdatkinson/NeuralAmpModelerPlugin#541]
Once the plugin (0.7.12) is added and you try to open it, Nexus crashes and exits unexpectedly.

## To reproduce
1. Open Nexus
2. Add NAM 0.7.12
3. Double click on the plugin box to open the plugin UI
4. Nexus crashes and exits (even without error)

## Expected behavior
Plugin GUI opens.

## Screenshots
N/A

## Computer & other info
**(please provide the following information):**
 - OS Windows 11
 - NVidia RTX 2060 Super
 - Plugin version - 0.7.12
  - VST3
 - Nexus plugin host
 - RME RayDat
 - 48Khz
 - 128
 - N/A
 - N/A

## Additional context
The bug is caused potentially by Nexus handling of plugin UI refresh, caused by "endless" loop (initially caused by calling OnTextEntryCompletion, see the Call Stack dump attached - SetParamNormalized <-> performEdit loop):
**NeuralAmpModelerControls.h**
void SetValueFromDelegate(double normalizedValue, int valIdx) override
{
  IControl::SetValueFromDelegate(normalizedValue, valIdx);
  const std::string s = ConvertToString(normalizedValue);
  **-->>>  OnTextEntryCompletion(s.c_str(), valIdx);  <<<---**
};

if this is changed to (which seems to make more sense):

void SetValueFromDelegate(double normalizedValue, int valIdx) override
{
  IControl::SetValueFromDelegate(normalizedValue, valIdx);
  const std::string s = ConvertToString(normalizedValue);
  **SetStr(s.c_str());**
};

The problem is solved.

![image](https://github.com/user-attachments/assets/9563dc9e-14b1-46f6-a3a1-f3da5aa90940)

**Comment by sdatkinson** [comment]
Thanks @synchu for the very nicely-written bug and proposed solution. I don't have Nexus but based on a very quick skim your suggestions sound reasonable.

I'm crunched for time but will come back to this if no one raises their hand to PR first. It should be able to be in 0.7.13.

**Comment by sdatkinson** [comment]
Reproduced this on macOS 15.1 using NA Nexus (not sure which version; just downloaded it now).

Will try #543 now to confirm the fix

**Comment by sdatkinson** [comment]
Yeah, the implementation of `OnTextEntryCompletion` is to `SetStr` then `SetDirty(true)`. I think that we don't want to _not_ `SetDirty`, but have the argument `triggerAction` set to `false` to prevent the chain reaction.

But it should still be redrawn after the new parameter is provided.

---

So I'll tweak the PR and we'll be good! (Checked locally as well)
