### ISSUE TITLE
[BUG] Frequency response shift for different session sample rates

### ISSUE THREAD

**Issue by ishadrin** [sdatkinson/NeuralAmpModelerPlugin#544]
## Description
I measured frequency response shift for different session sample rates. Seems like calculation error. 
Left measurement was done for 192000Hz session sample rate, right for 48000Hz session. NAM file sample rate was 48000Hz. ([link](https://pasttofuturereverbs.gumroad.com/l/ocevw?layout=profile) to the test model)

![Screenshot from 2024-12-14 03-47-34](https://github.com/user-attachments/assets/1fbd90ce-d107-47c3-9194-24c56935812e)

BERTOM EQ Analyzer 2 plugin was used to measure the frequency response. Defect could be also auditioned easily for actual audio application

## Expected behavior
Frequency response should stay the same for different session sample rates

## Computer & other info
I use Reaper 7.28 on Ubuntu

**Comment by synchu** [comment]
I would expect some difference as there's (almost) always some resampling involved in the processing due to the difference in the model's sample rate and the expected output sample rate. 
Especially with 192 KHz processing sample rate as I am yet to see a model @ 192 KHz.

**Comment by ishadrin** [comment]
I'm not sure where is the best place to solve this problem. I used the latest version of the lv2 plugin, compiled from the source code available at this date

**Comment by sdatkinson** [comment]
Hi @ishadrin. This repository isn't the right place for your issue because it sounds like you're not using it.
