### ISSUE TITLE
[BUG] 0.7.12 not opening while on Remote Desktop Session

### ISSUE THREAD

**Issue by ModeNoir** [sdatkinson/NeuralAmpModelerPlugin#546]
My setup is a desktop tower running all kinds of amp sims, solely for that purpose in order to record the output to my laptop and use the zero latency monitoring of my Yamaha THR10 (which I use as my laptop's interface).

So, I connect to the source computer via RD from my laptop. 

NAMU works, Audio Assault Amplocker works. 

NAM for some reason tells me to check the "preferences of the soundcard"! Afterwards it tries to load the GUI but fails and stops with the message "the program stopped working correctly".

My first thought was this might be due to using an older Ghostspectre version of Windows (Potato Edition) and additionally Chris Titus' debloating tool and O&O Shutup to an extreme extent.

To rule it out as a reason I installed a fresh version of Windows 10 (latest) and kept everything standard. Same again.
I also changed the 3 options for "Remote Audio" (Play on this computer, Do not play, Play on remote computer)

NAM will start and work correctly when I attach a screen to the source computer and use it in the usual way.

I am exclusively talking about the standalone versions of the Apps I mentioned here.

**Comment by sdatkinson** [comment]
Does v0.7.11 work?

**Comment by ModeNoir** [comment]
I tested many configs, but I still have to test older NAM V's!

**Comment by ModeNoir** [comment]
Hmm, I tested 0.7.11 and went even lower down to 0.5.8. No success.
