### ISSUE TITLE
I/O Names from Audio Device Driver, Pan Control for Stereo Outputs

### ISSUE THREAD

**Issue by MirrorProfiles** [sdatkinson/NeuralAmpModelerPlugin#6]
as mentioned on Facebook, just some small tweaks to make using standalone a bit nicer (and allowing for easier routing options to cab sims/DAW etc)

<img width="352" alt="Screenshot 2022-12-13 at 09 56 00" src="https://user-images.githubusercontent.com/120493637/207384941-c99dcef4-dff1-4d73-ac9c-31c7f084fc2e.png">
<img width="449" alt="Screenshot 2022-12-13 at 09 57 10" src="https://user-images.githubusercontent.com/120493637/207384952-41dd32db-2a94-487a-a6d5-2dbff4a64b0b.png">

**Comment by sdatkinson** [comment]
This is likely something that'd have to happen upstream with [iPlug2](https://github.com/iplug2/iplug2), so, coming back to this and having a better idea of where the boundaries are, I'm going to close this issue here as out of scope.
