### ISSUE TITLE
[FEATURE] Click through models in a directory

### ISSUE THREAD

**Issue by sdatkinson** [sdatkinson/NeuralAmpModelerPlugin#63]
**Is your feature request related to a problem? Please describe.**
When I want to load a new model, I always have to pick it from the file browser, even if I've already picked a model from a direcotry with tons of models in it.

**Describe the solution you'd like**
The ability to click through models in a directory once you're in there. A pair of arrows to click would do the trick.

**Describe alternatives you've considered**
Can continue to use as-is.

**Additional context**
Requested by a user.

**Comment by jaredbehrens** [comment]
This is probably my number one feature requested feature now that we have single file captures. Previous/Next buttons should do the trick. Thanks for all of your efforts!

**Comment by dmt-hub** [comment]
Next/previous buttons - def no. 1 quality of life feature

**Comment by olilarkin** [comment]
see PR #242

**Comment by olilarkin** [comment]
this can be closed
