### ISSUE TITLE
[BUG] NAM 0.6.2 crashes in Cubase 12 when loading presets

### ISSUE THREAD

**Issue by Eraz102** [sdatkinson/NeuralAmpModelerPlugin#66]
When switching between different presets made in Cubase12 the Plugin crashes the entire DAW.

Steps to reproduce:

1) Add NAM to a track, load a model and save that as a VST3 preset
2) Repeat step 1) multiple times, so you have some different preset to test
3) Load those presets one after another, or use the Arrows in Cubase
4) At some point the screen freezes and the application crashes
5) PS: I found, that if I save presets without a model loaded, and switch between them, the crash does not happen.

Info:
WIN11 - Cubase Pro 12 - i7 8700K - 16 gb RAM
[

https://user-images.githubusercontent.com/110374422/217897774-19f3e4c8-7c81-43af-a876-9ad7f72893bc.mp4

](url)

**Comment by sdatkinson** [comment]
Thanks for the bug (and the video! Very helpful!)

While I'm not sure, my best guess is that there's some memory mismanagement with the WaveNet models that's sneaking by for just a little bit, but ultimately bites it.

Probably related to #38, if I had to guess.

If I can get a proper Valgrind on this I suspect I'll get some hints.

**Comment by Eraz102** [comment]
I just checked, If you duplicate the plugin by  holding ALT and click-dragging it onto an empty slot it crashes as well, when a model is loaded.
Unfortunately no crash dump is created when this happens, so I don't know how I could be of more help 🤔

**Comment by Eraz102** [comment]
UPDATE: It crashes Cubase 12 also, when just adding a new instance of the plugin with no model loaded. Happened twice today when trying around quickly.

**Comment by sdatkinson** [comment]
Can you try updating to the latest version? I'm hoping the fixes in #76 might solve the issue you're having.

**Comment by DaniloMoran** [comment]
I'm using Cubase Pro 12, and NAM 0.7.1 version and i still the same issue, i delete all the VST3 presets, and i did new 3 presets (to make shure that no one NAM file or IR was in another folder or re-named) and still hapenning

**Comment by DaniloMoran** [comment]
Also, i find this particular thing:  if the nam if saved -bypassed- in every preset, the cubase don't crash, just crashing when in the preset the nam is "ON"

**Comment by DaniloMoran** [comment]
https://user-images.githubusercontent.com/132228310/236301914-d7fb71d6-1df4-4f85-a0c8-a25a511a487e.mp4

I don't know if this helps, but i found this about the Issue #66. Cubase doesn't crash if the vst3preset are saved bypassed, and if you bypass NAM before change the preset
I'm using Cubase 12 Pro-NAM 0.7.1

**Comment by sdatkinson** [comment]
I believe this was fixed by #298
