### ISSUE TITLE
[FEATURE] More tone shaping controls

### ISSUE THREAD

**Issue by ServusJon** [sdatkinson/NeuralAmpModelerPlugin#67]
It would be awesome to further fine tune an existing profile:

- Presence
- Gain
- Sag
- Compression
- Pick attack (transient designer)

**Comment by IzuTJ** [comment]
I don't actually know the answer but wouldn't these need to be trained into the model itself?

**Comment by sdatkinson** [comment]
I don't think I'm going to be trying to do things like this within this plugin.
