### ISSUE TITLE
[BUG] Chirp sound at crossfades and at the end of a performance

### ISSUE THREAD

**Issue by Eraz102** [sdatkinson/NeuralAmpModelerPlugin#69]
Not really sure if it should be marked as a bug or an enhancement. In case please reclassify!

When dealing with high gain sounds there is always a "chirp" sound at the end of a guitar performance, if there is a cut without a longer fade out. Also crossfades need to be relatively long to make this noise go away.
Listen to the part, where the strumming goes into the palm mute part and when the palm mute part ends. There is an audible "chirp" sound, which most probably arises, because NAM has trouble to handle loudness differences in short time? 

If you look at the picture it happens in the yellow spots.

Steps to reproduce:

1) record a strumming part
2) record a palm mute part
3) put them together adding short crossfades and end the performance with a clear cut
4) Load a high gain model in NAM
5) listen to the transition where the crossfades are and at the end of the performance

[NAM chirp sound.zip](https://github.com/sdatkinson/NeuralAmpModelerPlugin/files/10736825/NAM.chirp.sound.zip)
![image](https://user-images.githubusercontent.com/110374422/218861705-b0ff2199-d9a2-4e2b-a3d8-2cb63c9bd3e1.png)

**Comment by Eraz102** [comment]
Update: Its also audible in the DAW when hitting play and stopping playback.

**Comment by sdatkinson** [comment]
This seems to be an artifact of the models and not the plugin operating incorrectly. It might be able to be solved at the point of training.

I'm going to close it here and open an issue in [neural-amp-modeler](https://github.com/sdatkinson/neural-amp-modeler).

**Comment by sdatkinson** [comment]
Referenced: https://github.com/sdatkinson/neural-amp-modeler/issues/102
