### ISSUE TITLE
[BUG] DI bleed on Cubase 12 when using mono input and stereo output 

### ISSUE THREAD

**Issue by fcoberrios** [sdatkinson/NeuralAmpModelerPlugin#70]
I just found a bug on Cubase 12, when creating a mono track input with a stereo output configuration the DI bleeds on both channels (On the right channel the DI is even louder). On reaper this is not a problem 

How to replicate it:

Create a track like this:
[https://prnt.sc/purFImrIgTD_](url)
[https://prnt.sc/ktD0Ttbxm8gX](url)

With this configuration nothings happens (Everything works as normal, as it should be)
[https://prnt.sc/So7TeURj4L92](url)

Thank you! :)

**Comment by sdatkinson** [comment]
What version of the plugin are you using?

This sounds like something that might have been solved in #57 and would have been shipped in Version 0.6.2.

**Comment by sdatkinson** [comment]
Never heard back on this, assuming fixed.
