### ISSUE TITLE
Separate path variable stored in DAW for IR and NAM [FEATURE]

### ISSUE THREAD

**Issue by damiangr** [sdatkinson/NeuralAmpModelerPlugin#72]
Hi ! Can you ad separate path variable stored when DAW saves session to store IR and NAM paths separatly? 

Thank you!

**Comment by sdatkinson** [comment]
Can you give me some more detail on what you're looking for here?

The IR and NAM paths _are_ currently stored as separate variables: The former as [`mIRPath`](https://github.com/sdatkinson/NeuralAmpModelerPlugin/blob/3b0cc199e92bdfb720df4bf7a0466133e982ed1a/NeuralAmpModeler/NeuralAmpModeler.h#L152) and the latter as [`mNAMPath`](https://github.com/sdatkinson/NeuralAmpModelerPlugin/blob/3b0cc199e92bdfb720df4bf7a0466133e982ed1a/NeuralAmpModeler/NeuralAmpModeler.h#L150).

**Comment by damiangr** [comment]
Ah ok, so there are separate variable.  Sorry. But still when i browse for nam file and then i browse for IR the plugin open browser with previous nam path.  
I don't know if this is a bug?
