### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by masqutti** [sdatkinson/NeuralAmpModelerPlugin#73]
Continues #33 

Hi! Haven't been able to do much for a while... But I'd like to continue this one. I could just resync the fork and apply the bug fixed I had on my pull request, but you said you prefer more open data structures so I thought that maybe it would be worthwhile to do a struct that would describe the data even more. Do you have info about what all types of stuff can exist in the nam JSON that I can include in the struct?

**Comment by sdatkinson** [comment]
Currently, the models export a JSON with the format defined [here](https://github.com/sdatkinson/neural-amp-modeler/blob/8191f36c97261cb6e24967e45332aab2c638adcd/nam/models/_exportable.py#L42).

You can probably go on that since I don't see any reasons for that to change.
