### ISSUE TITLE
[FEATURE] Allow serial / daisy chaining 2 .nam profiles for loading overdrives 

### ISSUE THREAD

**Issue by 2-dor** [sdatkinson/NeuralAmpModelerPlugin#79]
Seeing how chaining 2 NAM sessions together to use overdrives with amp models has been giving people mixed results because of gain staging, it would probably be helpful if the NAM plugin will eventually give folks the opportunity to load an additional .nam model inside the same instance. 

Currently we have:
- NAM profile loader with tweakable: Input, Bass, Mid, Treble, Output
- IR loader

Suggesting we get:
- Overdrive profile loader with tweakable: Output
- NAM profile loader with tweakable: Input (acts at the input of the plugin, before the overdrive profile in case none is loaded), Bass, Mid, Treble, Output (same as currently is; affects the volume of the plugin itself)
- IR loader

**Comment by sdatkinson** [comment]
I can see how this would be fun.

The GUI would probably need to be larger to fit it all (unless I got pages, but I'm not sure how to do that so I might try to avoid it). Thoughts on that?

**Comment by 2-dor** [comment]
> I can see how this would be fun.
> 
> The GUI would probably need to be larger to fit it all (unless I got pages, but I'm not sure how to do that so I might try to avoid it). Thoughts on that?

Larger GUI should not be a problem.

**Comment by sdatkinson** [comment]
Update: I don't think I'll be pursuing this in this repo.
