### ISSUE TITLE
Save the amp loaded with the preset in the daw

### ISSUE THREAD

**Issue by DarkSkar** [sdatkinson/NeuralAmpModelerPlugin#8]
A good upgrate would be if you could save with a preset the amp loaded.
(If I save the preset and try to open it later it doesn't load the snap folder with it)

Cheers and thank you for sharing your amazing work!

**Comment by sdatkinson** [comment]
I believe this is fixed with PR #12. Look for this fix in the next release!

**Comment by DarkSkar** [comment]
> 

Sorry, I still having this issue with version 0.5.7

**Comment by sdatkinson** [comment]
Hmm, that's unfortunate.

Can you give me some more info then? What your computer/DAW setup is, whether this is the plugin or the standalone, and the steps you take to make the bug happen? (w screenshots would help too if possible)

**Comment by sdatkinson** [comment]
Hmm, yep I see this on macOS running Reaper.

**Comment by DarkSkar** [comment]
> 

Sorry, in my case is in win 11 (last update), vst3 x64 reaper  (last version). I was added here cos it was similar but in my case its not in mac. I am ill today and I can't send more info, I will try after some sleep if I got better. Cheers!
