### ISSUE TITLE
[BUG] nan DB input. Also all knobs are on 0.0

### ISSUE THREAD

**Issue by ServusJon** [sdatkinson/NeuralAmpModelerPlugin#81]
No sound in Logic m1
![Bildschirm­foto 2023-02-27 um 22 32 00](https://user-images.githubusercontent.com/783416/221690442-69480b15-9ade-4530-9b8a-f9daaa6fb575.png)

**Comment by ServusJon** [comment]
this is how the plugin loaded when I opened an old session that i used the previous NAM version

**Comment by ServusJon** [comment]
New NAM instance loaded fine

**Comment by ServusJon** [comment]
on old instances I can't change the input knob. I had to remove the plugin completely and start from scratch

**Comment by sdatkinson** [comment]
Unfortunately, this will be a breaking change moving up to version 0.7. But once you've re-set up things, it should work fine.
