### ISSUE TITLE
[FEATURE] Mix Knob on plugin

### ISSUE THREAD

**Issue by ServusJon** [sdatkinson/NeuralAmpModelerPlugin#83]
Mix knob for the plugin. Especially useful when using models of drive pedals :)

**Comment by sdatkinson** [comment]
Are there any workarounds for this that you know of?

**Comment by sdatkinson** [comment]
I'm aware of a workaround in Reaper (there's a mix parameter by default for every plugin effect), and I believe that there are VST wrappers out there that can achieve this as well.

In order to get closure here, I think I'm going to choose not to implement this feature in this repo.
