### ISSUE TITLE
[BUG]EQ ON, DAW CRASH~

### ISSUE THREAD

**Issue by martjay** [sdatkinson/NeuralAmpModelerPlugin#85]
DAW: FL STUDIO 20.9.2
OS: WIN 11 PRO X64

EQ ON, DAW CRASH~

**Comment by sdatkinson** [comment]
What plugin version are you running?

**Comment by martjay** [comment]
> What plugin version are you running?

0.6.2

**Comment by sdatkinson** [comment]
Is this resolved by updating to [Version 0.7.0](https://github.com/sdatkinson/NeuralAmpModelerPlugin/releases/tag/v0.7.0)?

**Comment by martjay** [comment]
> Is this resolved by updating to [Version 0.7.0](https://github.com/sdatkinson/NeuralAmpModelerPlugin/releases/tag/v0.7.0)?

YO, working perfect now, amazing, thank you man

**Comment by sdatkinson** [comment]
Thanks for letting me know, and glad to hear this did the trick for you!
