### ISSUE TITLE
Xcode compilation error for iOS auv3

### ISSUE THREAD

**Issue by demym** [sdatkinson/NeuralAmpModelerPlugin#87]
Hi,

first of all thanks for this great project, I tried it recently and sounds absolutely awesome !!

I am a developer myself, and I and trying to compile the iOS auv3 plugin, but I get errors in Xcode (using Xcode14).

First of all, in the repository there's an 'Eigen' folder, but its content is empty. What version of Eigen exactly does it needs ? Same for iplug folder, but in that case the iplug repository gets correctly linked here on GitHub.

I attached a screenshot with the errors I get compiling in XCODE:

<img width="841" alt="222376908-14369aa6-c83e-49a9-b02b-54af29b0a46f" src="https://user-images.githubusercontent.com/13074812/222384697-956086b9-98da-495d-9c6a-df4f2b1206ca.png">

Thanks very much in advance and compliments again for the great work !!!

**Comment by sdatkinson** [comment]
Hi!

Thanks for getting into the iOS build. Excited to hear what you find!

The `Eigen` and `iPlug2` directories are submodules. See [`git submodule`](https://git-scm.com/book/en/v2/Git-Tools-Submodules) for more information on what that means & how to work with them.

**Comment by demym** [comment]
Thanks very much @sdatkinson !

So i succeeded into compiling it for iOS Simulator,
but it starts with an error onto the actual device (i have an apple devaccount), something like NeuralModellerPluginAU library not found

I think it would be really great to have this awesome one you did easily portable on iOS

**Comment by olilarkin** [comment]
@demym #92 might help

**Comment by demym** [comment]
Great Oli ! Should I clone your rep (branch fix-iOS) to have those changes in place ?

**Comment by olilarkin** [comment]
yes, or wait for steve to merge

**Comment by demym** [comment]
Thanks @olilarkin.

SO i cloned your repo on fix-ios branch, and all ok, starts immediately on simulator.

For real iphone device, i registered three apple ids, anche changed obviously the entitlements.

But when i launch, app would not install on the phone, and the only way to do that that i've found is to put these following two settings (checked copy only when installing).
<img width="685" alt="Screenshot 2023-03-04 at 09 46 31" src="https://user-images.githubusercontent.com/13074812/222886370-76168787-0b6f-413d-81e6-64f0ff44966d.png">

In this way the app installs on iphone, BUT:

as soon as the splashscreen launches, i get lib not found in xcode and the app breaks:
![Uploading Screenshot 2023-03-04 at 09.47.10.png…]()

Sorry to bug you, but this is so much interesting to leave it alone :-)

Thanks

**Comment by olilarkin** [comment]
Hmm. Yes ticking that option isn't the right solution but your seeing the issue I thought I'd fixed.

**Comment by demym** [comment]
UPDATE: putting the following setting, the app finally started on iPHONE !!

<img width="872" alt="Screenshot 2023-03-04 at 15 37 27" src="https://user-images.githubusercontent.com/13074812/222908491-c5855352-13c2-400e-9c0a-798c16035176.png">


BUT (another one...): when i click 'select model', files app opens up and all seems correct; but i cannot select any file (.nam or .wav for the IR selection) as they all appear as 'grayed' in my files app selection:

![IMG_250FCCA6D805-1](https://user-images.githubusercontent.com/13074812/222908596-2bb5d0ba-8198-4a97-bb23-818730367c39.jpeg)


if i only could load a model and a IR :-)


Thanks

**Comment by olilarkin** [comment]
hold on...

**Comment by sdatkinson** [comment]
> BUT (another one...): when i click 'select model', files app opens up and all seems correct; but i cannot select any file (.nam or .wav for the IR selection) as they all appear as 'grayed' in my files app selection:

Yep, I've been meaning to log this Issue (and Oli mentioned to me roughly how to fix...wonder what he's up to 😉)

[Whew, what a Saturday morning!]

**Comment by olilarkin** [comment]
This issue is covering a few topics already. Basically the template project that got cloned starting off had a problem with iOS in that it didn't work on device. I've since fix that so my pull request overwriting the iOS xcode project is basically updating it to the current state of the template. I'd really not go through a review process on the modifications to the .xcproj files. I'm basically getting the project building / working on iOS

**Comment by olilarkin** [comment]
@demym could you re-checkout #92 and see if you can build to the device? I'm interested if you still need to make the change you mentioned above.

(it actually seems that there is an issue with the DSP on iOS and once you load a .nam it is silent ... not sure what yet)

**Comment by demym** [comment]
@olilarkin , i checked 92, and after just changing the entitlements, ran instantly on simulator and on physical device ! Great job !

Now the next problem: without any audio interface attached (that is only mic and iphone speaker) it's all ok, but app crashes when i attached an external audio interface; in my case i attached a Mooer GE250 (44.1khz) and an HX Stomp (48khz). Those are the only audio interfaces i have by hand, When usb is attached to iphone app crashes unfortunately.


But, anyway, i think you did great steps here. Also the file select now works perfectly !
Thanks really very much

**Comment by sdatkinson** [comment]
@demym should this be closed?

**Comment by demym** [comment]
@sdatkinson , for what concerns the specific bug of not starting on iOS, yes. That’s ok now. Thanks !
