### ISSUE TITLE
[FEATURE] Sample reference .nam models for testing

### ISSUE THREAD

**Issue by mikeoliphant** [sdatkinson/NeuralAmpModelerPlugin#93]
It would be useful to have a few reference .nam models in this repo for testing. It would also be really helpful to have some models trained with different layer channel sizes.

All of the models I've seen are using 16 channels. I'm assuming this number is not only key for accuracy, but also for how expensive the model is to run. Having some models with fewer channels would be very helpful to assess accuracy/performance tradeoffs.

**Comment by 2-dor** [comment]
> It would be useful to have a few reference .nam models in this repo for testing. It would also be really helpful to have some models trained with different layer channel sizes.
> 
> All of the models I've seen are using 16 channels. I'm assuming this number is not only key for accuracy, but also for how expensive the model is to run. Having some models with fewer channels would be very helpful to assess accuracy/performance tradeoffs.

I have several running 20, 21 ...maybe even 24 channels

**Comment by mikeoliphant** [comment]
@2-dor If you could point me at those, that would definitely be helpful (although I would really like some with <16 channels).

**Comment by 2-dor** [comment]
> @2-dor If you could point me at those, that would definitely be helpful (although I would really like some with <16 channels).

https://www.dropbox.com/home/NAM/channels 

problem is they're not the same settings on the amp.. I'll probably do some rounds with the amp dialed in the same way but vary the channels

**Comment by sdatkinson** [comment]
I see the appeal, but I'm not a fan of holding data in a repo. There's a risk that it'll bloat the git repo as the file format inevitably changes in the future.

Do you have any suggestions?

**Comment by mikeoliphant** [comment]
Maybe a separate repo with some reference examples? Or a link to some files stored elsewhere?

Things that would be useful would include input .wav and output .wav for a few captures, along with corresponding .nam models trained on a range of channel sizes.

Failing that, I'd really just like to get my hands on a few .nam models trained using fewer channels. I'm trying to get this running on Raspberry Pi, and 16 channel models are currently still prohibitively expensive to run there (even with the performance improvements I've been able to make so far).

I'll hopefully get set up to train my own models soon, but I haven't yet (I've got a Radeon gfx card, so it is harder to get set up).

**Comment by mikeoliphant** [comment]
I was able to use the colab notebook to generate smaller models - which was easy once I realized what the "architecture" parameter does.

From my testing, the "lite" version runs about 1.5x faster than "standard", while "feather" is more than 2x faster.

I submitted a PR (sdatkinson/neural-amp-modeler/pull/116) that adds some explanation to the easy colab notebook about this.

**Comment by mikeoliphant** [comment]
Btw, I just got "feather" models (along with the other performance tweaks I've made so far) to run on my Raspberry Pi 4 pedalboard.

**Comment by mikeoliphant** [comment]
Closing, as it is more of an issue for the core repo.
