### ISSUE TITLE
C++ Code style

### ISSUE THREAD

**Issue by olilarkin** [sdatkinson/NeuralAmpModelerPlugin#94]
@sdatkinson I know these things are all very subjective, but I find the code style rules that you've imposed on the C++ source code a bit strange and extremely painful to work with.

iPlug2's UI code uses a lot of lambdas and it's very hard to fit them in with the 80 char line limit.

Other gripes...

`this->` used all over the place unnecessarily

`void _Function()` I find the underscore unsightly

sorry :-)

**Comment by sdatkinson** [comment]
No worries--I'm _very_ unopinionated about _what_ the style is as long as (1) there _is_ a style and (2) it can be applied with a single command (see [format.bash](https://github.com/sdatkinson/NeuralAmpModelerPlugin/blob/main/format.bash)).

If you want to change things, all I ask is that it be as easy to enact as it currently is (i.e. running that script).

**Comment by sdatkinson** [comment]
🎉
