### ISSUE TITLE
[BUG] .nam files are grayed out

### ISSUE THREAD

**Issue by sdatkinson** [sdatkinson/NeuralAmpModelerPlugin#96]
**Describe the bug**
Users have reported that when using the model selector, .nam files are grayed out and cannot be selected.

I believe that the root cause is in the usage of [`pGraphics->PromptForFile()`](https://github.com/sdatkinson/NeuralAmpModelerPlugin/blob/d41d873818c2ff301edd7265850d9f94faa2d715/NeuralAmpModeler/NeuralAmpModeler.cpp#L209).

Oli says that iPlug2's  `IGraphics:CreateFileDialog()` method has an argument ext which needs to be provided with a space separated list `“nam json”`

**Comment by olilarkin** [comment]
I have added this as part of #92 , which will also make it work for desktop :-)

**Comment by sdatkinson** [comment]
Thanks so much, @olilarkin!
